%% P06 - Run an FMEA
% Guiding question:
% What inputs, observable effects, and failure modes matter when you run an
% FMEA?

%% Read the boundary and analysis direction before touching a control
disp(['P05 started with cooling loss and worked top-down through ' ...
    'T = S OR (A AND B). P06 keeps the same fixed 1000-hour, no-repair ' ...
    'two-pump mission but works bottom-up, one failure-mode row at a time.']);
disp(['Each row names an item function, one way it can fail, an example ' ...
    'cause, local and higher-level effects, an observable effect, and ' ...
    'current prevention and detection controls.']);
disp(['Read each effect column with only its row mode present and companion ' ...
    'items available. Occurrence rows may co-occur; P05 handles those ' ...
    'combined-event effects.']);
disp(['q is the probability that the mode occurs during the mission. ' ...
    'c is P(indicator annunciates | mode occurs), so q*c is detected and ' ...
    'q*(1-c) is latent. This chain rule does not assume independence.']);

%% Make one prediction, then inspect the deterministic FMEA worksheet
disp(['Prediction: if the Pump-A indicator misses a failure, has the ' ...
    'physical Pump-A failure mode disappeared?']);
baseline = model([0.005 0.10 0.10],[0.98 0.70 0.90]);
worksheetData = { ...
    'Item / required function',baseline.itemFunctions{1}, ...
        baseline.itemFunctions{2},baseline.itemFunctions{3}; ...
    'Failure mode',baseline.failureModes{1},baseline.failureModes{2}, ...
        baseline.failureModes{3}; ...
    'Example cause',baseline.exampleCauses{1},baseline.exampleCauses{2}, ...
        baseline.exampleCauses{3}; ...
    'Local effect',baseline.localEffects{1},baseline.localEffects{2}, ...
        baseline.localEffects{3}; ...
    'Next-higher effect',baseline.nextHigherEffects{1}, ...
        baseline.nextHigherEffects{2},baseline.nextHigherEffects{3}; ...
    'End effect',baseline.endEffects{1},baseline.endEffects{2}, ...
        baseline.endEffects{3}; ...
    'Observable effect',baseline.observableEffects{1}, ...
        baseline.observableEffects{2},baseline.observableEffects{3}; ...
    'Prevention control',baseline.preventionControls{1}, ...
        baseline.preventionControls{2},baseline.preventionControls{3}; ...
    'Detection control',baseline.detectionControls{1}, ...
        baseline.detectionControls{2},baseline.detectionControls{3}; ...
    'Consequence class',baseline.consequenceClasses{1}, ...
        baseline.consequenceClasses{2},baseline.consequenceClasses{3}};
worksheetFigure = figure('Name','P06 lesson baseline: FMEA worksheet', ...
    'Position',[60 80 1320 680]);
uitable(worksheetFigure,'Data',worksheetData,'Units','normalized', ...
    'Position',[0.01 0.02 0.98 0.96], ...
    'ColumnName',{'FMEA field','S - Shared supply','A - Pump A','B - Pump B'}, ...
    'ColumnWidth',{180,340,340,340});
disp(['Read one worksheet mode top to bottom before using a probability: ' ...
    'item/function -> failure mode -> local effect -> next-higher effect ' ...
    '-> end effect -> observable effect and current controls.']);

%% Now view the complementary occurrence-and-observability partition
figure('Name','P06 lesson baseline: FMEA observability');
bar(1:baseline.modeCount,[baseline.failureModeOccurrence(:), ...
    baseline.detectedOccurrence(:),baseline.latentOccurrence(:)], ...
    'grouped');
grid on; xticks(1:baseline.modeCount); xticklabels(baseline.modeIds);
xlabel('FMEA failure-mode row');
ylabel('Probability per fixed 1000-hour mission (dimensionless)');
title('Baseline: every mode occurrence is detected or latent');
legend({'Physical occurrence q','Detected q*c','Latent q*(1-c)'}, ...
    'Location','northwest');
ylim([0 0.12]);
fprintf(['Baseline expected listed mode occurrences per mission: %.4f ' ...
    '= %.4f detected + %.4f latent.\n'],baseline.expectedModeCount, ...
    baseline.expectedDetectedCount,baseline.expectedLatentCount);

%% Move one lever only after reading both baseline views
disp(['Open the live window at this baseline. Revisit one effect chain, ' ...
    'then switch once to its occurrence partition.']);
disp(['Increase only Pump-A occurrence qA and explain why both its ' ...
    'detected and latent paths grow. Reset, then increase only cA and ' ...
    'explain why occurrence stays fixed while observability repartitions.']);
disp(['Finally run experiment.m''s oracle-filtered-log broken case, answer ' ...
    'checks.md one question at a time, and teach back why missing evidence ' ...
    'is not proof that a failure mode is absent.']);
interactive;
