function out = model(failureModeOccurrence,detectionCoverage)
%MODEL Build a fixed three-row FMEA observability accounting model.
%   The three rows reuse P05's fixed 1000-hour, no-repair cooling mission:
%   shared supply output absent, pump A no-flow on demand, and pump B
%   no-flow on demand. FAILUREMODEOCCURRENCE contains dimensionless
%   per-mission probabilities. DETECTIONCOVERAGE contains the conditional
%   probabilities P(indicator annunciates | mode occurs).
%   Effect columns use the FMEA row-under-analysis premise: only that mode
%   is present and every other item is available. Occurrence rows may still
%   co-occur; combined-event effects remain P05 fault-tree work.
arguments
    failureModeOccurrence (1,3) double = [0.005 0.10 0.10]
    detectionCoverage (1,3) double = [0.98 0.70 0.90]
end

validateattributes(failureModeOccurrence,{'double'}, ...
    {'real','finite','>=',0,'<=',1},mfilename, ...
    'failureModeOccurrence');
validateattributes(detectionCoverage,{'double'}, ...
    {'real','finite','>=',0,'<=',1},mfilename, ...
    'detectionCoverage');

% Conditional-probability chain rule. No independence assumption is needed:
% P(mode and detected) = P(mode)*P(detected | mode).
detectedOccurrence = failureModeOccurrence.*detectionCoverage;
latentOccurrence = failureModeOccurrence.*(1-detectionCoverage);
partitionResidual = failureModeOccurrence-detectedOccurrence- ...
    latentOccurrence;

% These sums are expected counts of listed failure-mode rows per mission.
% The rows can co-occur, so none of these sums is a union probability.
expectedModeCount = sum(failureModeOccurrence);
expectedDetectedCount = sum(detectedOccurrence);
expectedLatentCount = sum(latentOccurrence);

% Deliberately wrong completeness claim under a favorable logging premise:
% one oracle-filtered true-positive record exists per detected occurrence,
% with perfect specificity and unique mode attribution. Even then, treating
% those records as the complete FMEA inventory equates "not annunciated"
% with "did not occur." Raw logs can additionally overcount or misattribute.
wrongReportedOccurrence = detectedOccurrence;
wrongExpectedModeCount = sum(wrongReportedOccurrence);
wrongUndercount = expectedModeCount-wrongExpectedModeCount;

out = struct( ...
    'modeCount',3, ...
    'missionDurationHours',1000, ...
    'failureModeOccurrence',failureModeOccurrence, ...
    'detectionCoverage',detectionCoverage, ...
    'detectedOccurrence',detectedOccurrence, ...
    'latentOccurrence',latentOccurrence, ...
    'partitionResidual',partitionResidual, ...
    'expectedModeCount',expectedModeCount, ...
    'expectedDetectedCount',expectedDetectedCount, ...
    'expectedLatentCount',expectedLatentCount, ...
    'wrongReportedOccurrence',wrongReportedOccurrence, ...
    'wrongExpectedModeCount',wrongExpectedModeCount, ...
    'wrongUndercount',wrongUndercount, ...
    'effectAnalysisPremise', ...
    ['Only the row-under-analysis mode is present; all other items ' ...
    'are available'], ...
    'loggingPremise', ...
    ['One oracle-filtered true-positive record per detected occurrence; ' ...
    'perfect specificity and unique mode attribution']);

% Deterministic FMEA row metadata. Consequence classes stay categorical;
% this module does not multiply ordinal labels into a risk-priority score.
out.modeIds = {'S','A','B'};
out.itemFunctions = { ...
    'Shared supply: energize both pumps', ...
    'Pump A: circulate coolant on demand', ...
    'Pump B: circulate coolant on demand'};
out.failureModes = { ...
    'Shared supply output absent', ...
    'Pump A delivers no flow on demand', ...
    'Pump B delivers no flow on demand'};
out.exampleCauses = { ...
    'Supply connector separates', ...
    'Pump-A bearing seizes', ...
    'Pump-B bearing seizes'};
out.localEffects = { ...
    'Cooling bus is de-energized', ...
    'Pump-A branch flow is zero', ...
    'Pump-B branch flow is zero'};
out.nextHigherEffects = { ...
    'Both pumps stop', ...
    'With Pump B available, Pump B alone carries the cooling load', ...
    'With Pump A available, Pump A alone carries the cooling load'};
out.endEffects = { ...
    'Cooling function unavailable', ...
    'With Pump B available, cooling continues; redundancy lost', ...
    'With Pump A available, cooling continues; redundancy lost'};
out.observableEffects = { ...
    'Low cooling-bus voltage', ...
    'Abnormal Pump-A motor current', ...
    'Low Pump-B branch flow'};
out.preventionControls = { ...
    'Connector retention and scheduled inspection', ...
    'Lubrication and pre-mission functional test', ...
    'Lubrication and pre-mission functional test'};
out.detectionControls = { ...
    'Undervoltage monitor', ...
    'Pump-A current-based monitor', ...
    'Pump-B flow switch'};
out.consequenceClasses = { ...
    'Required function lost', ...
    'Degraded redundancy', ...
    'Degraded redundancy'};
end
