function run_checks
%RUN_CHECKS Check P06 FMEA rows, observability, limits, and rejection.
baseline = model([0.005 0.10 0.10],[0.98 0.70 0.90]);
repeat = model([0.005 0.10 0.10],[0.98 0.70 0.90]);
assert(isequal(baseline,repeat), ...
    'Identical inputs must produce identical outputs.');

assert(isscalar(baseline) && baseline.modeCount == 3, ...
    'The FMEA model must remain one scalar result with three fixed rows.');
assert(isequal(size(baseline.failureModeOccurrence),[1 3]) && ...
    isequal(size(baseline.detectionCoverage),[1 3]), ...
    'Both model inputs must remain fixed 1x3 row vectors.');
assert(isequal(size(baseline.detectedOccurrence),[1 3]) && ...
    isequal(size(baseline.latentOccurrence),[1 3]), ...
    'Both observability outputs must remain fixed 1x3 row vectors.');
assert(isequal(baseline.modeIds,{'S','A','B'}), ...
    'The three FMEA rows must retain the P05 S, A, and B identity.');

metadata = {baseline.itemFunctions,baseline.failureModes, ...
    baseline.exampleCauses,baseline.localEffects, ...
    baseline.nextHigherEffects,baseline.endEffects, ...
    baseline.observableEffects,baseline.preventionControls, ...
    baseline.detectionControls,baseline.consequenceClasses};
for k = 1:numel(metadata)
    assert(isequal(size(metadata{k}),[1 3]), ...
        'Every FMEA metadata column must contain exactly three rows.');
    assert(all(~cellfun('isempty',metadata{k})), ...
        'Every FMEA metadata cell must be populated.');
end
assert(numel(unique(baseline.failureModes)) == 3, ...
    'Each row must name a distinct failure mode, not repeat an end effect.');
assert(strcmp(baseline.endEffects{1},'Cooling function unavailable'), ...
    'Shared supply loss must propagate to cooling unavailable.');
assert(strcmp(baseline.endEffects{2}, ...
    'With Pump B available, cooling continues; redundancy lost') && ...
    strcmp(baseline.endEffects{3}, ...
    'With Pump A available, cooling continues; redundancy lost'), ...
    ['Either pump row must explicitly require its healthy companion before ' ...
    'claiming degraded redundancy rather than cooling loss.']);
assert(strcmp(baseline.effectAnalysisPremise, ...
    ['Only the row-under-analysis mode is present; all other items ' ...
    'are available']), ...
    'Effect columns must state the standard single-row analysis premise.');
assert(strcmp(baseline.loggingPremise, ...
    ['One oracle-filtered true-positive record per detected occurrence; ' ...
    'perfect specificity and unique mode attribution']), ...
    'The broken log-only comparison must disclose its favorable logging premise.');
assert(baseline.missionDurationHours == 1000, ...
    'P06 must preserve P05''s fixed 1000-hour mission boundary.');

probabilityOutputs = [baseline.failureModeOccurrence, ...
    baseline.detectionCoverage,baseline.detectedOccurrence, ...
    baseline.latentOccurrence,baseline.wrongReportedOccurrence];
assert(all(isfinite(probabilityOutputs)) && ...
    all(probabilityOutputs >= 0 & probabilityOutputs <= 1), ...
    'Every row probability and coverage must remain finite and in [0,1].');
assert(max(abs(baseline.detectedOccurrence + ...
    baseline.latentOccurrence-baseline.failureModeOccurrence)) < 1e-15, ...
    'Detected plus latent occurrence must equal physical occurrence row by row.');
assert(max(abs(baseline.partitionResidual)) < 1e-15, ...
    'The stored conditional-probability partition residual must be zero.');
assert(abs(baseline.expectedDetectedCount + ...
    baseline.expectedLatentCount-baseline.expectedModeCount) < 1e-15, ...
    'Expected detected and latent row counts must add to the expected mode count.');
assert(isequal(baseline.wrongReportedOccurrence, ...
    baseline.detectedOccurrence), ...
    'The broken log-only inventory must transparently reuse detected occurrence.');
assert(abs(baseline.wrongUndercount-baseline.expectedLatentCount) < 1e-15, ...
    'The log-only expected-count undercount must equal the latent count.');

expectedDetected = [0.0049 0.0700 0.0900];
expectedLatent = [0.0001 0.0300 0.0100];
assert(max(abs(baseline.detectedOccurrence-expectedDetected)) < 1e-15, ...
    'The baseline detected probabilities must match independent q*c values.');
assert(max(abs(baseline.latentOccurrence-expectedLatent)) < 1e-15, ...
    'The baseline latent probabilities must match independent q*(1-c) values.');
assert(abs(baseline.expectedModeCount-0.2050) < 1e-15, ...
    'The baseline expected listed mode count must independently equal 0.2050.');
assert(abs(baseline.expectedDetectedCount-0.1649) < 1e-15, ...
    'The baseline expected detected count must independently equal 0.1649.');
assert(abs(baseline.expectedLatentCount-0.0401) < 1e-15, ...
    'The baseline expected latent count must independently equal 0.0401.');
assert(abs(0.005*0.98-expectedDetected(1)) < 1e-15 && ...
    abs(0.10*0.70-expectedDetected(2)) < 1e-15 && ...
    abs(0.10*0.90-expectedDetected(3)) < 1e-15, ...
    'Independent conditional chain-rule products must reproduce all rows.');

pumpAOccurrenceSweep = [0 0.05 0.10 0.20 0.40];
actualModeCountSweep = zeros(size(pumpAOccurrenceSweep));
actualDetectedCountSweep = zeros(size(pumpAOccurrenceSweep));
actualLatentCountSweep = zeros(size(pumpAOccurrenceSweep));
actualPumpADetectedSweep = zeros(size(pumpAOccurrenceSweep));
actualPumpALatentSweep = zeros(size(pumpAOccurrenceSweep));
for k = 1:numel(pumpAOccurrenceSweep)
    changed = model([0.005 pumpAOccurrenceSweep(k) 0.10], ...
        [0.98 0.70 0.90]);
    actualModeCountSweep(k) = changed.expectedModeCount;
    actualDetectedCountSweep(k) = changed.expectedDetectedCount;
    actualLatentCountSweep(k) = changed.expectedLatentCount;
    actualPumpADetectedSweep(k) = changed.detectedOccurrence(2);
    actualPumpALatentSweep(k) = changed.latentOccurrence(2);
    assert(isequal(changed.failureModeOccurrence([1 3]),[0.005 0.10]), ...
        'Changing qA must leave the supply and Pump-B occurrences unchanged.');
    assert(isequal(changed.detectionCoverage,[0.98 0.70 0.90]), ...
        'Changing qA must leave every detection coverage unchanged.');
    assert(isequal(changed.detectedOccurrence([1 3]), ...
        baseline.detectedOccurrence([1 3])) && ...
        isequal(changed.latentOccurrence([1 3]), ...
        baseline.latentOccurrence([1 3])), ...
        ['Changing qA must leave the supply and Pump-B detected and ' ...
        'latent outputs unchanged.']);
    assert(isequal(changed.failureModes,baseline.failureModes) && ...
        isequal(changed.endEffects,baseline.endEffects), ...
        'Changing qA must not rewrite the FMEA effect chain.');
end
assert(max(abs(actualModeCountSweep- ...
    [0.1050 0.1550 0.2050 0.3050 0.5050])) < 1e-15, ...
    'The occurrence sweep expected mode counts must match references.');
assert(max(abs(actualDetectedCountSweep- ...
    [0.0949 0.1299 0.1649 0.2349 0.3749])) < 1e-15, ...
    'The occurrence sweep detected counts must match references.');
assert(max(abs(actualLatentCountSweep- ...
    [0.0101 0.0251 0.0401 0.0701 0.1301])) < 1e-15, ...
    'The occurrence sweep latent counts must match references.');
assert(max(abs(actualPumpADetectedSweep- ...
    [0 0.035 0.070 0.140 0.280])) < 1e-15, ...
    'Pump-A detected occurrence must remain 0.70*qA throughout sweep 1.');
assert(max(abs(actualPumpALatentSweep- ...
    [0 0.015 0.030 0.060 0.120])) < 1e-15, ...
    'Pump-A latent occurrence must remain 0.30*qA throughout sweep 1.');
assert(all(diff(actualDetectedCountSweep) > 0) && ...
    all(diff(actualLatentCountSweep) > 0), ...
    'Increasing qA must increase both expected observability partitions.');

pumpACoverageSweep = [0 0.25 0.50 0.70 1];
actualPhysicalCoverageSweep = zeros(size(pumpACoverageSweep));
actualDetectedCoverageSweep = zeros(size(pumpACoverageSweep));
actualLatentCoverageSweep = zeros(size(pumpACoverageSweep));
actualPumpADetectedCoverageSweep = zeros(size(pumpACoverageSweep));
actualPumpALatentCoverageSweep = zeros(size(pumpACoverageSweep));
for k = 1:numel(pumpACoverageSweep)
    changed = model([0.005 0.10 0.10], ...
        [0.98 pumpACoverageSweep(k) 0.90]);
    actualPhysicalCoverageSweep(k) = changed.expectedModeCount;
    actualDetectedCoverageSweep(k) = changed.expectedDetectedCount;
    actualLatentCoverageSweep(k) = changed.expectedLatentCount;
    actualPumpADetectedCoverageSweep(k) = changed.detectedOccurrence(2);
    actualPumpALatentCoverageSweep(k) = changed.latentOccurrence(2);
    assert(isequal(changed.failureModeOccurrence,[0.005 0.10 0.10]), ...
        'Changing cA must leave every physical occurrence unchanged.');
    assert(isequal(changed.detectionCoverage([1 3]),[0.98 0.90]), ...
        'Changing cA must leave the other two coverages unchanged.');
    assert(isequal(changed.detectedOccurrence([1 3]), ...
        baseline.detectedOccurrence([1 3])) && ...
        isequal(changed.latentOccurrence([1 3]), ...
        baseline.latentOccurrence([1 3])), ...
        ['Changing cA must leave the supply and Pump-B detected and ' ...
        'latent outputs unchanged.']);
    assert(isequal(changed.failureModes,baseline.failureModes) && ...
        isequal(changed.endEffects,baseline.endEffects), ...
        'Changing cA must not rewrite the FMEA effect chain.');
end
assert(max(abs(actualPhysicalCoverageSweep-0.2050)) < 1e-15, ...
    'Detection coverage must not change expected physical mode occurrence.');
assert(max(abs(actualDetectedCoverageSweep- ...
    [0.0949 0.1199 0.1449 0.1649 0.1949])) < 1e-15, ...
    'The coverage sweep detected counts must match references.');
assert(max(abs(actualLatentCoverageSweep- ...
    [0.1101 0.0851 0.0601 0.0401 0.0101])) < 1e-15, ...
    'The coverage sweep latent counts must match references.');
assert(max(abs(actualPumpADetectedCoverageSweep- ...
    [0 0.025 0.050 0.070 0.100])) < 1e-15, ...
    'Pump-A detected occurrence must equal 0.10*cA throughout sweep 2.');
assert(max(abs(actualPumpALatentCoverageSweep- ...
    [0.100 0.075 0.050 0.030 0])) < 1e-15, ...
    'Pump-A latent occurrence must equal 0.10*(1-cA) throughout sweep 2.');
assert(all(diff(actualDetectedCoverageSweep) > 0) && ...
    all(diff(actualLatentCoverageSweep) < 0), ...
    'Increasing cA must transfer expected count from latent to detected.');
assert(max(abs(actualDetectedCoverageSweep + ...
    actualLatentCoverageSweep-actualPhysicalCoverageSweep)) < 1e-15, ...
    'Coverage sweep partitions must retain the unchanged physical total.');

zeroOccurrence = model([0 0.10 0.10],[0.50 0.70 0.90]);
assert(zeroOccurrence.detectedOccurrence(1) == 0 && ...
    zeroOccurrence.latentOccurrence(1) == 0, ...
    'Zero occurrence must give zero detected and latent paths.');
zeroCoverage = model([0.005 0.10 0.10],[0.98 0 0.90]);
assert(zeroCoverage.detectedOccurrence(2) == 0 && ...
    zeroCoverage.latentOccurrence(2) == 0.10, ...
    'Zero coverage must make Pump-A occurrence entirely latent.');
fullCoverage = model([0.005 0.10 0.10],[0.98 1 0.90]);
assert(fullCoverage.detectedOccurrence(2) == 0.10 && ...
    fullCoverage.latentOccurrence(2) == 0, ...
    'Full coverage must make Pump-A occurrence entirely detected.');
assert(fullCoverage.failureModeOccurrence(2) == ...
    zeroCoverage.failureModeOccurrence(2), ...
    'Coverage limits must not change Pump-A physical occurrence.');

allModesCertain = model([1 1 1],[0.25 0.50 0.75]);
assert(allModesCertain.expectedModeCount == 3, ...
    'Three certain rows must give expected mode count three, not a probability.');
assert(allModesCertain.expectedDetectedCount + ...
    allModesCertain.expectedLatentCount == 3, ...
    'Expected counts above one must still preserve the observability partition.');
tinyOccurrence = model([1e-300 0 0],[0.50 0 0]);
assert(tinyOccurrence.detectedOccurrence(1) > 0 && ...
    tinyOccurrence.latentOccurrence(1) > 0, ...
    'A representable tiny occurrence must survive in both partitions.');
nearPerfectCoverage = model([0 0.10 0],[0 1-eps(1) 0]);
assert(nearPerfectCoverage.latentOccurrence(2) > 0 && ...
    nearPerfectCoverage.detectedOccurrence(2) < 0.10, ...
    'A representable near-perfect coverage gap must remain visible.');

brokenNoObservation = model([0.005 0.10 0.10],[0.98 0 0.90]);
brokenFullObservation = model([0.005 0.10 0.10],[0.98 1 0.90]);
assert(brokenNoObservation.failureModeOccurrence(2) == 0.10 && ...
    brokenNoObservation.wrongReportedOccurrence(2) == 0 && ...
    brokenNoObservation.latentOccurrence(2) == 0.10, ...
    'A log-only inventory must falsely omit a detector-blind Pump-A mode.');
assert(contains(brokenNoObservation.loggingPremise,'perfect specificity') && ...
    contains(brokenNoObservation.loggingPremise,'unique mode attribution'), ...
    'The log-only counterexample must not imply that raw detector logs are error-free.');
assert(abs(brokenNoObservation.wrongExpectedModeCount-0.0949) < 1e-15 && ...
    abs(brokenNoObservation.wrongUndercount-0.1101) < 1e-15, ...
    'The broken inventory must retain its exact recognizable undercount.');
assert(brokenFullObservation.failureModeOccurrence(2) == ...
    brokenNoObservation.failureModeOccurrence(2) && ...
    brokenFullObservation.wrongReportedOccurrence(2) > ...
    brokenNoObservation.wrongReportedOccurrence(2), ...
    'Wrong reported occurrence must rise with coverage despite fixed physics.');

assertRejects(@() model([0.005 0.10],[0.98 0.70 0.90]), ...
    'A wrong-length occurrence vector must be rejected.');
assertRejects(@() model([0.005;0.10;0.10],[0.98 0.70 0.90]), ...
    'A column occurrence vector must be rejected.');
assertRejects(@() model([-0.005 0.10 0.10],[0.98 0.70 0.90]), ...
    'A negative occurrence probability must be rejected.');
assertRejects(@() model([0.005 1.01 0.10],[0.98 0.70 0.90]), ...
    'An occurrence probability above one must be rejected.');
assertRejects(@() model([0.005 NaN 0.10],[0.98 0.70 0.90]), ...
    'A nonfinite occurrence probability must be rejected.');
assertRejects(@() model([0.005 Inf 0.10],[0.98 0.70 0.90]), ...
    'An infinite occurrence probability must be rejected.');
assertRejects(@() model([0.005 0.1i 0.10],[0.98 0.70 0.90]), ...
    'A complex occurrence probability must be rejected.');
assertRejects(@() model([0.005 0.10 0.10],[0.98 0.70]), ...
    'A wrong-length coverage vector must be rejected.');
assertRejects(@() model([0.005 0.10 0.10],[0.98;0.70;0.90]), ...
    'A column coverage vector must be rejected.');
assertRejects(@() model([0.005 0.10 0.10],[-0.01 0.70 0.90]), ...
    'A negative detection coverage must be rejected.');
assertRejects(@() model([0.005 0.10 0.10],[0.98 1.01 0.90]), ...
    'A detection coverage above one must be rejected.');
assertRejects(@() model([0.005 0.10 0.10],[0.98 NaN 0.90]), ...
    'A nonfinite detection coverage must be rejected.');
assertRejects(@() model([0.005 0.10 0.10],[0.98 Inf 0.90]), ...
    'An infinite detection coverage must be rejected.');
assertRejects(@() model([0.005 0.10 0.10],[0.98 0.7i 0.90]), ...
    'A complex detection coverage must be rejected.');

recovered = model([0.005 0.10 0.10],[0.98 0.70 0.90]);
assert(isequal(recovered,baseline), ...
    'Rejected malformed calls must not contaminate a later valid calculation.');

disp(['P06 checks passed. Explain how bottom-up FMEA rows complement P05 ' ...
    'and why detector logs cannot be the complete mode inventory.']);
end

function assertRejects(operation,message)
didReject = false;
try
    operation();
catch
    didReject = true;
end
assert(didReject,message);
end
