%% P08 - Prioritize Risk Quantitatively
% Guiding question:
% What inputs, observable effects, and failure modes matter when you
% prioritize Risk Quantitatively?

%% Read the decision model before looking at a score
disp(['P06 named S, A, and B failure modes and their observable effects. ' ...
    'P07 placed those events in one fixed 1000-hour mission and produced ' ...
    'a five-state disjoint outcome ledger.']);
disp(['P08 keeps that ledger. It assigns each of four loss-bearing scenarios ' ...
    'a synthetic consequence in kUSD per occurrence, then computes expected ' ...
    'loss = scenario probability times consequence. Only S and A&B are ' ...
    'mission failures; either single-pump loss is degraded mission success.']);
disp(['The answer has units kUSD per mission. It is a conditional economic ' ...
    'priority, not a safety-acceptance decision or evidence that the inputs ' ...
    'were measured in service.']);

%% Make one prediction, then inspect the deterministic baseline probabilities
disp(['Prediction: will the rarest, most expensive scenario necessarily be ' ...
    'the first priority once occurrence and consequence are combined?']);
baseline = model([0.005 0.10 0.10],[120 100 8 12]);
probabilityFigure = figure('Name','P08 lesson baseline: disjoint outcomes');
probabilityAxes = axes('Parent',probabilityFigure);
bar(probabilityAxes,1:5,baseline.outcomeProbabilities,0.68);
grid(probabilityAxes,'on'); xticks(probabilityAxes,1:5);
xticklabels(probabilityAxes,{'S fails','A and B fail', ...
    'B fails only','A fails only','All work'});
ylabel(probabilityAxes, ...
    ['Scenario occurrence probability per fixed 1000-hour mission ' ...
    '(dimensionless)']);
title(probabilityAxes,'Start with P07 mutually exclusive outcomes');
ylim(probabilityAxes,[0 1]);
disp(['The first four outcomes can carry economic loss. The first two fail ' ...
    'the mission; the next two succeed with one pump. The all-working outcome ' ...
    'closes the ledger to one and carries no loss in this teaching model.']);

%% Advance once to the common-unit expected-loss view
rankingFigure = figure('Name','P08 lesson baseline: expected-loss priority');
rankingAxes = axes('Parent',rankingFigure);
bar(rankingAxes,1:4,baseline.expectedLossKusdPerMission,0.68);
grid(rankingAxes,'on'); xticks(rankingAxes,1:4);
xticklabels(rankingAxes,baseline.scenarioIds);
ylabel(rankingAxes,'Expected loss (kUSD/fixed 1000-hour mission)');
title(rankingAxes,'Probability times consequence changes the priority order');
ylim(rankingAxes,[0 1.2]);
fprintf(['Expected losses [S, A&B, B only, A only] = ' ...
    '[%.4f %.4f %.4f %.4f] kUSD/mission.\n'], ...
    baseline.expectedLossKusdPerMission(1), ...
    baseline.expectedLossKusdPerMission(2), ...
    baseline.expectedLossKusdPerMission(3), ...
    baseline.expectedLossKusdPerMission(4));
disp(['Observe: A-only ranks first even though its consequence per occurrence ' ...
    'is much smaller than S loss. Its probability is large enough to make ' ...
    'its expected contribution larger.']);

%% Move one lever, reset, then move the independent lever
disp(['Open the live window at baseline. First change only q_S and observe ' ...
    'how the mutually exclusive P07 outcome probabilities reallocate.']);
disp(['Reset. Then change only the A&B consequence. Every scenario ' ...
    'probability must remain fixed while just one expected-loss bar moves.']);
disp(['Run experiment.m one section at a time to see both exact sweeps and ' ...
    'the deliberately broken ordinal-product priority.']);
interactive;
