function out = model(basicEventFailureProbabilities,consequenceCostKusd)
%MODEL Rank four disjoint P07 outcomes by expected economic loss.
%   The basic events are [S,A,B] failures over the fixed 1000-hour,
%   no-repair mission. The four priced scenarios follow P07's outcome
%   order: S fails; S works and A/B fail; S/A work and B fails; S/B work
%   and A fails. The first two are mission failures. The next two are
%   degraded mission successes with one failed pump. Consequences are
%   synthetic kUSD per scenario occurrence.
arguments
    basicEventFailureProbabilities (1,3) double = [0.005 0.10 0.10]
    consequenceCostKusd (1,4) double = [120 100 8 12]
end

validateattributes(basicEventFailureProbabilities,{'double'}, ...
    {'real','finite','>=',0,'<=',1},mfilename, ...
    'basicEventFailureProbabilities');
validateattributes(consequenceCostKusd,{'double'}, ...
    {'real','finite','>=',0,'<=',1e6},mfilename, ...
    'consequenceCostKusd');

qS = basicEventFailureProbabilities(1);
qA = basicEventFailureProbabilities(2);
qB = basicEventFailureProbabilities(3);
rS = 1-qS;
rA = 1-qA;
rB = 1-qB;

% These priced outcomes are mutually exclusive and exhaustive with the
% all-components-working state. Preserve P07's separate mission boundary:
% only the first two outcomes fail S AND (A OR B); the next two succeed in
% degraded one-pump operation.
scenarioProbabilities = [ ...
    qS, ...
    rS*qA*qB, ...
    rS*rA*qB, ...
    rS*qA*rB];
healthyProbability = rS*rA*rB;
outcomeProbabilities = [scenarioProbabilities healthyProbability];
systemFailureProbability = sum(outcomeProbabilities(1:2));
systemReliability = sum(outcomeProbabilities(3:5));
probabilityClosureResidual = sum(outcomeProbabilities)-1;

% Expected economic loss is ratio-scale probability times a consequence
% in one common unit. Because the scenarios are disjoint, their expected
% losses may be added without double counting.
expectedLossKusdPerMission = scenarioProbabilities.*consequenceCostKusd;
totalExpectedLossKusdPerMission = sum(expectedLossKusdPerMission);
if totalExpectedLossKusdPerMission == 0
    riskShares = zeros(1,4);
else
    riskShares = expectedLossKusdPerMission./ ...
        totalExpectedLossKusdPerMission;
end

% Rank larger expected loss first. Exact ties retain the canonical P07
% scenario order so the result is deterministic without hidden state.
scenarioIndexes = 1:4;
greaterCounts = sum(expectedLossKusdPerMission.' > ...
    expectedLossKusdPerMission,1);
tieBeforeCounts = sum((expectedLossKusdPerMission.' == ...
    expectedLossKusdPerMission) & ...
    (scenarioIndexes.' < scenarioIndexes),1);
priorityRanks = 1+greaterCounts+tieBeforeCounts;
priorityOrder = zeros(1,4);
priorityOrder(priorityRanks) = scenarioIndexes;
sortedExpectedLossKusdPerMission = ...
    expectedLossKusdPerMission(priorityOrder);

% Transparent local sensitivities show what each of the two lesson levers
% changes at the current point.
expectedLossSensitivityToSharedSupplyProbability = [ ...
    consequenceCostKusd(1), ...
    -qA*qB*consequenceCostKusd(2), ...
    -rA*qB*consequenceCostKusd(3), ...
    -qA*rB*consequenceCostKusd(4)];
totalLossSensitivityToSharedSupplyProbability = ...
    sum(expectedLossSensitivityToSharedSupplyProbability);
totalLossSensitivityToDualPumpConsequence = ...
    scenarioProbabilities(2);

% Deliberately broken comparison: ordered categories are multiplied as if
% equal steps and ratios had physical meaning. All four products tie even
% though the common-unit expected losses do not.
ordinalOccurrenceRatings = [2 2 5 5];
ordinalSeverityRatings = [5 5 2 2];
wrongOrdinalProductScores = ...
    ordinalOccurrenceRatings.*ordinalSeverityRatings;
wrongOrdinalScoreSpread = max(wrongOrdinalProductScores)- ...
    min(wrongOrdinalProductScores);
expectedLossSpreadKusdPerMission = ...
    max(expectedLossKusdPerMission)-min(expectedLossKusdPerMission);

out = struct( ...
    'missionDurationHours',1000, ...
    'basicEventFailureProbabilities',basicEventFailureProbabilities, ...
    'basicEventSuccessProbabilities',[rS rA rB], ...
    'scenarioProbabilities',scenarioProbabilities, ...
    'systemFailureProbability',systemFailureProbability, ...
    'systemReliability',systemReliability, ...
    'healthyProbability',healthyProbability, ...
    'outcomeProbabilities',outcomeProbabilities, ...
    'probabilityClosureResidual',probabilityClosureResidual, ...
    'consequenceCostKusd',consequenceCostKusd, ...
    'expectedLossKusdPerMission',expectedLossKusdPerMission, ...
    'totalExpectedLossKusdPerMission', ...
        totalExpectedLossKusdPerMission, ...
    'riskShares',riskShares, ...
    'priorityRanks',priorityRanks, ...
    'priorityOrder',priorityOrder, ...
    'sortedExpectedLossKusdPerMission', ...
        sortedExpectedLossKusdPerMission, ...
    'expectedLossSensitivityToSharedSupplyProbability', ...
        expectedLossSensitivityToSharedSupplyProbability, ...
    'totalLossSensitivityToSharedSupplyProbability', ...
        totalLossSensitivityToSharedSupplyProbability, ...
    'totalLossSensitivityToDualPumpConsequence', ...
        totalLossSensitivityToDualPumpConsequence, ...
    'ordinalOccurrenceRatings',ordinalOccurrenceRatings, ...
    'ordinalSeverityRatings',ordinalSeverityRatings, ...
    'wrongOrdinalProductScores',wrongOrdinalProductScores, ...
    'wrongOrdinalScoreSpread',wrongOrdinalScoreSpread, ...
    'expectedLossSpreadKusdPerMission', ...
        expectedLossSpreadKusdPerMission);

out.basicEventIds = {'S','A','B'};
out.scenarioIds = {'S','A&B','B only','A only'};
out.scenarioNames = { ...
    'Shared supply fails', ...
    'Supply works; both pumps fail', ...
    'Supply and Pump A work; Pump B fails', ...
    'Supply and Pump B work; Pump A fails'};
out.topPriorityScenarioId = out.scenarioIds{priorityOrder(1)};
out.quantificationAssumption = [ ...
    'S, A, and B basic-event failures are mutually independent over the ' ...
    'same fixed mission; scenario consequences use comparable kUSD'];
out.rankingTieBreak = ...
    'exact expected-loss ties retain canonical P07 outcome order';
out.riskUnit = 'kUSD per fixed 1000-hour mission';
out.consequenceUnit = 'kUSD per scenario occurrence';
end
