function run_checks
%RUN_CHECKS Check P08 probability, loss, ranking, limits, and rejection.
baselineProbabilities = [0.005 0.10 0.10];
baselineConsequences = [120 100 8 12];
baseline = model(baselineProbabilities,baselineConsequences);
repeat = model(baselineProbabilities,baselineConsequences);
assert(isequal(baseline,repeat), ...
    'Identical inputs must produce identical outputs.');

assert(isscalar(baseline) && baseline.missionDurationHours == 1000, ...
    'The model must return one result for P07''s fixed 1000-hour mission.');
assert(isequal(size(baseline.basicEventFailureProbabilities),[1 3]) && ...
    isequal(size(baseline.basicEventSuccessProbabilities),[1 3]), ...
    'Basic-event probability outputs must remain fixed 1x3 rows.');
assert(isequal(size(baseline.scenarioProbabilities),[1 4]) && ...
    isequal(size(baseline.consequenceCostKusd),[1 4]) && ...
    isequal(size(baseline.expectedLossKusdPerMission),[1 4]), ...
    'Scenario probability, consequence, and risk outputs must remain fixed 1x4 rows.');
assert(isequal(size(baseline.outcomeProbabilities),[1 5]), ...
    'The complete P07 outcome ledger must remain a fixed 1x5 row.');
assert(isscalar(baseline.systemFailureProbability) && ...
    isscalar(baseline.systemReliability), ...
    'P07 mission failure and success outputs must remain scalar.');
assert(isequal(baseline.basicEventIds,{'S','A','B'}), ...
    'P08 must retain P06 and P07 basic-event identity.');
assert(isequal(baseline.scenarioIds,{'S','A&B','B only','A only'}), ...
    'Risk scenarios must retain P07 outcome order.');
assert(numel(baseline.scenarioNames) == 4 && ...
    all(~cellfun('isempty',baseline.scenarioNames)), ...
    'Every risk scenario must retain an explanatory name.');
assert(contains(baseline.quantificationAssumption,'mutually independent') && ...
    contains(baseline.quantificationAssumption,'comparable kUSD'), ...
    'The basic-event and consequence assumptions must remain explicit.');
assert(strcmp(baseline.riskUnit, ...
    'kUSD per fixed 1000-hour mission') && ...
    strcmp(baseline.consequenceUnit,'kUSD per scenario occurrence'), ...
    'Risk and consequence units must remain explicit.');

probabilityOutputs = [baseline.basicEventFailureProbabilities, ...
    baseline.basicEventSuccessProbabilities, ...
    baseline.scenarioProbabilities,baseline.systemFailureProbability, ...
    baseline.systemReliability,baseline.healthyProbability, ...
    baseline.outcomeProbabilities,baseline.riskShares];
assert(all(isfinite(probabilityOutputs)) && ...
    all(probabilityOutputs >= 0 & probabilityOutputs <= 1), ...
    'Every baseline probability and risk share must be finite and bounded.');
assert(max(abs(baseline.basicEventFailureProbabilities + ...
    baseline.basicEventSuccessProbabilities-1)) < 1e-15, ...
    'Each basic-event failure and success probability must be complementary.');
assert(abs(baseline.probabilityClosureResidual) < 1e-15 && ...
    abs(sum(baseline.outcomeProbabilities)-1) < 1e-15, ...
    'The five mutually exclusive P07 outcomes must close to one.');

expectedOutcomes = [0.00500 0.00995 0.08955 0.08955 0.80595];
assert(max(abs(baseline.outcomeProbabilities-expectedOutcomes)) < 1e-15, ...
    'Baseline outcome probabilities must match independent P07 references.');
assert(max(abs(baseline.scenarioProbabilities-expectedOutcomes(1:4))) < 1e-15, ...
    'The four ranked scenarios must be the first four P07 outcomes.');
assert(abs(baseline.systemFailureProbability-0.01495) < 1e-15 && ...
    abs(baseline.systemReliability-0.98505) < 1e-15 && ...
    abs(sum(baseline.outcomeProbabilities(1:2))- ...
    baseline.systemFailureProbability) < 1e-15 && ...
    abs(sum(baseline.outcomeProbabilities(3:5))- ...
    baseline.systemReliability) < 1e-15, ...
    ['The first two outcomes must remain P07 mission failures and the last ' ...
    'three must remain mission successes.']);
expectedLosses = [0.6000 0.9950 0.7164 1.0746];
assert(max(abs(baseline.expectedLossKusdPerMission-expectedLosses)) < 1e-12, ...
    'Baseline expected losses must equal probability times consequence.');
assert(abs(baseline.totalExpectedLossKusdPerMission-3.3860) < 1e-12, ...
    'Baseline total expected loss must independently equal 3.3860 kUSD.');
assert(abs(sum(baseline.riskShares)-1) < 1e-15 && ...
    max(abs(baseline.riskShares-expectedLosses/3.3860)) < 1e-15, ...
    'Risk shares must partition the positive total expected loss.');
assert(isequal(baseline.priorityRanks,[4 2 3 1]) && ...
    isequal(baseline.priorityOrder,[4 2 3 1]), ...
    'Baseline priority must be A only, A&B, B only, then S.');
assert(strcmp(baseline.topPriorityScenarioId,'A only') && ...
    isequal(baseline.sortedExpectedLossKusdPerMission, ...
    expectedLosses([4 2 3 1])), ...
    'Top identity and sorted risk values must match the transparent rank.');

independentScenarioReference = [ ...
    baselineProbabilities(1), ...
    (1-baselineProbabilities(1))*baselineProbabilities(2)* ...
        baselineProbabilities(3), ...
    (1-baselineProbabilities(1))*(1-baselineProbabilities(2))* ...
        baselineProbabilities(3), ...
    (1-baselineProbabilities(1))*baselineProbabilities(2)* ...
        (1-baselineProbabilities(3))];
assert(max(abs(baseline.scenarioProbabilities- ...
    independentScenarioReference)) < 1e-15, ...
    'Independent scenario arithmetic must reproduce the disjoint ledger.');
assert(max(abs(baseline.expectedLossKusdPerMission- ...
    baseline.scenarioProbabilities.*baseline.consequenceCostKusd)) < 1e-15, ...
    'Every risk contribution must retain the visible P times C identity.');
assert(max(abs(baseline.expectedLossSensitivityToSharedSupplyProbability- ...
    [120 -1 -0.72 -1.08])) < 1e-12 && ...
    abs(baseline.totalLossSensitivityToSharedSupplyProbability-117.2) < 1e-12, ...
    'Shared-supply sensitivity must include the opposing disjoint paths.');
assert(abs(baseline.totalLossSensitivityToDualPumpConsequence-0.00995) < 1e-15, ...
    'Dual-pump consequence sensitivity must equal its scenario probability.');

sharedSupplyFailureProbabilitySweep = [0 0.005 0.01 0.02 0.05];
actualSupplyProbabilities = zeros(5,4);
actualSupplyLosses = zeros(5,4);
actualSupplyTotals = zeros(1,5);
actualSupplyOrders = zeros(5,4);
for k = 1:numel(sharedSupplyFailureProbabilitySweep)
    changed = model([sharedSupplyFailureProbabilitySweep(k) 0.10 0.10], ...
        baselineConsequences);
    actualSupplyProbabilities(k,:) = changed.scenarioProbabilities;
    actualSupplyLosses(k,:) = changed.expectedLossKusdPerMission;
    actualSupplyTotals(k) = changed.totalExpectedLossKusdPerMission;
    actualSupplyOrders(k,:) = changed.priorityOrder;
    assert(isequal(changed.basicEventFailureProbabilities(2:3),[0.10 0.10]), ...
        'Changing q_S must leave q_A and q_B unchanged.');
    assert(isequal(changed.consequenceCostKusd,baselineConsequences), ...
        'Changing q_S must leave every consequence unchanged.');
    assert(abs(sum(changed.outcomeProbabilities)-1) < 1e-15, ...
        'Every q_S sweep ledger must remain a complete partition.');
end
expectedSupplyProbabilities = [ ...
    0     0.01000 0.09000 0.09000; ...
    0.005 0.00995 0.08955 0.08955; ...
    0.010 0.00990 0.08910 0.08910; ...
    0.020 0.00980 0.08820 0.08820; ...
    0.050 0.00950 0.08550 0.08550];
expectedSupplyLosses = [ ...
    0.0 1.000 0.7200 1.0800; ...
    0.6 0.995 0.7164 1.0746; ...
    1.2 0.990 0.7128 1.0692; ...
    2.4 0.980 0.7056 1.0584; ...
    6.0 0.950 0.6840 1.0260];
assert(max(abs(actualSupplyProbabilities(:)- ...
    expectedSupplyProbabilities(:))) < 1e-15, ...
    'The q_S sweep scenario probabilities must match independent references.');
assert(max(abs(actualSupplyLosses(:)-expectedSupplyLosses(:))) < 1e-12, ...
    'The q_S sweep expected losses must match independent references.');
assert(max(abs(actualSupplyTotals-[2.800 3.386 3.972 5.144 8.660])) < 1e-12, ...
    'The q_S sweep totals must match independent references.');
assert(isequal(actualSupplyOrders,[ ...
    4 2 3 1;4 2 3 1;1 4 2 3;1 4 2 3;1 4 2 3]), ...
    'The q_S sweep must expose its first post-crossover sample at 0.01.');
exactSupplyPriorityCrossover = 1.08/(120+1.08);
atSupplyPriorityCrossover = model( ...
    [exactSupplyPriorityCrossover 0.10 0.10],baselineConsequences);
assert(abs(exactSupplyPriorityCrossover-0.00891972249752230) < 1e-15 && ...
    abs(atSupplyPriorityCrossover.expectedLossKusdPerMission(1)- ...
    atSupplyPriorityCrossover.expectedLossKusdPerMission(4)) < 1e-12, ...
    ['S and A-only expected losses must cross at the exact q_S value, ' ...
    'before the 0.01 sweep sample.']);
assert(all(diff(actualSupplyLosses(:,1)) > 0) && ...
    all(all(diff(actualSupplyLosses(:,2:4),1,1) < 0)), ...
    ['Increasing q_S must raise S loss and lower every mutually exclusive ' ...
    'supply-up contribution.']);

dualPumpConsequenceSweepKusd = [0 25 50 100 200];
actualConsequenceProbabilities = zeros(5,4);
actualConsequenceLosses = zeros(5,4);
actualConsequenceTotals = zeros(1,5);
actualConsequenceOrders = zeros(5,4);
for k = 1:numel(dualPumpConsequenceSweepKusd)
    changed = model(baselineProbabilities, ...
        [120 dualPumpConsequenceSweepKusd(k) 8 12]);
    actualConsequenceProbabilities(k,:) = changed.scenarioProbabilities;
    actualConsequenceLosses(k,:) = changed.expectedLossKusdPerMission;
    actualConsequenceTotals(k) = changed.totalExpectedLossKusdPerMission;
    actualConsequenceOrders(k,:) = changed.priorityOrder;
    assert(isequal(changed.basicEventFailureProbabilities, ...
        baselineProbabilities), ...
        'Changing A&B consequence must leave every basic-event input unchanged.');
    assert(isequal(changed.consequenceCostKusd([1 3 4]),[120 8 12]), ...
        'Changing A&B consequence must leave every non-target consequence unchanged.');
end
probabilityIsolationResidual = actualConsequenceProbabilities- ...
    repmat(baseline.scenarioProbabilities,5,1);
assert(max(abs(probabilityIsolationResidual(:))) < 1e-15, ...
    'A consequence sweep must leave every scenario probability fixed.');
expectedDualPumpLoss = [0 0.24875 0.49750 0.99500 1.99000];
assert(max(abs(actualConsequenceLosses(:,2).'-expectedDualPumpLoss)) < 1e-12, ...
    'The A&B consequence sweep risk must equal 0.00995 times consequence.');
assert(max(abs(actualConsequenceTotals- ...
    [2.39100 2.63975 2.88850 3.38600 4.38100])) < 1e-12, ...
    'The A&B consequence sweep totals must match independent references.');
nonTargetLossResidual = actualConsequenceLosses(:,[1 3 4])- ...
    repmat(expectedLosses([1 3 4]),5,1);
assert(max(abs(nonTargetLossResidual(:))) < 1e-12, ...
    'Changing A&B consequence must leave all non-target risks fixed.');
assert(isequal(actualConsequenceOrders,[ ...
    4 3 1 2;4 3 1 2;4 3 1 2;4 2 3 1;2 4 3 1]), ...
    'The consequence sweep must expose the intended priority transitions.');
crossover = model(baselineProbabilities,[120 108 8 12]);
assert(abs(crossover.expectedLossKusdPerMission(2)- ...
    crossover.expectedLossKusdPerMission(4)) < 1e-12, ...
    'A&B and A-only expected losses must cross at 108 kUSD.');

noFailures = model([0 0 0],baselineConsequences);
assert(isequal(noFailures.scenarioProbabilities,[0 0 0 0]) && ...
    noFailures.healthyProbability == 1 && ...
    noFailures.totalExpectedLossKusdPerMission == 0, ...
    'No basic-event failures must give a healthy mission and zero risk.');
certainSupplyFailure = model([1 0.10 0.10],baselineConsequences);
assert(isequal(certainSupplyFailure.outcomeProbabilities,[1 0 0 0 0]) && ...
    isequal(certainSupplyFailure.expectedLossKusdPerMission,[120 0 0 0]), ...
    'Certain supply failure must make every supply-up scenario impossible.');
certainDualPumpFailure = model([0 1 1],baselineConsequences);
assert(isequal(certainDualPumpFailure.outcomeProbabilities,[0 1 0 0 0]) && ...
    isequal(certainDualPumpFailure.expectedLossKusdPerMission,[0 100 0 0]), ...
    'Certain dual-pump loss with a perfect supply must select only A&B.');
singlePumpFailure = model([0 1 0],baselineConsequences);
assert(isequal(singlePumpFailure.outcomeProbabilities,[0 0 0 1 0]) && ...
    singlePumpFailure.systemFailureProbability == 0 && ...
    singlePumpFailure.systemReliability == 1 && ...
    singlePumpFailure.healthyProbability == 0 && ...
    isequal(singlePumpFailure.expectedLossKusdPerMission,[0 0 0 12]), ...
    ['A certain Pump-A failure with Pump B working must retain mission ' ...
    'success while carrying the degraded-operation loss.']);
zeroConsequences = model(baselineProbabilities,[0 0 0 0]);
assert(zeroConsequences.totalExpectedLossKusdPerMission == 0 && ...
    isequal(zeroConsequences.riskShares,[0 0 0 0]) && ...
    isequal(zeroConsequences.priorityRanks,[1 2 3 4]) && ...
    isequal(zeroConsequences.priorityOrder,[1 2 3 4]), ...
    'Zero consequences must give zero shares and canonical deterministic ties.');
nonzeroPartialTie = model(baselineProbabilities,[120 100 12 12]);
assert(nonzeroPartialTie.expectedLossKusdPerMission(3) == ...
    nonzeroPartialTie.expectedLossKusdPerMission(4) && ...
    isequal(nonzeroPartialTie.priorityRanks,[4 3 1 2]) && ...
    isequal(nonzeroPartialTie.priorityOrder,[3 4 2 1]), ...
    'A nonzero partial tie must retain canonical P07 scenario order.');

original = model([0.02 0.20 0.40],[90 70 11 13]);
swapped = model([0.02 0.40 0.20],[90 70 13 11]);
assert(abs(original.totalExpectedLossKusdPerMission- ...
    swapped.totalExpectedLossKusdPerMission) < 1e-12 && ...
    max(abs(original.expectedLossKusdPerMission([1 2])- ...
    swapped.expectedLossKusdPerMission([1 2]))) < 1e-12 && ...
    abs(original.expectedLossKusdPerMission(3)- ...
    swapped.expectedLossKusdPerMission(4)) < 1e-12 && ...
    abs(original.expectedLossKusdPerMission(4)- ...
    swapped.expectedLossKusdPerMission(3)) < 1e-12, ...
    'Swapping Pump A and B with their single-mode costs must preserve total risk.');

tinyScenario = model([realmin 0 0],[1 0 0 0]);
assert(tinyScenario.scenarioProbabilities(1) == realmin && ...
    tinyScenario.expectedLossKusdPerMission(1) == realmin && ...
    tinyScenario.expectedLossKusdPerMission(1) > 0, ...
    'A representable tiny scenario and expected loss must not be discarded.');
maximumSupported = model([0.25 0.50 0.75],ones(1,4)*1e6);
assert(all(isfinite(maximumSupported.expectedLossKusdPerMission)) && ...
    isfinite(maximumSupported.totalExpectedLossKusdPerMission), ...
    'The fixed consequence resource bound must remain finite and usable.');

assert(isequal(baseline.ordinalOccurrenceRatings,[2 2 5 5]) && ...
    isequal(baseline.ordinalSeverityRatings,[5 5 2 2]), ...
    'The broken case must retain its named ordinal categories.');
assert(isequal(baseline.wrongOrdinalProductScores,[10 10 10 10]) && ...
    baseline.wrongOrdinalScoreSpread == 0, ...
    'Ordinal multiplication must retain the recognizable all-tied symptom.');
assert(abs(baseline.expectedLossSpreadKusdPerMission-0.4746) < 1e-12, ...
    'Common-unit expected losses must expose what the ordinal tie hides.');

assertRejects(@() model([0.005 0.10],baselineConsequences), ...
    'A wrong-length basic-event vector must be rejected.');
assertRejects(@() model([0.005;0.10;0.10],baselineConsequences), ...
    'A column basic-event vector must be rejected.');
assertRejects(@() model([-0.001 0.10 0.10],baselineConsequences), ...
    'A negative basic-event probability must be rejected.');
assertRejects(@() model([0.005 1.01 0.10],baselineConsequences), ...
    'A basic-event probability above one must be rejected.');
assertRejects(@() model([0.005 NaN 0.10],baselineConsequences), ...
    'A nonfinite basic-event probability must be rejected.');
assertRejects(@() model([0.005 Inf 0.10],baselineConsequences), ...
    'An infinite basic-event probability must be rejected.');
assertRejects(@() model([0.005 0.10 0.10i],baselineConsequences), ...
    'A complex basic-event probability must be rejected.');
assertRejects(@() model(baselineProbabilities,[120 100 8]), ...
    'A wrong-length consequence vector must be rejected.');
assertRejects(@() model(baselineProbabilities,[120;100;8;12]), ...
    'A column consequence vector must be rejected.');
assertRejects(@() model(baselineProbabilities,[120 -1 8 12]), ...
    'A negative consequence must be rejected.');
assertRejects(@() model(baselineProbabilities,[120 1e6+1 8 12]), ...
    'A consequence above the resource bound must be rejected.');
assertRejects(@() model(baselineProbabilities,[120 NaN 8 12]), ...
    'A nonfinite consequence must be rejected.');
assertRejects(@() model(baselineProbabilities,[120 Inf 8 12]), ...
    'An infinite consequence must be rejected.');
assertRejects(@() model(baselineProbabilities,[120 100i 8 12]), ...
    'A complex consequence must be rejected.');

recovered = model(baselineProbabilities,baselineConsequences);
assert(isequal(recovered,baseline), ...
    'Rejected malformed calls must not contaminate exact recovery.');

disp(['P08 checks passed. Explain why P07 disjoint scenarios support ' ...
    'common-unit expected-loss priority, how probability and consequence ' ...
    'levers differ, and why ordinal products cannot supply quantitative risk.']);
end

function assertRejects(operation,message)
didReject = false;
try
    operation();
catch
    didReject = true;
end
assert(didReject,message);
end
