function out = model(effectivenessLossFraction,predictorGainLpmPerCommand, ...
    rippleAmplitudeLpm)
%MODEL Generate a command-conditioned Pump-A diagnostic residual.
%   The deterministic teaching plant uses normalized speed command u(t),
%   measured cooling flow y(t), and nominal prediction y_hat(t|u). The
%   residual sign convention is r(t)=y(t)-y_hat(t|u), so loss of measured
%   flow produces a negative residual when the predictor is matched.
arguments
    effectivenessLossFraction (1,1) double = 0.20
    predictorGainLpmPerCommand (1,1) double = 10
    rippleAmplitudeLpm (1,1) double = 0.10
end

validateattributes(effectivenessLossFraction,{'double'}, ...
    {'real','finite','>=',0,'<=',1},mfilename, ...
    'effectivenessLossFraction');
validateattributes(predictorGainLpmPerCommand,{'double'}, ...
    {'real','finite','>=',0,'<=',20},mfilename, ...
    'predictorGainLpmPerCommand');
validateattributes(rippleAmplitudeLpm,{'double'}, ...
    {'real','finite','>=',0,'<=',1},mfilename, ...
    'rippleAmplitudeLpm');

samplePeriodSeconds = 0.1;
timeSeconds = (0:samplePeriodSeconds:30).';
commandStepTimeSeconds = 10;
faultTimeSeconds = 20;
lowCommand = 0.5;
highCommand = 0.8;
nominalGainLpmPerCommand = 10;
rippleFrequencyHz = 0.5;

speedCommand = lowCommand*ones(size(timeSeconds));
speedCommand(timeSeconds >= commandStepTimeSeconds) = highCommand;
faultActive = double(timeSeconds >= faultTimeSeconds);

deterministicRippleLpm = rippleAmplitudeLpm* ...
    sin(2*pi*rippleFrequencyHz*timeSeconds);
healthyFlowLpm = nominalGainLpmPerCommand*speedCommand;
faultFlowLossLpm = nominalGainLpmPerCommand* ...
    effectivenessLossFraction*faultActive.*speedCommand;
trueFlowLpm = healthyFlowLpm-faultFlowLossLpm;
measuredFlowLpm = trueFlowLpm+deterministicRippleLpm;
predictedFlowLpm = predictorGainLpmPerCommand*speedCommand;

modelMismatchResidualLpm = ...
    (nominalGainLpmPerCommand-predictorGainLpmPerCommand)*speedCommand;
faultResidualLpm = -faultFlowLossLpm;
residualLpm = measuredFlowLpm-predictedFlowLpm;
residualDecompositionErrorLpm = residualLpm- ...
    (modelMismatchResidualLpm+faultResidualLpm+deterministicRippleLpm);

% Equal three-cycle windows avoid command/fault transition samples and make
% the deterministic ripple mean independently auditable.
lowCommandHealthyWindow = timeSeconds >= 2 & timeSeconds < 8;
highCommandHealthyWindow = timeSeconds >= 12 & timeSeconds < 18;
postFaultWindow = timeSeconds >= 22 & timeSeconds < 28;
lowCommandHealthyMeanResidualLpm = ...
    mean(residualLpm(lowCommandHealthyWindow));
highCommandHealthyMeanResidualLpm = ...
    mean(residualLpm(highCommandHealthyWindow));
postFaultMeanResidualLpm = mean(residualLpm(postFaultWindow));
commandStepResidualChangeLpm = highCommandHealthyMeanResidualLpm- ...
    lowCommandHealthyMeanResidualLpm;
faultResidualChangeLpm = postFaultMeanResidualLpm- ...
    highCommandHealthyMeanResidualLpm;
healthyHighResidualRmsLpm = sqrt(mean( ...
    residualLpm(highCommandHealthyWindow).^2));
postFaultResidualRmsLpm = sqrt(mean(residualLpm(postFaultWindow).^2));

% Deliberately broken comparator: it freezes the initial expected flow and
% omits the known command transition. A normal command change then appears
% as a +3 L/min discrepancy even before the fault is injected.
brokenConstantPredictionLpm = predictorGainLpmPerCommand*lowCommand;
brokenPredictedFlowLpm = brokenConstantPredictionLpm* ...
    ones(size(timeSeconds));
brokenResidualLpm = measuredFlowLpm-brokenPredictedFlowLpm;
brokenLowCommandMeanResidualLpm = ...
    mean(brokenResidualLpm(lowCommandHealthyWindow));
brokenHighCommandMeanResidualLpm = ...
    mean(brokenResidualLpm(highCommandHealthyWindow));
brokenCommandStepResidualChangeLpm = ...
    brokenHighCommandMeanResidualLpm-brokenLowCommandMeanResidualLpm;

out = struct( ...
    'samplePeriodSeconds',samplePeriodSeconds, ...
    'sampleCount',numel(timeSeconds), ...
    'timeSeconds',timeSeconds, ...
    'commandStepTimeSeconds',commandStepTimeSeconds, ...
    'faultTimeSeconds',faultTimeSeconds, ...
    'lowCommand',lowCommand, ...
    'highCommand',highCommand, ...
    'speedCommand',speedCommand, ...
    'faultActive',faultActive, ...
    'nominalGainLpmPerCommand',nominalGainLpmPerCommand, ...
    'predictorGainLpmPerCommand',predictorGainLpmPerCommand, ...
    'effectivenessLossFraction',effectivenessLossFraction, ...
    'rippleAmplitudeLpm',rippleAmplitudeLpm, ...
    'rippleFrequencyHz',rippleFrequencyHz, ...
    'deterministicRippleLpm',deterministicRippleLpm, ...
    'healthyFlowLpm',healthyFlowLpm, ...
    'faultFlowLossLpm',faultFlowLossLpm, ...
    'trueFlowLpm',trueFlowLpm, ...
    'measuredFlowLpm',measuredFlowLpm, ...
    'predictedFlowLpm',predictedFlowLpm, ...
    'modelMismatchResidualLpm',modelMismatchResidualLpm, ...
    'faultResidualLpm',faultResidualLpm, ...
    'residualLpm',residualLpm, ...
    'residualDecompositionErrorLpm',residualDecompositionErrorLpm, ...
    'maxAbsResidualDecompositionErrorLpm', ...
        max(abs(residualDecompositionErrorLpm)), ...
    'lowCommandHealthyWindow',lowCommandHealthyWindow, ...
    'highCommandHealthyWindow',highCommandHealthyWindow, ...
    'postFaultWindow',postFaultWindow, ...
    'lowCommandHealthyMeanResidualLpm', ...
        lowCommandHealthyMeanResidualLpm, ...
    'highCommandHealthyMeanResidualLpm', ...
        highCommandHealthyMeanResidualLpm, ...
    'postFaultMeanResidualLpm',postFaultMeanResidualLpm, ...
    'commandStepResidualChangeLpm',commandStepResidualChangeLpm, ...
    'faultResidualChangeLpm',faultResidualChangeLpm, ...
    'healthyHighResidualRmsLpm',healthyHighResidualRmsLpm, ...
    'postFaultResidualRmsLpm',postFaultResidualRmsLpm, ...
    'expectedFaultSignatureLpm', ...
        -nominalGainLpmPerCommand*effectivenessLossFraction*highCommand, ...
    'expectedHealthyHighMismatchLpm', ...
        (nominalGainLpmPerCommand-predictorGainLpmPerCommand)*highCommand, ...
    'brokenConstantPredictionLpm',brokenConstantPredictionLpm, ...
    'brokenPredictedFlowLpm',brokenPredictedFlowLpm, ...
    'brokenResidualLpm',brokenResidualLpm, ...
    'brokenCommandStepResidualChangeLpm', ...
        brokenCommandStepResidualChangeLpm, ...
    'expectedBrokenCommandStepChangeLpm', ...
        nominalGainLpmPerCommand*(highCommand-lowCommand));

out.residualEquation = 'r(t) = y(t) - y_hat(t | u(t))';
out.residualUnit = 'L/min';
out.commandUnit = 'normalized speed command';
out.gainUnit = 'L/min per normalized command';
out.signConvention = [ ...
    'negative residual means measured flow is below the ' ...
    'command-conditioned prediction'];
out.inputAssumption = [ ...
    'the predictor receives the known speed command that drives flow'];
out.lossMeaning = [ ...
    'conditional flow-effectiveness loss after injection, not an ' ...
    'occurrence probability'];
out.scopeBoundary = [ ...
    'residual generation only; no alarm threshold, fault isolation, ' ...
    'Bayesian posterior, or recovery action'];
end
