function run_checks
%RUN_CHECKS Check P09 residual equations, sweeps, limits, and rejection.
baseline = model(0.20,10,0.10);
repeat = model(0.20,10,0.10);
assert(isequal(baseline,repeat), ...
    'Identical inputs must produce identical outputs.');

assert(isscalar(baseline) && baseline.sampleCount == 301 && ...
    baseline.samplePeriodSeconds == 0.1, ...
    'The model must return one fixed 301-sample deterministic record.');
signalNames = {'timeSeconds','speedCommand','faultActive', ...
    'deterministicRippleLpm','healthyFlowLpm','faultFlowLossLpm', ...
    'trueFlowLpm','measuredFlowLpm','predictedFlowLpm', ...
    'modelMismatchResidualLpm','faultResidualLpm','residualLpm', ...
    'residualDecompositionErrorLpm','brokenPredictedFlowLpm', ...
    'brokenResidualLpm'};
for k = 1:numel(signalNames)
    assert(isequal(size(baseline.(signalNames{k})),[301 1]), ...
        'Every signal output must remain a fixed 301x1 column.');
end
assert(abs(baseline.timeSeconds(1)) < 1e-15 && ...
    abs(baseline.timeSeconds(end)-30) < 1e-12 && ...
    max(abs(diff(baseline.timeSeconds)-0.1)) < 1e-12, ...
    'Time must span 0 through 30 seconds in fixed 0.1-second steps.');
assert(sum(baseline.lowCommandHealthyWindow) == 60 && ...
    sum(baseline.highCommandHealthyWindow) == 60 && ...
    sum(baseline.postFaultWindow) == 60, ...
    'Each reference window must contain exactly three ripple cycles.');
assert(all(baseline.speedCommand(baseline.timeSeconds < 10) == 0.5) && ...
    all(baseline.speedCommand(baseline.timeSeconds >= 10) == 0.8), ...
    'The known speed command must change from 0.5 to 0.8 at 10 seconds.');
assert(all(baseline.faultActive(baseline.timeSeconds < 20) == 0) && ...
    all(baseline.faultActive(baseline.timeSeconds >= 20) == 1), ...
    'Conditional effectiveness loss must activate at 20 seconds.');

assert(strcmp(baseline.residualEquation, ...
    'r(t) = y(t) - y_hat(t | u(t))') && ...
    strcmp(baseline.residualUnit,'L/min') && ...
    strcmp(baseline.gainUnit,'L/min per normalized command'), ...
    'Residual equation, sign convention, and units must remain explicit.');
assert(contains(baseline.signConvention,'negative residual') && ...
    contains(baseline.signConvention,'below') && ...
    contains(baseline.inputAssumption,'known speed command'), ...
    'Residual sign and known-input assumption must remain explicit.');
assert(contains(baseline.lossMeaning,'not an occurrence probability') && ...
    contains(baseline.scopeBoundary,'no alarm threshold') && ...
    contains(baseline.scopeBoundary,'fault isolation'), ...
    'Conditional magnitude and P09 decision boundaries must remain explicit.');

independentHealthyFlow = 10*baseline.speedCommand;
independentFaultLoss = 10*0.20*baseline.faultActive.* ...
    baseline.speedCommand;
independentTrueFlow = independentHealthyFlow-independentFaultLoss;
independentPrediction = 10*baseline.speedCommand;
independentResidual = baseline.measuredFlowLpm-independentPrediction;
assert(max(abs(baseline.healthyFlowLpm-independentHealthyFlow)) < 1e-14, ...
    'Healthy flow must equal nominal gain times known command.');
assert(max(abs(baseline.faultFlowLossLpm-independentFaultLoss)) < 1e-14 && ...
    max(abs(baseline.trueFlowLpm-independentTrueFlow)) < 1e-14, ...
    'Physical effectiveness loss must reduce only post-injection true flow.');
assert(max(abs(baseline.predictedFlowLpm-independentPrediction)) < 1e-14, ...
    'Nominal prediction must equal predictor gain times known command.');
assert(max(abs(baseline.residualLpm-independentResidual)) < 1e-14, ...
    'Diagnostic residual must independently equal measured minus predicted flow.');
independentDecomposition = baseline.modelMismatchResidualLpm + ...
    baseline.faultResidualLpm+baseline.deterministicRippleLpm;
assert(max(abs(baseline.residualLpm-independentDecomposition)) < 1e-12 && ...
    baseline.maxAbsResidualDecompositionErrorLpm < 1e-12, ...
    'Model mismatch, fault, and ripple components must close to the residual.');

assert(abs(mean(baseline.measuredFlowLpm( ...
    baseline.lowCommandHealthyWindow))-5) < 1e-12 && ...
    abs(mean(baseline.measuredFlowLpm( ...
    baseline.highCommandHealthyWindow))-8) < 1e-12 && ...
    abs(mean(baseline.measuredFlowLpm( ...
    baseline.postFaultWindow))-6.4) < 1e-12, ...
    'Reference-window measured flows must be 5, 8, and 6.4 L/min.');
assert(abs(baseline.lowCommandHealthyMeanResidualLpm) < 1e-12 && ...
    abs(baseline.highCommandHealthyMeanResidualLpm) < 1e-12, ...
    'Matched healthy residual means must remain zero at both commands.');
assert(abs(baseline.commandStepResidualChangeLpm) < 1e-12, ...
    'Known command conditioning must reject the normal command step.');
assert(abs(baseline.postFaultMeanResidualLpm+1.6) < 1e-12 && ...
    abs(baseline.faultResidualChangeLpm+1.6) < 1e-12 && ...
    abs(baseline.expectedFaultSignatureLpm+1.6) < 1e-15, ...
    'A 20 percent loss at command 0.8 must create a -1.6 L/min signature.');
assert(abs(baseline.healthyHighResidualRmsLpm-0.1/sqrt(2)) < 1e-12, ...
    'Healthy RMS must independently equal sinusoid amplitude over sqrt two.');
assert(abs(baseline.postFaultResidualRmsLpm- ...
    sqrt(1.6^2+0.1^2/2)) < 1e-12, ...
    'Post-fault RMS must combine the -1.6 mean and deterministic ripple.');

effectivenessLossSweep = [0 0.05 0.10 0.20 0.30];
actualLossPostMeans = zeros(size(effectivenessLossSweep));
actualLossShifts = zeros(size(effectivenessLossSweep));
actualLossHealthyMeans = zeros(size(effectivenessLossSweep));
for k = 1:numel(effectivenessLossSweep)
    changed = model(effectivenessLossSweep(k),10,0.10);
    actualLossPostMeans(k) = changed.postFaultMeanResidualLpm;
    actualLossShifts(k) = changed.faultResidualChangeLpm;
    actualLossHealthyMeans(k) = changed.highCommandHealthyMeanResidualLpm;
    assert(isequal(changed.speedCommand,baseline.speedCommand) && ...
        isequal(changed.predictedFlowLpm,baseline.predictedFlowLpm), ...
        'Loss sweep must leave command and nominal prediction fixed.');
    assert(isequal(changed.measuredFlowLpm(changed.timeSeconds < 20), ...
        baseline.measuredFlowLpm(baseline.timeSeconds < 20)), ...
        'Loss sweep must leave every pre-fault measurement fixed.');
    assert(isequal(changed.deterministicRippleLpm, ...
        baseline.deterministicRippleLpm), ...
        'Loss sweep must leave deterministic ripple fixed.');
    expectedFaultComponentLpm = -10*effectivenessLossSweep(k)* ...
        baseline.faultActive.*baseline.speedCommand;
    expectedLossResidualLpm = expectedFaultComponentLpm+ ...
        baseline.deterministicRippleLpm;
    assert(max(abs(changed.modelMismatchResidualLpm)) < 1e-14 && ...
        max(abs(changed.faultResidualLpm- ...
        expectedFaultComponentLpm)) < 1e-12 && ...
        max(abs(changed.residualLpm-expectedLossResidualLpm)) < 1e-12 && ...
        changed.maxAbsResidualDecompositionErrorLpm < 1e-12, ...
        ['Every loss-sweep point must retain the pointwise residual ' ...
        'decomposition.']);
end
expectedLossMeans = [0 -0.4 -0.8 -1.6 -2.4];
assert(max(abs(actualLossPostMeans-expectedLossMeans)) < 1e-12 && ...
    max(abs(actualLossShifts-expectedLossMeans)) < 1e-12, ...
    'Effectiveness-loss sweep must match independent -8L references.');
assert(max(abs(actualLossHealthyMeans)) < 1e-12, ...
    'Effectiveness-loss sweep must not create a pre-fault mean.');

predictorGainSweepLpmPerCommand = [8 9 10 11 12];
actualGainHealthyMeans = zeros(size(predictorGainSweepLpmPerCommand));
actualGainPostMeans = zeros(size(predictorGainSweepLpmPerCommand));
actualGainShifts = zeros(size(predictorGainSweepLpmPerCommand));
actualGainCommandChanges = zeros(size(predictorGainSweepLpmPerCommand));
for k = 1:numel(predictorGainSweepLpmPerCommand)
    changed = model(0.20,predictorGainSweepLpmPerCommand(k),0.10);
    actualGainHealthyMeans(k) = changed.highCommandHealthyMeanResidualLpm;
    actualGainPostMeans(k) = changed.postFaultMeanResidualLpm;
    actualGainShifts(k) = changed.faultResidualChangeLpm;
    actualGainCommandChanges(k) = changed.commandStepResidualChangeLpm;
    assert(isequal(changed.trueFlowLpm,baseline.trueFlowLpm) && ...
        isequal(changed.measuredFlowLpm,baseline.measuredFlowLpm), ...
        'Predictor-gain sweep must leave physical true and measured flow fixed.');
    assert(isequal(changed.faultResidualLpm,baseline.faultResidualLpm) && ...
        isequal(changed.deterministicRippleLpm, ...
        baseline.deterministicRippleLpm), ...
        'Predictor-gain sweep must leave physical fault and ripple fixed.');
    expectedPredictionLpm = predictorGainSweepLpmPerCommand(k)* ...
        baseline.speedCommand;
    expectedMismatchComponentLpm = ...
        (10-predictorGainSweepLpmPerCommand(k))*baseline.speedCommand;
    expectedGainResidualLpm = expectedMismatchComponentLpm+ ...
        baseline.faultResidualLpm+baseline.deterministicRippleLpm;
    assert(max(abs(changed.predictedFlowLpm-expectedPredictionLpm)) < 1e-12 && ...
        max(abs(changed.modelMismatchResidualLpm- ...
        expectedMismatchComponentLpm)) < 1e-12 && ...
        max(abs(changed.residualLpm-expectedGainResidualLpm)) < 1e-12 && ...
        changed.maxAbsResidualDecompositionErrorLpm < 1e-12, ...
        ['Every predictor-gain sweep point must retain the pointwise ' ...
        'residual decomposition.']);
end
assert(max(abs(actualGainHealthyMeans-[1.6 0.8 0 -0.8 -1.6])) < 1e-12, ...
    'Predictor-gain sweep healthy means must match mismatch references.');
assert(max(abs(actualGainPostMeans-[0 -0.8 -1.6 -2.4 -3.2])) < 1e-12, ...
    'Predictor-gain sweep post-fault means must match independent references.');
assert(max(abs(actualGainShifts+1.6)) < 1e-12, ...
    'Predictor-gain sweep must preserve the -1.6 L/min fault-induced shift.');
assert(max(abs(actualGainCommandChanges-[0.6 0.3 0 -0.3 -0.6])) < 1e-12, ...
    'Predictor mismatch must expose command-dependent healthy residual change.');

healthy = model(0,10,0.10);
assert(abs(healthy.commandStepResidualChangeLpm) < 1e-12 && ...
    abs(healthy.brokenCommandStepResidualChangeLpm-3) < 1e-12, ...
    'Broken constant prediction must turn the normal command into +3 L/min.');
assert(all(healthy.brokenPredictedFlowLpm == 5) && ...
    max(abs(healthy.residualLpm-healthy.deterministicRippleLpm)) < 1e-14, ...
    'Healthy correct residual must retain only ripple while broken prediction freezes at 5.');
assert(max(abs(healthy.brokenResidualLpm- ...
    (healthy.measuredFlowLpm-5))) < 1e-14, ...
    'Broken residual must retain its recognizable omitted-command symptom.');

zeroResidual = model(0,10,0);
assert(all(zeroResidual.residualLpm == 0) && ...
    zeroResidual.healthyHighResidualRmsLpm == 0 && ...
    zeroResidual.postFaultResidualRmsLpm == 0, ...
    'Zero loss, matched gain, and zero ripple must give exact zero residual.');
fullLoss = model(1,10,0);
assert(all(fullLoss.measuredFlowLpm(fullLoss.postFaultWindow) == 0) && ...
    all(fullLoss.residualLpm(fullLoss.postFaultWindow) == -8) && ...
    fullLoss.postFaultMeanResidualLpm == -8, ...
    'Full effectiveness loss must give zero measured flow and -8 L/min residual.');
canceledFault = model(0.20,8,0);
assert(abs(canceledFault.highCommandHealthyMeanResidualLpm-1.6) < 1e-15 && ...
    abs(canceledFault.postFaultMeanResidualLpm) < 1e-15 && ...
    abs(canceledFault.faultResidualChangeLpm+1.6) < 1e-15 && ...
    max(abs(canceledFault.measuredFlowLpm( ...
    canceledFault.postFaultWindow)-6.4)) < 1e-14, ...
    'Predictor mismatch cancellation must not be mistaken for physical health.');
zeroPredictor = model(0,0,0);
assert(isequal(zeroPredictor.residualLpm,zeroPredictor.healthyFlowLpm) && ...
    zeroPredictor.commandStepResidualChangeLpm == 3, ...
    'Zero predictor gain must expose the full known-input flow as residual.');
maximumSupported = model(1,20,1);
numericOutputs = [maximumSupported.trueFlowLpm; ...
    maximumSupported.measuredFlowLpm;maximumSupported.predictedFlowLpm; ...
    maximumSupported.residualLpm;maximumSupported.brokenResidualLpm];
assert(all(isfinite(numericOutputs)) && numel(numericOutputs) == 1505, ...
    'Maximum bounded inputs must keep every fixed resource output finite.');
tinyRipple = model(0,10,eps(5));
assert(max(abs(tinyRipple.deterministicRippleLpm)) > 0 && ...
    max(abs(tinyRipple.residualLpm)) > 0, ...
    'A representable tiny ripple must not be silently discarded.');

assertRejects(@() model([0.10 0.20],10,0.10), ...
    'A nonscalar loss input must be rejected.');
assertRejects(@() model(-0.01,10,0.10), ...
    'A negative effectiveness loss must be rejected.');
assertRejects(@() model(1.01,10,0.10), ...
    'An effectiveness loss above one must be rejected.');
assertRejects(@() model(NaN,10,0.10), ...
    'A nonfinite effectiveness loss must be rejected.');
assertRejects(@() model(Inf,10,0.10), ...
    'An infinite effectiveness loss must be rejected.');
assertRejects(@() model(0.20i,10,0.10), ...
    'A complex effectiveness loss must be rejected.');
assertRejects(@() model(0.20,[9 10],0.10), ...
    'A nonscalar predictor gain must be rejected.');
assertRejects(@() model(0.20,-0.1,0.10), ...
    'A negative predictor gain must be rejected.');
assertRejects(@() model(0.20,20.1,0.10), ...
    'A predictor gain above the resource bound must be rejected.');
assertRejects(@() model(0.20,NaN,0.10), ...
    'A nonfinite predictor gain must be rejected.');
assertRejects(@() model(0.20,Inf,0.10), ...
    'An infinite predictor gain must be rejected.');
assertRejects(@() model(0.20,10i,0.10), ...
    'A complex predictor gain must be rejected.');
assertRejects(@() model(0.20,10,[0.05 0.10]), ...
    'A nonscalar ripple amplitude must be rejected.');
assertRejects(@() model(0.20,10,-0.01), ...
    'A negative ripple amplitude must be rejected.');
assertRejects(@() model(0.20,10,1.01), ...
    'A ripple amplitude above the resource bound must be rejected.');
assertRejects(@() model(0.20,10,NaN), ...
    'A nonfinite ripple amplitude must be rejected.');
assertRejects(@() model(0.20,10,Inf), ...
    'An infinite ripple amplitude must be rejected.');
assertRejects(@() model(0.20,10,0.10i), ...
    'A complex ripple amplitude must be rejected.');

recovered = model(0.20,10,0.10);
assert(isequal(recovered,baseline), ...
    'Rejected malformed calls must not contaminate exact recovery.');

disp(['P09 checks passed. Explain how known command and measured flow ' ...
    'generate a signed residual, how loss and predictor mismatch differ, ' ...
    'and why discrepancy alone is not an alarm or unique diagnosis.']);
end

function assertRejects(operation,message)
didReject = false;
try
    operation();
catch
    didReject = true;
end
assert(didReject,message);
end
