function out = model(thresholdMagnitudeLpm,effectivenessLossFraction, ...
    rippleAmplitudeLpm)
%MODEL Apply a signed fault threshold to a deterministic Pump-A residual.
%   P09 established r(t)=y(t)-y_hat(t|u), so a Pump-A effectiveness loss
%   produces a negative residual. P10 places the signed boundary at -T,
%   where T is a nonnegative threshold magnitude, and raises an alarm when
%   r(t) <= -T. Reference-window alarm fractions describe only this fixed
%   synthetic record; they are not field probabilities or rates.
arguments
    thresholdMagnitudeLpm (1,1) double = 0.50
    effectivenessLossFraction (1,1) double = 0.20
    rippleAmplitudeLpm (1,1) double = 0.10
end

validateattributes(thresholdMagnitudeLpm,{'double'}, ...
    {'real','finite','>=',0,'<=',10},mfilename, ...
    'thresholdMagnitudeLpm');
validateattributes(effectivenessLossFraction,{'double'}, ...
    {'real','finite','>=',0,'<=',1},mfilename, ...
    'effectivenessLossFraction');
validateattributes(rippleAmplitudeLpm,{'double'}, ...
    {'real','finite','>=',0,'<=',1},mfilename, ...
    'rippleAmplitudeLpm');

samplePeriodSeconds = 0.1;
timeSeconds = (0:samplePeriodSeconds:30).';
commandStepTimeSeconds = 10;
faultTimeSeconds = 20;
lowCommand = 0.5;
highCommand = 0.8;
nominalGainLpmPerCommand = 10;
rippleFrequencyHz = 0.5;

speedCommand = lowCommand*ones(size(timeSeconds));
speedCommand(timeSeconds >= commandStepTimeSeconds) = highCommand;
faultActive = double(timeSeconds >= faultTimeSeconds);
deterministicRippleLpm = rippleAmplitudeLpm* ...
    sin(2*pi*rippleFrequencyHz*timeSeconds);
faultResidualLpm = -nominalGainLpmPerCommand* ...
    effectivenessLossFraction*faultActive.*speedCommand;
residualLpm = faultResidualLpm+deterministicRippleLpm;

signedThresholdLpm = -thresholdMagnitudeLpm*ones(size(timeSeconds));
decisionStatisticLpm = -residualLpm;
alarm = residualLpm <= signedThresholdLpm;
alarmMarginLpm = decisionStatisticLpm-thresholdMagnitudeLpm;

% Compare equal three-cycle, high-command windows before and after the
% injection. This makes the deterministic ripple average independently
% auditable and avoids either transition sample.
healthyReferenceWindow = timeSeconds >= 12 & timeSeconds < 18;
faultReferenceWindow = timeSeconds >= 22 & timeSeconds < 28;
healthyReferenceCount = sum(healthyReferenceWindow);
faultReferenceCount = sum(faultReferenceWindow);
falseAlarmCount = sum(alarm & healthyReferenceWindow);
detectionCount = sum(alarm & faultReferenceWindow);
trueNegativeCount = healthyReferenceCount-falseAlarmCount;
missedDetectionCount = faultReferenceCount-detectionCount;
falseAlarmSampleFraction = falseAlarmCount/healthyReferenceCount;
detectionSampleFraction = detectionCount/faultReferenceCount;
missedDetectionSampleFraction = ...
    missedDetectionCount/faultReferenceCount;

healthyMeanResidualLpm = mean(residualLpm(healthyReferenceWindow));
postFaultMeanResidualLpm = mean(residualLpm(faultReferenceWindow));
healthyMinimumResidualLpm = min(residualLpm(healthyReferenceWindow));
healthyMaximumResidualLpm = max(residualLpm(healthyReferenceWindow));
postFaultMinimumResidualLpm = min(residualLpm(faultReferenceWindow));
postFaultMaximumResidualLpm = max(residualLpm(faultReferenceWindow));

% Deliberately broken comparator: it forgets that P09's loss signature is
% negative and places the boundary at +T while keeping the <= direction.
% With the baseline T=0.5 L/min, every healthy reference sample alarms.
brokenSignedThresholdLpm = thresholdMagnitudeLpm*ones(size(timeSeconds));
brokenWrongSignAlarm = residualLpm <= brokenSignedThresholdLpm;
brokenFalseAlarmCount = sum( ...
    brokenWrongSignAlarm & healthyReferenceWindow);
brokenFalseAlarmSampleFraction = ...
    brokenFalseAlarmCount/healthyReferenceCount;

out = struct( ...
    'samplePeriodSeconds',samplePeriodSeconds, ...
    'sampleCount',numel(timeSeconds), ...
    'timeSeconds',timeSeconds, ...
    'commandStepTimeSeconds',commandStepTimeSeconds, ...
    'faultTimeSeconds',faultTimeSeconds, ...
    'lowCommand',lowCommand, ...
    'highCommand',highCommand, ...
    'speedCommand',speedCommand, ...
    'faultActive',faultActive, ...
    'nominalGainLpmPerCommand',nominalGainLpmPerCommand, ...
    'thresholdMagnitudeLpm',thresholdMagnitudeLpm, ...
    'effectivenessLossFraction',effectivenessLossFraction, ...
    'rippleAmplitudeLpm',rippleAmplitudeLpm, ...
    'rippleFrequencyHz',rippleFrequencyHz, ...
    'deterministicRippleLpm',deterministicRippleLpm, ...
    'faultResidualLpm',faultResidualLpm, ...
    'residualLpm',residualLpm, ...
    'signedThresholdLpm',signedThresholdLpm, ...
    'decisionStatisticLpm',decisionStatisticLpm, ...
    'alarmMarginLpm',alarmMarginLpm, ...
    'alarm',alarm, ...
    'healthyReferenceWindow',healthyReferenceWindow, ...
    'faultReferenceWindow',faultReferenceWindow, ...
    'healthyReferenceCount',healthyReferenceCount, ...
    'faultReferenceCount',faultReferenceCount, ...
    'trueNegativeCount',trueNegativeCount, ...
    'falseAlarmCount',falseAlarmCount, ...
    'detectionCount',detectionCount, ...
    'missedDetectionCount',missedDetectionCount, ...
    'falseAlarmSampleFraction',falseAlarmSampleFraction, ...
    'detectionSampleFraction',detectionSampleFraction, ...
    'missedDetectionSampleFraction',missedDetectionSampleFraction, ...
    'healthyMeanResidualLpm',healthyMeanResidualLpm, ...
    'postFaultMeanResidualLpm',postFaultMeanResidualLpm, ...
    'healthyMinimumResidualLpm',healthyMinimumResidualLpm, ...
    'healthyMaximumResidualLpm',healthyMaximumResidualLpm, ...
    'postFaultMinimumResidualLpm',postFaultMinimumResidualLpm, ...
    'postFaultMaximumResidualLpm',postFaultMaximumResidualLpm, ...
    'expectedPostFaultMeanResidualLpm', ...
        -nominalGainLpmPerCommand*effectivenessLossFraction*highCommand, ...
    'brokenSignedThresholdLpm',brokenSignedThresholdLpm, ...
    'brokenWrongSignAlarm',brokenWrongSignAlarm, ...
    'brokenFalseAlarmCount',brokenFalseAlarmCount, ...
    'brokenFalseAlarmSampleFraction', ...
        brokenFalseAlarmSampleFraction);

out.residualEquation = 'r(t) = y(t) - y_hat(t | u(t))';
out.decisionEquation = 'alarm when r(t) <= -T, for T >= 0';
out.residualUnit = 'L/min';
out.thresholdUnit = 'L/min';
out.signConvention = [ ...
    'negative residual means measured flow is below the ' ...
    'command-conditioned prediction'];
out.lossMeaning = [ ...
    'conditional flow-effectiveness loss after injection, not an ' ...
    'occurrence probability'];
out.fractionMeaning = [ ...
    'fractions count alarmed samples in fixed deterministic reference ' ...
    'windows; they are not field probabilities or rates'];
out.scopeBoundary = [ ...
    'threshold detection only; no unique fault isolation, Bayesian ' ...
    'posterior, recovery action, or mission-level decision'];
out.brokenAssumption = [ ...
    'the signed boundary must respect P09''s negative loss-residual ' ...
    'convention'];
end
