function run_checks
%RUN_CHECKS Check P10 threshold equations, sweeps, limits, and rejection.
baseline = model(0.50,0.20,0.10);
repeat = model(0.50,0.20,0.10);
assert(isequal(baseline,repeat), ...
    'Identical inputs must produce identical outputs.');

assert(isscalar(baseline) && baseline.sampleCount == 301 && ...
    baseline.samplePeriodSeconds == 0.1, ...
    'The model must return one fixed 301-sample deterministic record.');
signalNames = {'timeSeconds','speedCommand','faultActive', ...
    'deterministicRippleLpm','faultResidualLpm','residualLpm', ...
    'signedThresholdLpm','decisionStatisticLpm','alarmMarginLpm', ...
    'alarm','healthyReferenceWindow','faultReferenceWindow', ...
    'brokenSignedThresholdLpm','brokenWrongSignAlarm'};
for k = 1:numel(signalNames)
    assert(isequal(size(baseline.(signalNames{k})),[301 1]), ...
        'Every signal output must remain a fixed 301x1 column.');
end
assert(abs(baseline.timeSeconds(1)) < 1e-15 && ...
    abs(baseline.timeSeconds(end)-30) < 1e-12 && ...
    max(abs(diff(baseline.timeSeconds)-0.1)) < 1e-12, ...
    'Time must span 0 through 30 seconds in fixed 0.1-second steps.');
assert(all(baseline.speedCommand(baseline.timeSeconds < 10) == 0.5) && ...
    all(baseline.speedCommand(baseline.timeSeconds >= 10) == 0.8), ...
    'The known speed command must change from 0.5 to 0.8 at 10 seconds.');
assert(all(baseline.faultActive(baseline.timeSeconds < 20) == 0) && ...
    all(baseline.faultActive(baseline.timeSeconds >= 20) == 1), ...
    'Conditional effectiveness loss must activate at 20 seconds.');
assert(baseline.healthyReferenceCount == 60 && ...
    baseline.faultReferenceCount == 60, ...
    'Each reference window must contain exactly three ripple cycles.');

assert(strcmp(baseline.residualEquation, ...
    'r(t) = y(t) - y_hat(t | u(t))') && ...
    strcmp(baseline.decisionEquation, ...
    'alarm when r(t) <= -T, for T >= 0') && ...
    strcmp(baseline.residualUnit,'L/min') && ...
    strcmp(baseline.thresholdUnit,'L/min'), ...
    'Residual equation, decision equation, sign convention, and units must remain explicit.');
assert(contains(baseline.signConvention,'negative residual') && ...
    contains(baseline.signConvention,'below') && ...
    contains(baseline.lossMeaning,'not an occurrence probability'), ...
    'P09 sign and conditional-magnitude meanings must remain explicit.');
assert(contains(baseline.fractionMeaning,'not field probabilities') && ...
    contains(baseline.scopeBoundary,'no unique fault isolation') && ...
    contains(baseline.scopeBoundary,'Bayesian posterior'), ...
    'Deterministic fractions and the P10 scope boundary must remain explicit.');

independentRippleLpm = 0.10*sin(2*pi*0.5*baseline.timeSeconds);
independentFaultResidualLpm = -10*0.20*baseline.faultActive.* ...
    baseline.speedCommand;
independentResidualLpm = independentFaultResidualLpm+ ...
    independentRippleLpm;
independentSignedThresholdLpm = -0.50*ones(size(baseline.timeSeconds));
independentAlarm = independentResidualLpm <= ...
    independentSignedThresholdLpm;
assert(max(abs(baseline.deterministicRippleLpm- ...
    independentRippleLpm)) < 1e-14, ...
    'Deterministic ripple must match the independent sinusoidal reference.');
assert(max(abs(baseline.faultResidualLpm- ...
    independentFaultResidualLpm)) < 1e-14 && ...
    max(abs(baseline.residualLpm-independentResidualLpm)) < 1e-14, ...
    'Residual must independently equal fault signature plus ripple.');
assert(isequal(baseline.signedThresholdLpm, ...
    independentSignedThresholdLpm) && ...
    isequal(baseline.alarm,independentAlarm) && ...
    max(abs(baseline.decisionStatisticLpm+baseline.residualLpm)) < 1e-14 && ...
    max(abs(baseline.alarmMarginLpm- ...
    (baseline.decisionStatisticLpm-0.50))) < 1e-14, ...
    'Alarm must pointwise implement the inclusive signed threshold equation.');

assert(abs(baseline.healthyMeanResidualLpm) < 1e-12 && ...
    abs(baseline.postFaultMeanResidualLpm+1.6) < 1e-12 && ...
    abs(baseline.expectedPostFaultMeanResidualLpm+1.6) < 1e-15, ...
    'Healthy and baseline fault means must be 0 and -1.6 L/min.');
assert(abs(baseline.healthyMinimumResidualLpm+0.1) < 1e-12 && ...
    abs(baseline.healthyMaximumResidualLpm-0.1) < 1e-12 && ...
    abs(baseline.postFaultMinimumResidualLpm+1.7) < 1e-12 && ...
    abs(baseline.postFaultMaximumResidualLpm+1.5) < 1e-12, ...
    'Reference-window ranges must be [-0.1,0.1] and [-1.7,-1.5] L/min.');
assert(baseline.trueNegativeCount == 60 && ...
    baseline.falseAlarmCount == 0 && ...
    baseline.detectionCount == 60 && ...
    baseline.missedDetectionCount == 0, ...
    'Baseline confusion counts must be TN/FP/detected/missed = 60/0/60/0.');
assert(baseline.trueNegativeCount+baseline.falseAlarmCount == 60 && ...
    baseline.detectionCount+baseline.missedDetectionCount == 60 && ...
    baseline.falseAlarmSampleFraction == 0 && ...
    baseline.detectionSampleFraction == 1 && ...
    baseline.missedDetectionSampleFraction == 0, ...
    'Confusion counts and deterministic sample fractions must close exactly.');

thresholdSweepLpm = [0.06 0.12 0.50 1.49 1.56 1.72];
actualFalseAlarmFractions = zeros(size(thresholdSweepLpm));
actualDetectionFractions = zeros(size(thresholdSweepLpm));
previousAlarm = true(size(baseline.alarm));
for k = 1:numel(thresholdSweepLpm)
    changed = model(thresholdSweepLpm(k),0.20,0.10);
    actualFalseAlarmFractions(k) = changed.falseAlarmSampleFraction;
    actualDetectionFractions(k) = changed.detectionSampleFraction;
    assert(isequal(changed.residualLpm,baseline.residualLpm) && ...
        isequal(changed.faultResidualLpm,baseline.faultResidualLpm) && ...
        isequal(changed.deterministicRippleLpm, ...
        baseline.deterministicRippleLpm), ...
        'Threshold sweep must leave every residual component fixed.');
    expectedBoundaryLpm = -thresholdSweepLpm(k)* ...
        ones(size(baseline.timeSeconds));
    expectedAlarm = baseline.residualLpm <= expectedBoundaryLpm;
    assert(isequal(changed.signedThresholdLpm,expectedBoundaryLpm) && ...
        isequal(changed.alarm,expectedAlarm), ...
        'Every threshold-sweep point must retain the pointwise comparator.');
    assert(all(~changed.alarm | previousAlarm), ...
        'Raising the threshold must make each alarm set a subset of the previous set.');
    previousAlarm = changed.alarm;
end
assert(max(abs(actualFalseAlarmFractions- ...
    [0.25 0 0 0 0 0])) < 1e-12, ...
    'Threshold sweep healthy false-alarm fractions must match independent references.');
assert(max(abs(actualDetectionFractions- ...
    [1 1 1 1 0.65 0])) < 1e-12, ...
    'Threshold sweep fault detection fractions must match independent references.');

lossSweep = [0 0.04 0.06 0.08 0.20];
actualLossFalseAlarmFractions = zeros(size(lossSweep));
actualLossDetectionFractions = zeros(size(lossSweep));
actualLossPostMeansLpm = zeros(size(lossSweep));
previousFaultAlarm = false(sum(baseline.faultReferenceWindow),1);
for k = 1:numel(lossSweep)
    changed = model(0.50,lossSweep(k),0.10);
    actualLossFalseAlarmFractions(k) = changed.falseAlarmSampleFraction;
    actualLossDetectionFractions(k) = changed.detectionSampleFraction;
    actualLossPostMeansLpm(k) = changed.postFaultMeanResidualLpm;
    assert(isequal(changed.signedThresholdLpm, ...
        baseline.signedThresholdLpm) && ...
        isequal(changed.deterministicRippleLpm, ...
        baseline.deterministicRippleLpm), ...
        'Loss sweep must leave threshold and ripple fixed.');
    assert(isequal(changed.residualLpm(changed.timeSeconds < 20), ...
        baseline.residualLpm(baseline.timeSeconds < 20)) && ...
        isequal(changed.alarm(changed.timeSeconds < 20), ...
        baseline.alarm(baseline.timeSeconds < 20)), ...
        'Loss sweep must leave every pre-fault residual and alarm fixed.');
    expectedFaultComponentLpm = -10*lossSweep(k)* ...
        baseline.faultActive.*baseline.speedCommand;
    expectedLossResidualLpm = expectedFaultComponentLpm+ ...
        baseline.deterministicRippleLpm;
    expectedLossAlarm = expectedLossResidualLpm <= ...
        baseline.signedThresholdLpm;
    assert(max(abs(changed.faultResidualLpm- ...
        expectedFaultComponentLpm)) < 1e-12 && ...
        max(abs(changed.residualLpm-expectedLossResidualLpm)) < 1e-12 && ...
        isequal(changed.alarm,expectedLossAlarm), ...
        'Every loss-sweep point must retain residual and comparator attribution.');
    currentFaultAlarm = changed.alarm(changed.faultReferenceWindow);
    assert(all(~previousFaultAlarm | currentFaultAlarm), ...
        'Increasing loss must not remove an existing fault-window alarm.');
    previousFaultAlarm = currentFaultAlarm;
end
assert(max(abs(actualLossFalseAlarmFractions)) < 1e-12, ...
    'Loss sweep must not change the healthy false-alarm fraction.');
assert(max(abs(actualLossDetectionFractions-[0 0 0.45 1 1])) < 1e-12, ...
    'Loss sweep detection fractions must match independent references.');
assert(max(abs(actualLossPostMeansLpm- ...
    [0 -0.32 -0.48 -0.64 -1.6])) < 1e-12, ...
    'Loss sweep post-fault means must match independent -8L references.');

% The interactive exposes ripple amplitude as a third learner-facing
% control. At a fixed positive threshold, increasing this deterministic
% nuisance must leave the command, fault signature, and boundary fixed
% while growing only the healthy-window alarm set for these chosen values.
rippleSweepLpm = [0 0.40 0.60 0.70 1.00];
actualRippleFalseAlarmCounts = zeros(size(rippleSweepLpm));
actualRippleDetectionCounts = zeros(size(rippleSweepLpm));
actualRippleFalseAlarmFractions = zeros(size(rippleSweepLpm));
actualRippleDetectionFractions = zeros(size(rippleSweepLpm));
rippleReference = model(0.55,0.20,0);
previousHealthyAlarm = false(rippleReference.healthyReferenceCount,1);
for k = 1:numel(rippleSweepLpm)
    changed = model(0.55,0.20,rippleSweepLpm(k));
    expectedRippleLpm = rippleSweepLpm(k)* ...
        sin(2*pi*0.5*baseline.timeSeconds);
    expectedFaultComponentLpm = -10*0.20*baseline.faultActive.* ...
        baseline.speedCommand;
    expectedResidualLpm = expectedFaultComponentLpm+expectedRippleLpm;
    expectedBoundaryLpm = -0.55*ones(size(baseline.timeSeconds));
    expectedAlarm = expectedResidualLpm <= expectedBoundaryLpm;
    expectedFalseAlarmCount = sum( ...
        expectedAlarm & baseline.healthyReferenceWindow);
    expectedDetectionCount = sum( ...
        expectedAlarm & baseline.faultReferenceWindow);
    assert(isequal(changed.speedCommand,baseline.speedCommand) && ...
        isequal(changed.faultActive,baseline.faultActive) && ...
        isequal(changed.faultResidualLpm,expectedFaultComponentLpm) && ...
        isequal(changed.signedThresholdLpm, ...
        rippleReference.signedThresholdLpm), ...
        ['Ripple-control sweep must leave command, fault signature, ' ...
        'and threshold fixed.']);
    assert(max(abs(changed.deterministicRippleLpm- ...
        expectedRippleLpm)) < 1e-14 && ...
        max(abs(changed.residualLpm-expectedResidualLpm)) < 1e-14 && ...
        isequal(changed.alarm,expectedAlarm), ...
        ['Ripple-control sweep must preserve the pointwise nuisance, ' ...
        'residual, and comparator equations.']);
    assert(changed.falseAlarmCount == expectedFalseAlarmCount && ...
        changed.trueNegativeCount == ...
        changed.healthyReferenceCount-expectedFalseAlarmCount && ...
        changed.detectionCount == expectedDetectionCount && ...
        changed.missedDetectionCount == ...
        changed.faultReferenceCount-expectedDetectionCount && ...
        abs(changed.falseAlarmSampleFraction- ...
        expectedFalseAlarmCount/changed.healthyReferenceCount) < 1e-14 && ...
        abs(changed.detectionSampleFraction- ...
        expectedDetectionCount/changed.faultReferenceCount) < 1e-14 && ...
        abs(changed.missedDetectionSampleFraction- ...
        (changed.faultReferenceCount-expectedDetectionCount)/ ...
        changed.faultReferenceCount) < 1e-14, ...
        ['Ripple-control counts and fractions must close against the ' ...
        'pointwise alarm vector.']);
    currentHealthyAlarm = changed.alarm(changed.healthyReferenceWindow);
    assert(all(~previousHealthyAlarm | currentHealthyAlarm), ...
        ['Increasing ripple amplitude must not remove an existing ' ...
        'healthy-window alarm at fixed positive T.']);
    previousHealthyAlarm = currentHealthyAlarm;
    actualRippleFalseAlarmCounts(k) = changed.falseAlarmCount;
    actualRippleDetectionCounts(k) = changed.detectionCount;
    actualRippleFalseAlarmFractions(k) = ...
        changed.falseAlarmSampleFraction;
    actualRippleDetectionFractions(k) = changed.detectionSampleFraction;
end
assert(isequal(actualRippleFalseAlarmCounts,[0 0 9 15 21]) && ...
    isequal(actualRippleDetectionCounts,60*ones(size(rippleSweepLpm))), ...
    'Ripple-control alarm counts must match independent references.');
assert(max(abs(actualRippleFalseAlarmFractions- ...
    [0 0 0.15 0.25 0.35])) < 1e-12 && ...
    max(abs(actualRippleDetectionFractions-1)) < 1e-12, ...
    'Ripple-control sample fractions must match independent references.');

assert(isequal(baseline.brokenWrongSignAlarm, ...
    baseline.residualLpm <= baseline.brokenSignedThresholdLpm) && ...
    all(baseline.brokenSignedThresholdLpm == 0.50), ...
    'Broken comparator must transparently place the boundary at positive T.');
assert(baseline.brokenFalseAlarmCount == 60 && ...
    baseline.brokenFalseAlarmSampleFraction == 1 && ...
    contains(baseline.brokenAssumption,'negative loss-residual'), ...
    'Wrong-sign threshold must have the recognizable all-healthy-alarm symptom.');

zeroLoss = model(0.50,0,0.10);
assert(zeroLoss.detectionCount == 0 && ...
    zeroLoss.missedDetectionCount == 60 && ...
    zeroLoss.detectionSampleFraction == 0, ...
    'Zero loss must give no fault-window threshold detections at baseline T.');
inclusiveBoundary = model(1.60,0.20,0);
assert(all(inclusiveBoundary.residualLpm( ...
    inclusiveBoundary.faultReferenceWindow) == -1.60) && ...
    inclusiveBoundary.detectionCount == 60, ...
    'Samples exactly on the inclusive signed boundary must alarm.');
fullLoss = model(0.50,1,0);
assert(all(fullLoss.residualLpm(fullLoss.faultReferenceWindow) == -8) && ...
    fullLoss.detectionCount == 60 && ...
    fullLoss.detectionSampleFraction == 1, ...
    'Full effectiveness loss must give -8 L/min and alarm every fault sample.');
zeroThreshold = model(0,0,0);
assert(zeroThreshold.falseAlarmSampleFraction == 1 && ...
    zeroThreshold.detectionSampleFraction == 1, ...
    'At zero residual and zero threshold, inclusive equality must alarm.');
maximumSupported = model(10,1,1);
numericOutputs = [maximumSupported.residualLpm; ...
    maximumSupported.signedThresholdLpm; ...
    maximumSupported.decisionStatisticLpm; ...
    maximumSupported.alarmMarginLpm; ...
    maximumSupported.brokenSignedThresholdLpm];
assert(all(isfinite(numericOutputs)) && numel(numericOutputs) == 1505 && ...
    maximumSupported.detectionSampleFraction == 0, ...
    'Maximum bounded inputs must keep fixed outputs finite and permit a high-threshold miss.');
tinyRipple = model(0.50,0.20,eps(5));
assert(max(abs(tinyRipple.deterministicRippleLpm)) > 0, ...
    'A representable tiny ripple must not be silently discarded from its component output.');

assertRejects(@() model([0.4 0.5],0.20,0.10), ...
    'A nonscalar threshold must be rejected.');
assertRejects(@() model(-0.01,0.20,0.10), ...
    'A negative threshold must be rejected.');
assertRejects(@() model(10.01,0.20,0.10), ...
    'A threshold above the resource bound must be rejected.');
assertRejects(@() model(NaN,0.20,0.10), ...
    'A nonfinite threshold must be rejected.');
assertRejects(@() model(Inf,0.20,0.10), ...
    'An infinite threshold must be rejected.');
assertRejects(@() model(0.50i,0.20,0.10), ...
    'A complex threshold must be rejected.');
assertRejects(@() model(0.50,[0.10 0.20],0.10), ...
    'A nonscalar effectiveness loss must be rejected.');
assertRejects(@() model(0.50,-0.01,0.10), ...
    'A negative effectiveness loss must be rejected.');
assertRejects(@() model(0.50,1.01,0.10), ...
    'An effectiveness loss above one must be rejected.');
assertRejects(@() model(0.50,NaN,0.10), ...
    'A nonfinite effectiveness loss must be rejected.');
assertRejects(@() model(0.50,Inf,0.10), ...
    'An infinite effectiveness loss must be rejected.');
assertRejects(@() model(0.50,0.20i,0.10), ...
    'A complex effectiveness loss must be rejected.');
assertRejects(@() model(0.50,0.20,[0.05 0.10]), ...
    'A nonscalar ripple amplitude must be rejected.');
assertRejects(@() model(0.50,0.20,-0.01), ...
    'A negative ripple amplitude must be rejected.');
assertRejects(@() model(0.50,0.20,1.01), ...
    'A ripple amplitude above the resource bound must be rejected.');
assertRejects(@() model(0.50,0.20,NaN), ...
    'A nonfinite ripple amplitude must be rejected.');
assertRejects(@() model(0.50,0.20,Inf), ...
    'An infinite ripple amplitude must be rejected.');
assertRejects(@() model(0.50,0.20,0.10i), ...
    'A complex ripple amplitude must be rejected.');

recovered = model(0.50,0.20,0.10);
assert(isequal(recovered,baseline), ...
    'Rejected malformed calls must not contaminate exact recovery.');

disp(['P10 checks passed. Explain how P09''s signed residual and T create ' ...
    'a threshold decision, why threshold and fault magnitude trade off, ' ...
    'and why detection alone is not isolation or recovery.']);
end

function assertRejects(operation,message)
didReject = false;
try
    operation();
catch
    didReject = true;
end
assert(didReject,message);
end
