%% P07 - Construct a Reliability Block Diagram
% Guiding question:
% What inputs, observable effects, and failure modes matter when you
% construct a Reliability Block Diagram?

%% Read the functional boundary before looking at MATLAB controls
disp(['P06 identified three failure modes for the fixed 1000-hour, ' ...
    'no-repair cooling mission: shared supply absent (S), Pump A no flow ' ...
    '(A), and Pump B no flow (B).']);
disp(['Turn each row around into required success. Cooling succeeds when ' ...
    'S works AND either A OR B works. An RBD represents this functional ' ...
    'success logic; it does not copy the physical wiring diagram.']);
disp(['Each input is a block success probability over the same mission. ' ...
    'P06 detection coverage stays outside this RBD because observation ' ...
    'alone does not prevent or recover a failure.']);

%% Make one prediction, then construct the deterministic baseline
disp(['Prediction: if one physical supply feeds both pumps, should its ' ...
    'success block appear once before the pump split or once inside each ' ...
    'branch?']);
baseline = model(0.995,0.90,0.90);
topologyFigure = figure('Name','P07 lesson baseline: RBD topology');
topologyAxes = axes('Parent',topologyFigure);
drawCorrectRbd(topologyAxes,baseline);
disp(['Trace one path at a time. S-A and S-B are the two minimal success ' ...
    'paths, and both contain the same S block.']);

%% Advance once to the complementary probability view
ledgerFigure = figure('Name','P07 lesson baseline: outcome ledger');
ledgerAxes = axes('Parent',ledgerFigure);
bar(ledgerAxes,1:5,baseline.outcomeProbabilities,0.68);
grid(ledgerAxes,'on'); xticks(ledgerAxes,1:5);
xticklabels(ledgerAxes,{'S fails','S works; A+B fail', ...
    'S + only A','S + only B','S + A + B'});
ylabel(ledgerAxes, ...
    'Outcome probability per fixed 1000-hour mission (dimensionless)');
title(ledgerAxes,'Disjoint outcomes reveal why the RBD succeeds or fails');
ylim(ledgerAxes,[0 1]);
fprintf(['R_pumps = %.5f; R_system = %.5f; Q_system = %.5f. ' ...
    'The last three outcomes sum to success.\n'], ...
    baseline.pumpGroupReliability,baseline.systemReliability, ...
    baseline.systemFailureProbability);
disp(['P05 found top-event probability 0.01495 from failure logic. ' ...
    'P07 reaches its exact complement 0.98505 from success logic.']);

%% Move one lever, reset, then move the independent lever
disp(['Open the live window at baseline. First change only shared-supply ' ...
    'reliability and observe that every success path moves.']);
disp(['Reset. Then change only Pump-A reliability and observe that the ' ...
    'supply and Pump B stay fixed; Pump A matters only when B fails.']);
disp(['Run experiment.m one section at a time for the exact two sweeps and ' ...
    'the deliberately duplicated-supply broken case.']);
interactive;

function drawCorrectRbd(axesHandle,out)
cla(axesHandle,'reset'); hold(axesHandle,'on');
plot(axesHandle,[0.5 1.2],[0 0],'k-','LineWidth',1.5);
drawBlock(axesHandle,1.2,-0.55,1.8,1.1, ...
    sprintf('S: supply works\nR_S = %.3f',out.blockReliabilities(1)), ...
    [0.86 0.92 1.00]);
plot(axesHandle,[3.0 4.0],[0 0],'k-','LineWidth',1.5);
plot(axesHandle,[4.0 4.0],[-1.5 1.5],'k-','LineWidth',1.5);
plot(axesHandle,[4.0 4.8],[1.5 1.5],'k-','LineWidth',1.5);
plot(axesHandle,[4.0 4.8],[-1.5 -1.5],'k-','LineWidth',1.5);
drawBlock(axesHandle,4.8,0.95,1.8,1.1, ...
    sprintf('A: Pump A works\nR_A = %.3f',out.blockReliabilities(2)), ...
    [0.90 0.96 0.86]);
drawBlock(axesHandle,4.8,-2.05,1.8,1.1, ...
    sprintf('B: Pump B works\nR_B = %.3f',out.blockReliabilities(3)), ...
    [0.90 0.96 0.86]);
plot(axesHandle,[6.6 7.5],[1.5 1.5],'k-','LineWidth',1.5);
plot(axesHandle,[6.6 7.5],[-1.5 -1.5],'k-','LineWidth',1.5);
plot(axesHandle,[7.5 7.5],[-1.5 1.5],'k-','LineWidth',1.5);
plot(axesHandle,[7.5 8.7],[0 0],'k-','LineWidth',1.5);
text(axesHandle,0.45,0,'SOURCE','HorizontalAlignment','right');
text(axesHandle,8.75,0,'COOLING','HorizontalAlignment','left');
text(axesHandle,4.0,2.25,'split: either pump may succeed', ...
    'HorizontalAlignment','center');
text(axesHandle,4.9,-2.65,sprintf( ...
    'R_{system} = R_S[R_A + (1-R_A)R_B] = %.5f', ...
    out.systemReliability),'HorizontalAlignment','center', ...
    'Interpreter','tex','FontWeight','bold');
axis(axesHandle,[0 9.6 -3 3]); axis(axesHandle,'off');
title(axesHandle,'Functional success topology: S AND (A OR B)');
hold(axesHandle,'off');
end

function drawBlock(axesHandle,x,y,width,height,label,color)
rectangle('Parent',axesHandle,'Position',[x y width height], ...
    'FaceColor',color,'EdgeColor',[0.15 0.15 0.15],'LineWidth',1.3);
text(axesHandle,x+width/2,y+height/2,label, ...
    'HorizontalAlignment','center','VerticalAlignment','middle', ...
    'Interpreter','tex');
end
