function out = model(sharedSupplyReliability,pumpAReliability,pumpBReliability)
%MODEL Quantify one shared series block feeding two parallel pump blocks.
%   Inputs are block success probabilities over P06's fixed 1000-hour,
%   no-repair mission. The RBD success rule is S AND (A OR B). Quantifying
%   the diagram assumes the S, A, and B block-success events are mutually
%   independent; the functional topology itself does not prove that claim.
arguments
    sharedSupplyReliability (1,1) double = 0.995
    pumpAReliability (1,1) double = 0.90
    pumpBReliability (1,1) double = 0.90
end

validateattributes(sharedSupplyReliability,{'double'}, ...
    {'real','finite','>=',0,'<=',1},mfilename, ...
    'sharedSupplyReliability');
validateattributes(pumpAReliability,{'double'}, ...
    {'real','finite','>=',0,'<=',1},mfilename,'pumpAReliability');
validateattributes(pumpBReliability,{'double'}, ...
    {'real','finite','>=',0,'<=',1},mfilename,'pumpBReliability');

blockReliabilities = [sharedSupplyReliability,pumpAReliability, ...
    pumpBReliability];
blockFailureProbabilities = 1-blockReliabilities;
sharedSupplyFailureProbability = blockFailureProbabilities(1);
pumpAFailureProbability = blockFailureProbabilities(2);
pumpBFailureProbability = blockFailureProbabilities(3);

% Disjoint form of A OR B: either A works, or A fails and B works.
pumpGroupReliability = pumpAReliability + ...
    pumpAFailureProbability*pumpBReliability;
pumpGroupFailureProbability = pumpAFailureProbability* ...
    pumpBFailureProbability;

% The shared supply is required before either parallel branch can succeed.
systemReliability = sharedSupplyReliability*pumpGroupReliability;
sharedSupplyFailureContribution = sharedSupplyFailureProbability;
dualPumpFailureContribution = sharedSupplyReliability* ...
    pumpGroupFailureProbability;
systemFailureProbability = sharedSupplyFailureContribution + ...
    dualPumpFailureContribution;
probabilityClosureResidual = systemReliability + ...
    systemFailureProbability-1;

% Minimal success paths S-A and S-B overlap when S, A, and B all work.
minimalPathReliabilities = [ ...
    sharedSupplyReliability*pumpAReliability, ...
    sharedSupplyReliability*pumpBReliability];
successPathOverlapProbability = sharedSupplyReliability* ...
    pumpAReliability*pumpBReliability;
rawSuccessPathSum = sum(minimalPathReliabilities);
inclusionExclusionReliability = rawSuccessPathSum- ...
    successPathOverlapProbability;

% A complete disjoint outcome ledger makes success and failure auditable.
outcomeProbabilities = [ ...
    sharedSupplyFailureProbability, ...
    sharedSupplyReliability*pumpAFailureProbability* ...
        pumpBFailureProbability, ...
    sharedSupplyReliability*pumpAReliability*pumpBFailureProbability, ...
    sharedSupplyReliability*pumpAFailureProbability*pumpBReliability, ...
    sharedSupplyReliability*pumpAReliability*pumpBReliability];

% Deliberately wrong comparison: redraw the one physical supply inside both
% pump paths and combine S-A and S-B as though their shared S events were
% independent. Compute the exact nonnegative optimism before adding it to
% the correct result; subtracting nearly equal reliabilities can produce a
% false negative gap near R_S=1 because of floating-point cancellation.
wrongPathOverlapProbability = prod(minimalPathReliabilities);
wrongReliabilityOverstatement = sharedSupplyReliability* ...
    sharedSupplyFailureProbability*pumpAReliability*pumpBReliability;
wrongIndependentPathReliability = systemReliability + ...
    wrongReliabilityOverstatement;

out = struct( ...
    'missionDurationHours',1000, ...
    'blockReliabilities',blockReliabilities, ...
    'blockFailureProbabilities',blockFailureProbabilities, ...
    'pumpGroupReliability',pumpGroupReliability, ...
    'pumpGroupFailureProbability',pumpGroupFailureProbability, ...
    'systemReliability',systemReliability, ...
    'systemFailureProbability',systemFailureProbability, ...
    'sharedSupplyFailureContribution', ...
        sharedSupplyFailureContribution, ...
    'dualPumpFailureContribution',dualPumpFailureContribution, ...
    'probabilityClosureResidual',probabilityClosureResidual, ...
    'minimalPathReliabilities',minimalPathReliabilities, ...
    'successPathOverlapProbability',successPathOverlapProbability, ...
    'rawSuccessPathSum',rawSuccessPathSum, ...
    'inclusionExclusionReliability',inclusionExclusionReliability, ...
    'outcomeProbabilities',outcomeProbabilities, ...
    'wrongIndependentPathReliability', ...
        wrongIndependentPathReliability, ...
    'wrongPathOverlapProbability',wrongPathOverlapProbability, ...
    'wrongReliabilityOverstatement',wrongReliabilityOverstatement, ...
    'systemReliabilitySensitivityToSharedSupply', ...
        pumpGroupReliability, ...
    'systemReliabilitySensitivityToPumpA', ...
        sharedSupplyReliability*pumpBFailureProbability, ...
    'systemReliabilitySensitivityToPumpB', ...
        sharedSupplyReliability*pumpAFailureProbability);

out.blockIds = {'S','A','B'};
out.blockFunctions = { ...
    'Shared supply energizes the cooling bus', ...
    'Pump A carries the cooling load', ...
    'Pump B carries the cooling load'};
out.minimalPathSets = {'S-A','S-B'};
out.pathIncidence = [1 1 0;1 0 1];
out.successLogic = 'S AND (A OR B)';
out.quantificationAssumption = ...
    'S, A, and B block-success events are mutually independent';
out.outcomeNames = { ...
    'Shared supply fails', ...
    'Supply works; both pumps fail', ...
    'Supply and only Pump A work', ...
    'Supply and only Pump B work', ...
    'Supply and both pumps work'};
end
