function run_checks
%RUN_CHECKS Check P07 RBD topology, accounting, limits, and rejection.
baseline = model(0.995,0.90,0.90);
repeat = model(0.995,0.90,0.90);
assert(isequal(baseline,repeat), ...
    'Identical inputs must produce identical outputs.');

assert(isscalar(baseline) && baseline.missionDurationHours == 1000, ...
    'The model must return one scalar result for P06''s fixed 1000-hour mission.');
assert(isequal(size(baseline.blockReliabilities),[1 3]) && ...
    isequal(size(baseline.blockFailureProbabilities),[1 3]), ...
    'Block reliability and failure outputs must remain fixed 1x3 rows.');
assert(isequal(size(baseline.minimalPathReliabilities),[1 2]) && ...
    isequal(size(baseline.pathIncidence),[2 3]), ...
    'The two minimal paths and their fixed 2x3 incidence must remain explicit.');
assert(isequal(size(baseline.outcomeProbabilities),[1 5]), ...
    'The complete disjoint outcome ledger must remain a fixed 1x5 row.');
assert(isequal(baseline.blockIds,{'S','A','B'}), ...
    'The RBD must retain P06''s shared-supply and two-pump block identity.');
assert(isequal(baseline.minimalPathSets,{'S-A','S-B'}) && ...
    isequal(baseline.pathIncidence,[1 1 0;1 0 1]), ...
    'The only minimal success paths must be S-A and S-B.');
assert(strcmp(baseline.successLogic,'S AND (A OR B)'), ...
    'The functional success rule must remain S AND (A OR B).');
assert(contains(baseline.quantificationAssumption,'mutually independent'), ...
    'Quantification must disclose the independent block-event assumption.');
assert(numel(baseline.blockFunctions) == 3 && ...
    all(~cellfun('isempty',baseline.blockFunctions)), ...
    'Every RBD block must retain a populated required-function statement.');
assert(numel(baseline.outcomeNames) == 5 && ...
    all(~cellfun('isempty',baseline.outcomeNames)), ...
    'Every disjoint outcome must retain an explanatory label.');

probabilityOutputs = [baseline.blockReliabilities, ...
    baseline.blockFailureProbabilities,baseline.pumpGroupReliability, ...
    baseline.pumpGroupFailureProbability,baseline.systemReliability, ...
    baseline.systemFailureProbability,baseline.outcomeProbabilities];
assert(all(isfinite(probabilityOutputs)) && ...
    all(probabilityOutputs >= 0 & probabilityOutputs <= 1), ...
    'Every baseline probability must remain finite and inside [0,1].');
assert(max(abs(baseline.blockReliabilities + ...
    baseline.blockFailureProbabilities-1)) < 1e-15, ...
    'Each block reliability and failure probability must be complementary.');
assert(abs(baseline.probabilityClosureResidual) < 1e-15 && ...
    abs(baseline.systemReliability + ...
    baseline.systemFailureProbability-1) < 1e-15, ...
    'System reliability and failure probability must close to one.');

assert(abs(baseline.pumpGroupReliability-0.99) < 1e-15, ...
    'The independent one-out-of-two pump group must equal 0.99.');
assert(abs(baseline.pumpGroupFailureProbability-0.01) < 1e-15, ...
    'The pump group fails only when both 0.10 failure events occur.');
assert(abs(baseline.systemReliability-0.98505) < 1e-15, ...
    'The baseline RBD reliability must independently equal 0.98505.');
assert(abs(baseline.systemFailureProbability-0.01495) < 1e-15, ...
    'The baseline failure probability must independently equal 0.01495.');
assert(abs(baseline.sharedSupplyFailureContribution-0.005) < 1e-15 && ...
    abs(baseline.dualPumpFailureContribution-0.00995) < 1e-15, ...
    'P05 failure terms must remain shared loss plus supply-up dual-pump loss.');
assert(abs(baseline.systemFailureProbability- ...
    (0.005+(1-0.005)*0.10*0.10)) < 1e-15, ...
    'P07 success logic must exactly complement P05 top-event arithmetic.');

expectedOutcomes = [0.00500 0.00995 0.08955 0.08955 0.80595];
assert(max(abs(baseline.outcomeProbabilities-expectedOutcomes)) < 1e-15, ...
    'The five baseline disjoint outcomes must match independent references.');
assert(abs(sum(baseline.outcomeProbabilities)-1) < 1e-15, ...
    'The disjoint outcome ledger must form a complete probability partition.');
assert(abs(sum(baseline.outcomeProbabilities(3:5))- ...
    baseline.systemReliability) < 1e-15, ...
    'The three success outcomes must add to system reliability.');
assert(abs(sum(baseline.outcomeProbabilities(1:2))- ...
    baseline.systemFailureProbability) < 1e-15, ...
    'The two failure outcomes must add to system failure probability.');

assert(max(abs(baseline.minimalPathReliabilities- ...
    [0.89550 0.89550])) < 1e-15, ...
    'The S-A and S-B minimal path probabilities must each equal 0.89550.');
assert(abs(baseline.successPathOverlapProbability-0.80595) < 1e-15, ...
    'The actual shared S-A-B path intersection must equal 0.80595.');
assert(baseline.rawSuccessPathSum > 1 && ...
    abs(baseline.rawSuccessPathSum-1.791) < 1e-15, ...
    'Blindly adding overlapping success paths must expose an impossible sum.');
assert(abs(baseline.inclusionExclusionReliability- ...
    baseline.systemReliability) < 1e-15, ...
    'Inclusion-exclusion must recover the direct RBD reliability.');
assert(abs(baseline.systemReliabilitySensitivityToSharedSupply-0.99) < 1e-15 && ...
    abs(baseline.systemReliabilitySensitivityToPumpA-0.0995) < 1e-15 && ...
    abs(baseline.systemReliabilitySensitivityToPumpB-0.0995) < 1e-15, ...
    'Baseline reliability sensitivities must match the transparent derivatives.');

states = [0 0 0;0 0 1;0 1 0;0 1 1; ...
    1 0 0;1 0 1;1 1 0;1 1 1];
truth = logical(states(:,1)) & ...
    (logical(states(:,2)) | logical(states(:,3)));
assert(isequal(truth,[false;false;false;false;false;true;true;true]), ...
    'Eight-state truth enumeration must implement S AND (A OR B).');

sharedSupplyReliabilitySweep = [0 0.50 0.90 0.995 1];
actualSupplySweep = zeros(size(sharedSupplyReliabilitySweep));
actualSupplyFailureSweep = zeros(size(sharedSupplyReliabilitySweep));
actualPumpGroupSupplySweep = zeros(size(sharedSupplyReliabilitySweep));
actualOutcomeSupplySweep = zeros(numel(sharedSupplyReliabilitySweep),5);
for k = 1:numel(sharedSupplyReliabilitySweep)
    changed = model(sharedSupplyReliabilitySweep(k),0.90,0.90);
    actualSupplySweep(k) = changed.systemReliability;
    actualSupplyFailureSweep(k) = changed.systemFailureProbability;
    actualPumpGroupSupplySweep(k) = changed.pumpGroupReliability;
    actualOutcomeSupplySweep(k,:) = changed.outcomeProbabilities;
    assert(isequal(changed.blockReliabilities(2:3),[0.90 0.90]), ...
        'Changing R_S must leave both pump block inputs unchanged.');
    assert(isequal(changed.minimalPathSets,baseline.minimalPathSets) && ...
        isequal(changed.pathIncidence,baseline.pathIncidence), ...
        'Changing R_S must not rewrite the RBD path topology.');
end
assert(max(abs(actualSupplySweep- ...
    [0 0.495 0.891 0.98505 0.99])) < 1e-15, ...
    'The shared-supply sweep must match independent reference reliabilities.');
assert(max(abs(actualSupplyFailureSweep- ...
    [1 0.505 0.109 0.01495 0.01])) < 1e-15, ...
    'The shared-supply sweep failure complements must match references.');
assert(max(abs(actualPumpGroupSupplySweep-0.99)) < 1e-15, ...
    'The parallel pump group must remain fixed throughout sweep 1.');
assert(all(diff(actualSupplySweep) > 0), ...
    'Increasing shared-supply reliability must increase system reliability.');
expectedOutcomeSupplySweep = [ ...
    1.000 0       0       0       0; ...
    0.500 0.00500 0.04500 0.04500 0.40500; ...
    0.100 0.00900 0.08100 0.08100 0.72900; ...
    0.005 0.00995 0.08955 0.08955 0.80595; ...
    0     0.01000 0.09000 0.09000 0.81000];
supplyOutcomeResidual = actualOutcomeSupplySweep- ...
    expectedOutcomeSupplySweep;
assert(max(abs(supplyOutcomeResidual(:))) < 1e-15, ...
    'Every R_S sweep point must retain the exact five-state outcome ledger.');
assert(max(abs(sum(actualOutcomeSupplySweep,2)-1)) < 1e-15 && ...
    max(abs(sum(actualOutcomeSupplySweep(:,1:2),2)- ...
    actualSupplyFailureSweep(:))) < 1e-15 && ...
    max(abs(sum(actualOutcomeSupplySweep(:,3:5),2)- ...
    actualSupplySweep(:))) < 1e-15, ...
    'Every R_S outcome ledger must close and partition failure from success.');
assert(all(diff(actualOutcomeSupplySweep(:,1)) < 0) && ...
    all(all(diff(actualOutcomeSupplySweep(:,2:5),1,1) > 0)), ...
    ['Increasing R_S must reduce the supply-failure state and raise every ' ...
    'supply-up state.']);

pumpAReliabilitySweep = [0 0.25 0.50 0.75 1];
actualPumpASweep = zeros(size(pumpAReliabilitySweep));
actualPumpAFailureSweep = zeros(size(pumpAReliabilitySweep));
actualSharedFailureContribution = zeros(size(pumpAReliabilitySweep));
actualOutcomePumpASweep = zeros(numel(pumpAReliabilitySweep),5);
for k = 1:numel(pumpAReliabilitySweep)
    changed = model(0.995,pumpAReliabilitySweep(k),0.90);
    actualPumpASweep(k) = changed.systemReliability;
    actualPumpAFailureSweep(k) = changed.systemFailureProbability;
    actualSharedFailureContribution(k) = ...
        changed.sharedSupplyFailureContribution;
    actualOutcomePumpASweep(k,:) = changed.outcomeProbabilities;
    assert(isequal(changed.blockReliabilities([1 3]),[0.995 0.90]), ...
        'Changing R_A must leave the shared supply and Pump B unchanged.');
    assert(isequal(changed.blockFunctions,baseline.blockFunctions) && ...
        isequal(changed.pathIncidence,baseline.pathIncidence), ...
        'Changing R_A must not rewrite block functions or path topology.');
end
assert(max(abs(actualPumpASweep- ...
    [0.8955 0.920375 0.94525 0.970125 0.995])) < 1e-15, ...
    'The Pump-A sweep must match independent reference reliabilities.');
assert(max(abs(actualPumpAFailureSweep- ...
    [0.1045 0.079625 0.05475 0.029875 0.005])) < 1e-15, ...
    'The Pump-A sweep failure complements must match references.');
assert(max(abs(actualSharedFailureContribution-0.005)) < 1e-15, ...
    'The shared-supply failure contribution must remain fixed in sweep 2.');
assert(all(diff(actualPumpASweep) > 0), ...
    'Increasing Pump-A reliability must increase system reliability.');
expectedOutcomePumpASweep = [ ...
    0.005 0.099500 0        0.895500 0; ...
    0.005 0.074625 0.024875 0.671625 0.223875; ...
    0.005 0.049750 0.049750 0.447750 0.447750; ...
    0.005 0.024875 0.074625 0.223875 0.671625; ...
    0.005 0        0.099500 0        0.895500];
pumpAOutcomeResidual = actualOutcomePumpASweep- ...
    expectedOutcomePumpASweep;
assert(max(abs(pumpAOutcomeResidual(:))) < 1e-15, ...
    'Every R_A sweep point must retain the exact five-state outcome ledger.');
assert(max(abs(sum(actualOutcomePumpASweep,2)-1)) < 1e-15 && ...
    max(abs(sum(actualOutcomePumpASweep(:,1:2),2)- ...
    actualPumpAFailureSweep(:))) < 1e-15 && ...
    max(abs(sum(actualOutcomePumpASweep(:,3:5),2)- ...
    actualPumpASweep(:))) < 1e-15, ...
    'Every R_A outcome ledger must close and partition failure from success.');
assert(max(abs(actualOutcomePumpASweep(:,1)-0.005)) < 1e-15 && ...
    all(all(diff(actualOutcomePumpASweep(:,[2 4]),1,1) < 0)) && ...
    all(all(diff(actualOutcomePumpASweep(:,[3 5]),1,1) > 0)), ...
    ['Increasing R_A must preserve supply failure, reduce A-failed states, ' ...
    'and raise A-success states.']);

allPerfect = model(1,1,1);
assert(allPerfect.systemReliability == 1 && ...
    allPerfect.systemFailureProbability == 0, ...
    'Three perfect blocks must give certain mission success.');
supplyFailed = model(0,1,1);
assert(supplyFailed.systemReliability == 0 && ...
    supplyFailed.systemFailureProbability == 1, ...
    'A certainly failed shared supply must defeat both pump branches.');
pumpsFailed = model(1,0,0);
assert(pumpsFailed.systemReliability == 0 && ...
    pumpsFailed.systemFailureProbability == 1, ...
    'Two certainly failed pumps must make cooling unavailable.');
pumpAPerfect = model(0.73,1,0.20);
pumpBPerfect = model(0.73,0.20,1);
assert(pumpAPerfect.systemReliability == 0.73 && ...
    pumpBPerfect.systemReliability == 0.73, ...
    'Either perfect pump must make system reliability equal R_S.');
pumpAFailed = model(0.80,0,0.75);
assert(abs(pumpAFailed.systemReliability-0.60) < 1e-15, ...
    'A certainly failed Pump A must reduce the RBD to S in series with B.');
noSharedFailure = model(1,0.40,0.70);
assert(abs(noSharedFailure.systemReliability- ...
    (0.40+0.60*0.70)) < 1e-15, ...
    'A perfect supply must recover ordinary independent pump redundancy.');
swapped = model(0.995,0.90,0.65);
reverse = model(0.995,0.65,0.90);
assert(abs(swapped.systemReliability-reverse.systemReliability) < 1e-15 && ...
    abs(swapped.systemFailureProbability- ...
    reverse.systemFailureProbability) < 1e-15, ...
    'Swapping Pump A and Pump B must preserve system probabilities.');

tinySuccess = model(realmin,1,0);
assert(tinySuccess.systemReliability == realmin && ...
    tinySuccess.systemReliability > 0, ...
    'A representable tiny success contribution must not be discarded.');
nearOne = 1-eps(1);
tinyFailure = model(1,nearOne,nearOne);
assert(tinyFailure.systemFailureProbability > 0 && ...
    abs(tinyFailure.systemFailureProbability/(eps(1)^2)-1) < 1e-15, ...
    'Direct failure accounting must retain a tiny dual-pump failure product.');

brokenCase = model(0.80,0.90,0.90);
assert(abs(brokenCase.systemReliability-0.7920) < 1e-15, ...
    'The correct stressed one-supply RBD must equal 0.7920.');
assert(abs(brokenCase.wrongIndependentPathReliability-0.9216) < 1e-15, ...
    'Duplicated independent supply drawings must produce the 0.9216 symptom.');
assert(abs(brokenCase.wrongReliabilityOverstatement-0.1296) < 1e-15, ...
    'The duplicated-supply optimism must equal 0.1296.');
expectedOverstatement = 0.80*(1-0.80)*0.90*0.90;
assert(abs(brokenCase.wrongReliabilityOverstatement- ...
    expectedOverstatement) < 1e-15, ...
    'Broken-case overstatement must equal the missing shared-path overlap.');
assert(abs(brokenCase.successPathOverlapProbability-0.648) < 1e-15 && ...
    abs(brokenCase.wrongPathOverlapProbability-0.5184) < 1e-15, ...
    'The wrong independent formula must subtract R_S twice in the overlap.');
perfectSupplyPaths = model(1,0.90,0.90);
assert(abs(perfectSupplyPaths.wrongIndependentPathReliability- ...
    perfectSupplyPaths.systemReliability) < 1e-15, ...
    'A perfect shared block is the limit where the wrong path independence is harmless.');
nearPerfectSupply = model(1-eps(1),0.10,0.50);
expectedNearPerfectGap = (1-eps(1))*eps(1)*0.10*0.50;
assert(nearPerfectSupply.wrongReliabilityOverstatement > 0 && ...
    abs(nearPerfectSupply.wrongReliabilityOverstatement/ ...
    expectedNearPerfectGap-1) < 1e-15, ...
    'Near a perfect supply, the exact wrong-model optimism must stay positive.');
assert(nearPerfectSupply.wrongIndependentPathReliability >= ...
    nearPerfectSupply.systemReliability, ...
    'Floating-point cancellation must not make the wrong model look pessimistic.');

assertRejects(@() model([0.995 0.90],0.90,0.90), ...
    'A nonscalar shared-supply reliability must be rejected.');
assertRejects(@() model(-0.01,0.90,0.90), ...
    'A negative shared-supply reliability must be rejected.');
assertRejects(@() model(1.01,0.90,0.90), ...
    'A shared-supply reliability above one must be rejected.');
assertRejects(@() model(NaN,0.90,0.90), ...
    'A nonfinite shared-supply reliability must be rejected.');
assertRejects(@() model(Inf,0.90,0.90), ...
    'An infinite shared-supply reliability must be rejected.');
assertRejects(@() model(0.9i,0.90,0.90), ...
    'A complex shared-supply reliability must be rejected.');
assertRejects(@() model(0.995,[0.90 0.80],0.90), ...
    'A nonscalar Pump-A reliability must be rejected.');
assertRejects(@() model(0.995,-0.01,0.90), ...
    'A negative Pump-A reliability must be rejected.');
assertRejects(@() model(0.995,1.01,0.90), ...
    'A Pump-A reliability above one must be rejected.');
assertRejects(@() model(0.995,NaN,0.90), ...
    'A nonfinite Pump-A reliability must be rejected.');
assertRejects(@() model(0.995,Inf,0.90), ...
    'An infinite Pump-A reliability must be rejected.');
assertRejects(@() model(0.995,0.9i,0.90), ...
    'A complex Pump-A reliability must be rejected.');
assertRejects(@() model(0.995,0.90,[0.90;0.80]), ...
    'A nonscalar Pump-B reliability must be rejected.');
assertRejects(@() model(0.995,0.90,-0.01), ...
    'A negative Pump-B reliability must be rejected.');
assertRejects(@() model(0.995,0.90,1.01), ...
    'A Pump-B reliability above one must be rejected.');
assertRejects(@() model(0.995,0.90,NaN), ...
    'A nonfinite Pump-B reliability must be rejected.');
assertRejects(@() model(0.995,0.90,Inf), ...
    'An infinite Pump-B reliability must be rejected.');
assertRejects(@() model(0.995,0.90,0.9i), ...
    'A complex Pump-B reliability must be rejected.');

recovered = model(0.995,0.90,0.90);
assert(isequal(recovered,baseline), ...
    'Rejected malformed calls must not contaminate a later valid calculation.');

disp(['P07 checks passed. Explain how P06 rows become S AND (A OR B), ' ...
    'why P05 is its failure complement, and why one shared block cannot ' ...
    'be duplicated into independent paths.']);
end

function assertRejects(operation,message)
didReject = false;
try
    operation();
catch
    didReject = true;
end
assert(didReject,message);
end
