function run_checks
%RUN_CHECKS Check P11 residual signatures, sweeps, limits, and rejection.
baseline = model(0.20,0);
repeat = model(0.20,0);
assert(isequal(baseline,repeat), ...
    'Identical inputs must produce identical outputs.');

assert(isscalar(baseline) && baseline.sampleCount == 301 && ...
    baseline.samplePeriodSeconds == 0.1, ...
    'The model must return one fixed 301-sample deterministic record.');
signalNames = {'timeSeconds','speedCommand','faultActive', ...
    'predictedFlowLpm','trueFlowLpm','measuredFlowLpm', ...
    'deterministicFlowRippleLpm','pumpLossFlowResidualLpm', ...
    'sensorBiasFlowResidualLpm','flowResidualLpm', ...
    'predictedPressureKpa','truePressureKpa','measuredPressureKpa', ...
    'deterministicPressureRippleKpa','pumpLossPressureResidualKpa', ...
    'pressureResidualKpa','biasConsistencyResidualKpa', ...
    'healthyReferenceWindow','faultReferenceWindow', ...
    'p10SignedThresholdLpm','p10Alarm', ...
    'pressureSignedThresholdKpa','pressureAlarm'};
for k = 1:numel(signalNames)
    assert(isequal(size(baseline.(signalNames{k})),[301 1]), ...
        'Every signal output must remain a fixed 301x1 column.');
end
assert(abs(baseline.timeSeconds(1)) < 1e-15 && ...
    abs(baseline.timeSeconds(end)-30) < 1e-12 && ...
    max(abs(diff(baseline.timeSeconds)-0.1)) < 1e-12, ...
    'Time must span 0 through 30 seconds in fixed 0.1-second steps.');
assert(all(baseline.speedCommand(baseline.timeSeconds < 10) == 0.5) && ...
    all(baseline.speedCommand(baseline.timeSeconds >= 10) == 0.8), ...
    'The known P10 command must change from 0.5 to 0.8 at 10 seconds.');
assert(all(baseline.faultActive(baseline.timeSeconds < 20) == 0) && ...
    all(baseline.faultActive(baseline.timeSeconds >= 20) == 1), ...
    'Both conditional fault injections must activate at 20 seconds.');
assert(baseline.healthyReferenceCount == 60 && ...
    baseline.faultReferenceCount == 60, ...
    'Each fixed reference window must contain exactly three ripple cycles.');

assert(strcmp(baseline.flowResidualEquation, ...
    'r_Q(t) = y_Q(t) - y_Q_hat(t | u(t))') && ...
    strcmp(baseline.pressureResidualEquation, ...
    'r_P(t) = y_P(t) - y_P_hat(t | u(t))') && ...
    strcmp(baseline.flowResidualUnit,'L/min') && ...
    strcmp(baseline.pressureResidualUnit,'kPa'), ...
    'Flow and pressure residual equations, sign convention, and units must remain explicit.');
assert(contains(baseline.signatureEquation,'mean_W(r_Q)') && ...
    contains(baseline.signatureEquation,'mean_W(r_P)') && ...
    contains(baseline.signConvention,'negative residual'), ...
    'The two fixed-window signature tests and negative sign must remain explicit.');
assert(contains(baseline.libraryAssumption,'at most one modeled fault') && ...
    contains(baseline.scopeBoundary,'no posterior probability') && ...
    contains(baseline.scopeBoundary,'field coverage'), ...
    'Single-fault applicability and the P11 evidence boundary must remain explicit.');

independentFlowRippleLpm = 0.10*sin( ...
    2*pi*0.5*baseline.timeSeconds);
independentPumpFlowLpm = -10*0.20*baseline.faultActive.* ...
    baseline.speedCommand;
independentSensorFlowLpm = zeros(size(baseline.timeSeconds));
independentFlowResidualLpm = independentPumpFlowLpm+ ...
    independentSensorFlowLpm+independentFlowRippleLpm;
independentPressureRippleKpa = 0.50*sin( ...
    2*pi*0.5*baseline.timeSeconds);
independentPumpPressureKpa = -50*0.20*baseline.faultActive.* ...
    baseline.speedCommand;
independentPressureResidualKpa = independentPumpPressureKpa+ ...
    independentPressureRippleKpa;
assert(max(abs(baseline.deterministicFlowRippleLpm- ...
    independentFlowRippleLpm)) < 1e-14 && ...
    max(abs(baseline.pumpLossFlowResidualLpm- ...
    independentPumpFlowLpm)) < 1e-14 && ...
    isequal(baseline.sensorBiasFlowResidualLpm, ...
    independentSensorFlowLpm), ...
    'Flow residual components must match independent P10-compatible references.');
assert(isequal(baseline.flowResidualLpm, ...
    independentFlowResidualLpm) && ...
    max(abs(baseline.measuredFlowLpm-baseline.predictedFlowLpm- ...
    baseline.flowResidualLpm)) < 1e-14, ...
    ['The flow residual must preserve P10''s direct component sum while ' ...
    'measured minus predicted closes within floating precision.']);
assert(max(abs(baseline.deterministicPressureRippleKpa- ...
    independentPressureRippleKpa)) < 1e-14 && ...
    max(abs(baseline.pumpLossPressureResidualKpa- ...
    independentPumpPressureKpa)) < 1e-14 && ...
    max(abs(baseline.pressureResidualKpa- ...
    independentPressureResidualKpa)) < 1e-14, ...
    'Pressure residual components must match independent references.');
assert(max(abs(baseline.biasConsistencyResidualKpa- ...
    (baseline.pressureResidualKpa-5*baseline.flowResidualLpm))) < 1e-14 && ...
    max(abs(baseline.biasConsistencyResidualKpa)) < 1e-13, ...
    'The calibrated consistency residual r_P-5r_Q must cancel pure pump loss.');

independentP10BoundaryLpm = -0.50*ones(size(baseline.timeSeconds));
independentP10Alarm = independentFlowResidualLpm <= ...
    independentP10BoundaryLpm;
assert(isequal(baseline.p10SignedThresholdLpm, ...
    independentP10BoundaryLpm) && ...
    isequal(baseline.p10Alarm,independentP10Alarm) && ...
    baseline.p10FalseAlarmSampleFraction == 0 && ...
    baseline.p10DetectionSampleFraction == 1, ...
    'P10 pointwise flow threshold behavior must remain compatible at zero bias.');

assert(abs(baseline.healthyMeanFlowResidualLpm) < 1e-12 && ...
    abs(baseline.healthyMeanPressureResidualKpa) < 1e-12 && ...
    abs(baseline.postFaultMeanFlowResidualLpm+1.6) < 1e-12 && ...
    abs(baseline.postFaultMeanPressureResidualKpa+8) < 1e-12, ...
    'Baseline Pump-A residual means must be 0/0 healthy and -1.6/-8 after injection.');
assert(isequal(baseline.candidateSignatureMatrix,[0 0;1 1;1 0]) && ...
    size(unique(baseline.candidateSignatureMatrix,'rows'),1) == 3, ...
    'The full two-channel candidate signatures must be fixed and distinct.');
assert(isequal(baseline.observedSignature,[1 1]) && ...
    strcmp(baseline.signatureCode,'11') && ...
    isequal(baseline.hammingDistances,[2;0;1]) && ...
    baseline.exactMatchCount == 1 && ...
    strcmp(baseline.decodedCandidateLabel, ...
    'Pump-A effectiveness loss') && baseline.isCorrectIsolation, ...
    'The baseline Pump-A case must have one correct exact signature match.');

sensorCase = model(0,1.60);
assert(max(abs(sensorCase.flowResidualLpm- ...
    baseline.flowResidualLpm)) < 1e-14, ...
    'Competing baseline faults must have identical pointwise flow residuals.');
assert(abs(sensorCase.postFaultMeanFlowResidualLpm+1.6) < 1e-12 && ...
    abs(sensorCase.postFaultMeanPressureResidualKpa) < 1e-12 && ...
    abs(sensorCase.postFaultMeanBiasConsistencyKpa-8) < 1e-12, ...
    'The sensor case must have -1.6 L/min flow, zero pressure, and 8 kPa consistency means.');
assert(isequal(sensorCase.observedSignature,[1 0]) && ...
    strcmp(sensorCase.signatureCode,'10') && ...
    isequal(sensorCase.hammingDistances,[1;1;0]) && ...
    sensorCase.exactMatchCount == 1 && ...
    strcmp(sensorCase.decodedCandidateLabel, ...
    'Flow-sensor negative bias') && sensorCase.isCorrectIsolation, ...
    'The competing sensor case must have one correct exact signature match.');

healthy = model(0,0);
assert(isequal(healthy.observedSignature,[0 0]) && ...
    strcmp(healthy.signatureCode,'00') && ...
    isequal(healthy.hammingDistances,[0;2;1]) && ...
    healthy.exactMatchCount == 1 && healthy.isCorrectIsolation, ...
    'Zero faults must give the unique healthy limiting signature 00.');

inclusiveFlowBoundary = model(0,0.50);
inclusivePressureBoundary = model(0.10,0);
assert(abs(inclusiveFlowBoundary.postFaultMeanFlowResidualLpm+0.50) < ...
    inclusiveFlowBoundary.flowFeatureComparisonToleranceLpm && ...
    isequal(inclusiveFlowBoundary.observedSignature,[1 0]) && ...
    inclusiveFlowBoundary.flowFeatureCrossed && ...
    inclusiveFlowBoundary.isCorrectIsolation, ...
    ['A sensor bias analytically on the inclusive mean-flow boundary ' ...
    'must retain code 10 despite sampled-mean roundoff.']);
assert(abs(inclusivePressureBoundary.postFaultMeanPressureResidualKpa+4) < ...
    inclusivePressureBoundary.pressureFeatureComparisonToleranceKpa && ...
    isequal(inclusivePressureBoundary.observedSignature,[1 1]) && ...
    inclusivePressureBoundary.pressureFeatureCrossed && ...
    inclusivePressureBoundary.isCorrectIsolation, ...
    ['A 10-percent loss analytically on the inclusive mean-pressure ' ...
    'boundary must retain code 11 despite sampled-mean roundoff.']);

outsideToleranceInputMargin = 128*eps(1);
justClearFlowBoundary = model(0,0.50-outsideToleranceInputMargin);
justClearPressureBoundary = model( ...
    0.10-outsideToleranceInputMargin,0);
assert(justClearFlowBoundary.postFaultMeanFlowResidualLpm > ...
    -justClearFlowBoundary.flowThresholdMagnitudeLpm+ ...
    justClearFlowBoundary.flowFeatureComparisonToleranceLpm && ...
    ~justClearFlowBoundary.flowFeatureCrossed && ...
    isequal(justClearFlowBoundary.observedSignature,[0 0]), ...
    ['A sensor bias just outside the numerical flow tolerance must ' ...
    'remain clear rather than widening the physical decision band.']);
assert(justClearPressureBoundary.postFaultMeanPressureResidualKpa > ...
    -justClearPressureBoundary.pressureThresholdMagnitudeKpa+ ...
    justClearPressureBoundary.pressureFeatureComparisonToleranceKpa && ...
    justClearPressureBoundary.flowFeatureCrossed && ...
    ~justClearPressureBoundary.pressureFeatureCrossed && ...
    isequal(justClearPressureBoundary.observedSignature,[1 0]), ...
    ['A pump loss just outside the numerical pressure tolerance must ' ...
    'retain code 10 rather than widening the physical decision band.']);

p10PointwiseBoundary = model(0.0625,0);
expectedP10BoundaryResidualLpm = -10*0.0625* ...
    p10PointwiseBoundary.faultActive.*p10PointwiseBoundary.speedCommand+ ...
    0.10*sin(2*pi*0.5*p10PointwiseBoundary.timeSeconds);
assert(isequal(p10PointwiseBoundary.flowResidualLpm, ...
    expectedP10BoundaryResidualLpm) && ...
    isequal(p10PointwiseBoundary.p10Alarm, ...
    expectedP10BoundaryResidualLpm <= -0.50), ...
    ['P10 pointwise boundary behavior must retain the direct fault-plus-' ...
    'ripple operation order exactly.']);

pumpLossSweep = [0 0.04 0.08 0.12 0.20];
actualPumpFlowMeansLpm = zeros(size(pumpLossSweep));
actualPumpPressureMeansKpa = zeros(size(pumpLossSweep));
actualPumpSignatures = zeros(numel(pumpLossSweep),2);
actualPumpCorrect = false(size(pumpLossSweep));
for k = 1:numel(pumpLossSweep)
    changed = model(pumpLossSweep(k),0);
    actualPumpFlowMeansLpm(k) = changed.postFaultMeanFlowResidualLpm;
    actualPumpPressureMeansKpa(k) = ...
        changed.postFaultMeanPressureResidualKpa;
    actualPumpSignatures(k,:) = changed.observedSignature;
    actualPumpCorrect(k) = changed.isCorrectIsolation;
    assert(all(changed.sensorBiasFlowResidualLpm == 0) && ...
        changed.flowSensorBiasLpm == 0 && ...
        isequal(changed.candidateSignatureMatrix, ...
        baseline.candidateSignatureMatrix), ...
        'Pump-loss sweep must leave sensor bias and candidate library fixed.');
end
assert(max(abs(actualPumpFlowMeansLpm- ...
    [0 -0.32 -0.64 -0.96 -1.6])) < 1e-12 && ...
    max(abs(actualPumpPressureMeansKpa- ...
    [0 -1.6 -3.2 -4.8 -8])) < 1e-12, ...
    'Pump-loss sweep means must match independent references.');
assert(isequal(actualPumpSignatures, ...
    [0 0;0 0;1 0;1 1;1 1]) && ...
    isequal(actualPumpCorrect,[true false false true true]), ...
    'Pump-loss sweep must expose the weak-fault 10 coverage gap.');
weakPump = model(0.08,0);
assert(strcmp(weakPump.decodedCandidateLabel, ...
    'Flow-sensor negative bias') && ~weakPump.isCorrectIsolation && ...
    weakPump.singleFaultLibraryApplicable, ...
    'The negative 8-percent pump case must visibly misisolate as sensor bias.');

sensorBiasSweepLpm = [0 0.30 0.60 1.00 1.60];
actualSensorFlowMeansLpm = zeros(size(sensorBiasSweepLpm));
actualSensorPressureMeansKpa = zeros(size(sensorBiasSweepLpm));
actualSensorSignatures = zeros(numel(sensorBiasSweepLpm),2);
actualSensorCorrect = false(size(sensorBiasSweepLpm));
for k = 1:numel(sensorBiasSweepLpm)
    changed = model(0,sensorBiasSweepLpm(k));
    actualSensorFlowMeansLpm(k) = changed.postFaultMeanFlowResidualLpm;
    actualSensorPressureMeansKpa(k) = ...
        changed.postFaultMeanPressureResidualKpa;
    actualSensorSignatures(k,:) = changed.observedSignature;
    actualSensorCorrect(k) = changed.isCorrectIsolation;
    assert(all(changed.pumpLossFlowResidualLpm == 0) && ...
        all(changed.pumpLossPressureResidualKpa == 0) && ...
        isequal(changed.pressureResidualKpa, ...
        healthy.pressureResidualKpa), ...
        'Sensor-bias sweep must leave pump components and pressure fixed.');
end
assert(max(abs(actualSensorFlowMeansLpm- ...
    [0 -0.30 -0.60 -1.00 -1.60])) < 1e-12 && ...
    max(abs(actualSensorPressureMeansKpa)) < 1e-12, ...
    'Sensor-bias sweep means must match independent references.');
assert(isequal(actualSensorSignatures, ...
    [0 0;0 0;1 0;1 0;1 0]) && ...
    isequal(actualSensorCorrect,[true false true true true]), ...
    'Sensor-bias sweep must retain pressure-clear code 10 after detection.');

assert(isequal(baseline.brokenFlowOnlyCandidateSignatures,[0;1;1]) && ...
    baseline.brokenFlowOnlyObservedSignature == 1 && ...
    isequal(baseline.brokenFlowOnlyHammingDistances,[1;0;0]) && ...
    baseline.brokenFlowOnlyExactMatchCount == 2, ...
    'Removing pressure must create the recognizable two-exact-match ambiguity.');
assert(contains(baseline.brokenAssumption,'distinct signatures') && ...
    contains(baseline.brokenAssumption,'channel'), ...
    'The deliberately broken case must name the diagnosability assumption.');

combined = model(0.20,1.60);
assert(isequal(combined.observedSignature,[1 1]) && ...
    strcmp(combined.decodedCandidateLabel, ...
    'Pump-A effectiveness loss') && ...
    ~combined.singleFaultLibraryApplicable && ...
    ~combined.isCorrectIsolation && ...
    contains(combined.diagnosisStatement,'Not applicable'), ...
    'Simultaneous faults must not masquerade as an applicable single-fault diagnosis.');
assert(abs(combined.postFaultMeanBiasConsistencyKpa-8) < 1e-12, ...
    'The consistency residual must still expose combined sensor bias.');

fullLoss = model(1,0);
assert(abs(fullLoss.postFaultMeanFlowResidualLpm+8) < 1e-12 && ...
    abs(fullLoss.postFaultMeanPressureResidualKpa+40) < 1e-12 && ...
    isequal(fullLoss.observedSignature,[1 1]) && ...
    fullLoss.isCorrectIsolation, ...
    'Full effectiveness loss must retain finite -8 L/min and -40 kPa means.');
maximumBias = model(0,10);
numericOutputs = [maximumBias.flowResidualLpm; ...
    maximumBias.pressureResidualKpa; ...
    maximumBias.biasConsistencyResidualKpa; ...
    maximumBias.hammingDistances; ...
    maximumBias.brokenFlowOnlyHammingDistances];
assert(all(isfinite(numericOutputs)) && numel(numericOutputs) == 909 && ...
    isequal(maximumBias.observedSignature,[1 0]) && ...
    maximumBias.isCorrectIsolation, ...
    'Maximum bounded bias must keep fixed-size outputs finite and isolate sensor bias.');
tinyBias = model(0,eps(1));
assert(any(tinyBias.sensorBiasFlowResidualLpm ~= 0), ...
    'A representable tiny sensor bias must survive in its component output.');

assertRejects(@() model([0.10 0.20],0), ...
    'A nonscalar effectiveness loss must be rejected.');
assertRejects(@() model(-0.01,0), ...
    'A negative effectiveness loss must be rejected.');
assertRejects(@() model(1.01,0), ...
    'An effectiveness loss above one must be rejected.');
assertRejects(@() model(NaN,0), ...
    'A nonfinite effectiveness loss must be rejected.');
assertRejects(@() model(Inf,0), ...
    'An infinite effectiveness loss must be rejected.');
assertRejects(@() model(0.20i,0), ...
    'A complex effectiveness loss must be rejected.');
assertRejects(@() model(0,[0.5 1.0]), ...
    'A nonscalar flow-sensor bias must be rejected.');
assertRejects(@() model(0,-0.01), ...
    'A negative flow-sensor bias magnitude must be rejected.');
assertRejects(@() model(0,10.01), ...
    'A flow-sensor bias above the resource bound must be rejected.');
assertRejects(@() model(0,NaN), ...
    'A nonfinite flow-sensor bias must be rejected.');
assertRejects(@() model(0,Inf), ...
    'An infinite flow-sensor bias must be rejected.');
assertRejects(@() model(0,0.50i), ...
    'A complex flow-sensor bias must be rejected.');

recovered = model(0.20,0);
assert(isequal(recovered,baseline), ...
    'Rejected malformed calls must not contaminate exact recovery.');

disp(['P11 checks passed. Explain why the P10 flow alarm admits two ' ...
    'causes, how pressure creates codes 11 and 10, and why weak, ' ...
    'combined, or flow-only cases bound the isolation claim.']);
end

function assertRejects(operation,message)
didReject = false;
try
    operation();
catch
    didReject = true;
end
assert(didReject,message);
end
