function interactive
%INTERACTIVE Explore one fault-tree view and one probability view at a time.
% Pin this module's implementation before the launcher removes its path.
modelForThisModule = @model;
fig = uifigure('Name','P05 Build a Fault Tree', ...
    'Position',[100 100 1120 720]);
gridLayout = uigridlayout(fig,[6 3]);
gridLayout.RowHeight = {28,50,32,34,'1x',120};
gridLayout.ColumnWidth = {'1x','1x','1x'};

sharedLabel = uilabel(gridLayout, ...
    'Text','Shared-supply failure per mission (dimensionless)');
sharedLabel.Layout.Row = 1; sharedLabel.Layout.Column = 1;
pumpALabel = uilabel(gridLayout, ...
    'Text','Pump-A failure per mission (dimensionless)');
pumpALabel.Layout.Row = 1; pumpALabel.Layout.Column = 2;
pumpBLabel = uilabel(gridLayout, ...
    'Text','Pump-B failure per mission (dimensionless)');
pumpBLabel.Layout.Row = 1; pumpBLabel.Layout.Column = 3;

sharedControl = uispinner(gridLayout,'Limits',[0 1],'Step',0.005, ...
    'Value',0.005,'ValueDisplayFormat','%.3f');
sharedControl.Layout.Row = 2; sharedControl.Layout.Column = 1;
pumpAControl = uispinner(gridLayout,'Limits',[0 1],'Step',0.01, ...
    'Value',0.10,'ValueDisplayFormat','%.2f');
pumpAControl.Layout.Row = 2; pumpAControl.Layout.Column = 2;
pumpBControl = uispinner(gridLayout,'Limits',[0 1],'Step',0.01, ...
    'Value',0.10,'ValueDisplayFormat','%.2f');
pumpBControl.Layout.Row = 2; pumpBControl.Layout.Column = 3;

viewLabel = uilabel(gridLayout,'Text','Visible view (one at a time)');
viewLabel.Layout.Row = 3; viewLabel.Layout.Column = 1;
viewControl = uidropdown(gridLayout, ...
    'Items',{'Fault-tree structure','Non-overlapping contributions'}, ...
    'Value','Fault-tree structure');
viewControl.Layout.Row = 3; viewControl.Layout.Column = [2 3];

missionLabel = uilabel(gridLayout, ...
    'Text','Mission boundary: fixed 1000 h, no repair');
missionLabel.Layout.Row = 4; missionLabel.Layout.Column = [1 2];
resetButton = uibutton(gridLayout,'push','Text','Reset baseline', ...
    'ButtonPushedFcn',@resetControls);
resetButton.Layout.Row = 4; resetButton.Layout.Column = 3;

displayAxes = uiaxes(gridLayout);
displayAxes.Layout.Row = 5; displayAxes.Layout.Column = [1 3];
summary = uilabel(gridLayout,'WordWrap','on');
summary.Layout.Row = 6; summary.Layout.Column = [1 3];

sharedControl.ValueChangedFcn = @(~,~) updatePlots();
pumpAControl.ValueChangedFcn = @(~,~) updatePlots();
pumpBControl.ValueChangedFcn = @(~,~) updatePlots();
viewControl.ValueChangedFcn = @(~,~) updatePlots();
updatePlots();

    function resetControls(~,~)
        sharedControl.Value = 0.005;
        pumpAControl.Value = 0.10;
        pumpBControl.Value = 0.10;
        viewControl.Value = 'Fault-tree structure';
        updatePlots();
    end

    function updatePlots
        out = modelForThisModule(sharedControl.Value,pumpAControl.Value, ...
            pumpBControl.Value);
        if strcmp(viewControl.Value,'Fault-tree structure')
            drawTree(displayAxes,out);
        else
            cla(displayAxes,'reset');
            bar(displayAxes,1:3,[out.sharedExclusiveContribution, ...
                out.dualPumpExclusiveContribution,out.topEventProbability], ...
                0.62);
            grid(displayAxes,'on'); xticks(displayAxes,1:3);
            xticklabels(displayAxes, ...
                {'S occurs','No S; A and B occur','Exact top event'});
            ylabel(displayAxes, ...
                'Event probability per mission (dimensionless)');
            title(displayAxes, ...
                'Exact non-overlapping contributions to loss of cooling');
            upperLimit = max(0.02,1.18*out.topEventProbability);
            ylim(displayAxes,[0 min(1,upperLimit)]);
        end

        summary.Text = sprintf([ ...
            'For the fixed 1000-hour no-repair mission, T = S OR (A AND B); ' ...
            'minimal cut sets are {S} and {A,B}. qT = qS + ' ...
            '(1-qS)qAqB = %.6f per mission. The exact ' ...
            'contributions are %.6f shared and %.6f no-shared/dual-pump. ' ...
            'Gate logic and the all-three-basic-event independence ' ...
            'assumption are separate claims.'], ...
            out.topEventProbability,out.sharedExclusiveContribution, ...
            out.dualPumpExclusiveContribution);
    end

    function drawTree(axesHandle,out)
        cla(axesHandle,'reset'); hold(axesHandle,'on');
        plot(axesHandle,[5 5],[8.85 8.15],'k-','LineWidth',1.4);
        plot(axesHandle,[5 2.2],[7.75 6.75],'k-','LineWidth',1.4);
        plot(axesHandle,[5 7.4],[7.75 6.75],'k-','LineWidth',1.4);
        plot(axesHandle,[7.4 6.25],[5.95 4.95],'k-','LineWidth',1.4);
        plot(axesHandle,[7.4 8.55],[5.95 4.95],'k-','LineWidth',1.4);
        text(axesHandle,5,9.25,sprintf( ...
            'TOP: cooling unavailable  Q = %.5f',out.topEventProbability), ...
            'HorizontalAlignment','center','FontWeight','bold', ...
            'BackgroundColor',[1.00 0.86 0.82],'Margin',6);
        text(axesHandle,5,7.95,'OR','HorizontalAlignment','center', ...
            'FontWeight','bold','BackgroundColor',[0.92 0.92 0.92], ...
            'Margin',5);
        text(axesHandle,2.2,6.45,sprintf(['S: shared supply lost\n' ...
            'qS = %.3f'],out.sharedSupplyFailureProbability), ...
            'HorizontalAlignment','center', ...
            'BackgroundColor',[0.86 0.92 1.00],'Margin',6);
        text(axesHandle,7.4,6.25,'AND','HorizontalAlignment','center', ...
            'FontWeight','bold','BackgroundColor',[0.92 0.92 0.92], ...
            'Margin',5);
        text(axesHandle,6.25,4.65,sprintf(['A: pump A fails\n' ...
            'qA = %.3f'],out.pumpAFailureProbability), ...
            'HorizontalAlignment','center', ...
            'BackgroundColor',[0.90 0.97 0.90],'Margin',6);
        text(axesHandle,8.55,4.65,sprintf(['B: pump B fails\n' ...
            'qB = %.3f'],out.pumpBFailureProbability), ...
            'HorizontalAlignment','center', ...
            'BackgroundColor',[0.90 0.97 0.90],'Margin',6);
        text(axesHandle,5,3.25,'Minimal cut sets: {S} and {A,B}', ...
            'HorizontalAlignment','center','FontWeight','bold');
        hold(axesHandle,'off'); axis(axesHandle,[0.5 9.8 2.8 9.8]);
        axis(axesHandle,'off');
        title(axesHandle, ...
            'Fault-tree structure and fixed-mission event probabilities');
    end
end
