%% P05 - Build a Fault Tree
% Guiding question:
% What inputs, observable effects, and failure modes matter when you build a
% Fault Tree?

%% Read the system boundary before touching a control
disp(['P04 separated one shared event from channel-specific failures. P05 ' ...
    'makes that structure explicit for a two-pump cooling function over a ' ...
    'fixed 1000-hour no-repair mission: T = S OR (A AND B).']);
disp(['qS, qA, and qB are dimensionless event probabilities over those same ' ...
    '1000 hours. Minimal cut sets are {S} and {A,B}; all three basic events ' ...
    'are independent in this teaching calculation.']);

%% Make one prediction, then show the baseline before any lever
disp(['Prediction: with the shared supply healthy, does pump A failing by ' ...
    'itself activate loss of cooling?']);
baseline = model(0.005,0.10,0.10);
figure('Name','P05 lesson baseline: fault-tree structure');
baselineAxes = axes; hold(baselineAxes,'on');
plot(baselineAxes,[5 5],[8.85 8.15],'k-','LineWidth',1.4);
plot(baselineAxes,[5 2.2],[7.75 6.75],'k-','LineWidth',1.4);
plot(baselineAxes,[5 7.4],[7.75 6.75],'k-','LineWidth',1.4);
plot(baselineAxes,[7.4 6.25],[5.95 4.95],'k-','LineWidth',1.4);
plot(baselineAxes,[7.4 8.55],[5.95 4.95],'k-','LineWidth',1.4);
text(baselineAxes,5,9.25,sprintf('TOP: cooling unavailable  Q = %.5f', ...
    baseline.topEventProbability),'HorizontalAlignment','center', ...
    'FontWeight','bold','BackgroundColor',[1.00 0.86 0.82],'Margin',6);
text(baselineAxes,5,7.95,'OR','HorizontalAlignment','center', ...
    'FontWeight','bold','BackgroundColor',[0.92 0.92 0.92],'Margin',5);
text(baselineAxes,2.2,6.45,sprintf('S: shared supply lost\nqS = %.3f', ...
    baseline.sharedSupplyFailureProbability),'HorizontalAlignment','center', ...
    'BackgroundColor',[0.86 0.92 1.00],'Margin',6);
text(baselineAxes,7.4,6.25,'AND','HorizontalAlignment','center', ...
    'FontWeight','bold','BackgroundColor',[0.92 0.92 0.92],'Margin',5);
text(baselineAxes,6.25,4.65,sprintf('A: pump A fails\nqA = %.2f', ...
    baseline.pumpAFailureProbability),'HorizontalAlignment','center', ...
    'BackgroundColor',[0.90 0.97 0.90],'Margin',6);
text(baselineAxes,8.55,4.65,sprintf('B: pump B fails\nqB = %.2f', ...
    baseline.pumpBFailureProbability),'HorizontalAlignment','center', ...
    'BackgroundColor',[0.90 0.97 0.90],'Margin',6);
text(baselineAxes,5,3.25,'Minimal cut sets: {S} and {A,B}', ...
    'HorizontalAlignment','center','FontWeight','bold');
hold(baselineAxes,'off'); axis(baselineAxes,[0.5 9.8 2.8 9.8]);
axis(baselineAxes,'off');
title(baselineAxes,'Baseline fault tree for the 1000-hour cooling mission');
fprintf(['Baseline: qS = %.3f, qA = %.2f, qB = %.2f, Q_top = %.5f ' ...
    'per 1000-hour mission.\n'],baseline.sharedSupplyFailureProbability, ...
    baseline.pumpAFailureProbability,baseline.pumpBFailureProbability, ...
    baseline.topEventProbability);

%% Move one lever only after reading the baseline
disp(['The live window opens at this baseline. First switch once to the ' ...
    'non-overlapping contribution view without moving a lever.']);
disp(['Then increase qS and explain the changed singleton path. Reset, ' ...
    'increase only qA, and explain why fixed qB conditions the AND path.']);
disp(['After the two levers, run the final broken-gate section of ' ...
    'experiment.m, answer checks.md one question at a time, and teach back ' ...
    'the equation plus the wrong-OR symptom in two sentences.']);
interactive;
