function out = model(sharedSupplyFailureProbability, ...
    pumpAFailureProbability,pumpBFailureProbability)
%MODEL Quantify T = S OR (A AND B) over one fixed mission.
%   S is one shared supply-loss basic event. A and B are pump-specific
%   failure events. S, A, and B are independent in this teaching model. All
%   inputs are dimensionless probabilities over the same fixed 1000-hour
%   no-repair mission boundary.
arguments
    sharedSupplyFailureProbability (1,1) double = 0.005
    pumpAFailureProbability (1,1) double = 0.10
    pumpBFailureProbability (1,1) double = 0.10
end

validateattributes(sharedSupplyFailureProbability,{'double'}, ...
    {'real','finite','>=',0,'<=',1},mfilename, ...
    'sharedSupplyFailureProbability');
validateattributes(pumpAFailureProbability,{'double'}, ...
    {'real','finite','>=',0,'<=',1},mfilename, ...
    'pumpAFailureProbability');
validateattributes(pumpBFailureProbability,{'double'}, ...
    {'real','finite','>=',0,'<=',1},mfilename, ...
    'pumpBFailureProbability');

% Minimal cut sets identify sufficient basic-event combinations. Their raw
% probabilities overlap when S, A, and B all occur, so they must not simply
% be added as though they were mutually exclusive.
sharedCutSetProbability = sharedSupplyFailureProbability;
dualPumpCutSetProbability = ...
    pumpAFailureProbability*pumpBFailureProbability;
cutSetProbabilitySum = sharedCutSetProbability + ...
    dualPumpCutSetProbability;
cutSetOverlapProbability = sharedSupplyFailureProbability* ...
    dualPumpCutSetProbability;

% Exact disjoint accounting for T = S OR (A AND B): either S occurs, or S
% does not occur and both independent pump-specific failures occur.
noSharedSupplyFailureProbability = 1-sharedSupplyFailureProbability;
dualPumpExclusiveContribution = noSharedSupplyFailureProbability* ...
    dualPumpCutSetProbability;
topEventProbability = sharedCutSetProbability + ...
    dualPumpExclusiveContribution;
coolingAvailableProbability = noSharedSupplyFailureProbability* ...
    (1-dualPumpCutSetProbability);

% Deliberately wrong comparison: replacing the redundant-pump AND gate
% with OR says that either single pump failure is sufficient to lose cooling.
pumpOrFailureProbability = pumpAFailureProbability + ...
    (1-pumpAFailureProbability)*pumpBFailureProbability;
wrongGateTopEventProbability = sharedSupplyFailureProbability + ...
    noSharedSupplyFailureProbability*pumpOrFailureProbability;
wrongGateOverstatementProbability = wrongGateTopEventProbability - ...
    topEventProbability;

sharedFractionOfTopEvent = 0;
if topEventProbability > 0
    sharedFractionOfTopEvent = sharedCutSetProbability/topEventProbability;
end

out = struct( ...
    'sharedSupplyFailureProbability',sharedSupplyFailureProbability, ...
    'pumpAFailureProbability',pumpAFailureProbability, ...
    'pumpBFailureProbability',pumpBFailureProbability, ...
    'sharedCutSetProbability',sharedCutSetProbability, ...
    'dualPumpCutSetProbability',dualPumpCutSetProbability, ...
    'minimalCutSetProbabilities',[sharedCutSetProbability, ...
        dualPumpCutSetProbability], ...
    'cutSetProbabilitySum',cutSetProbabilitySum, ...
    'cutSetOverlapProbability',cutSetOverlapProbability, ...
    'noSharedSupplyFailureProbability', ...
        noSharedSupplyFailureProbability, ...
    'sharedExclusiveContribution',sharedCutSetProbability, ...
    'dualPumpExclusiveContribution',dualPumpExclusiveContribution, ...
    'disjointContributionProbabilities',[sharedCutSetProbability, ...
        dualPumpExclusiveContribution], ...
    'topEventProbability',topEventProbability, ...
    'coolingAvailableProbability',coolingAvailableProbability, ...
    'sharedFractionOfTopEvent',sharedFractionOfTopEvent, ...
    'topEventSensitivityToSharedSupply', ...
        1-dualPumpCutSetProbability, ...
    'topEventSensitivityToPumpA', ...
        noSharedSupplyFailureProbability*pumpBFailureProbability, ...
    'topEventSensitivityToPumpB', ...
        noSharedSupplyFailureProbability*pumpAFailureProbability, ...
    'pumpOrFailureProbability',pumpOrFailureProbability, ...
    'wrongGateTopEventProbability',wrongGateTopEventProbability, ...
    'wrongGateOverstatementProbability', ...
        wrongGateOverstatementProbability);
end
