function run_checks
%RUN_CHECKS Check P05 gate logic, probabilities, limits, and rejection.
baseline = model(0.005,0.10,0.10);
repeat = model(0.005,0.10,0.10);
assert(isequal(baseline,repeat), ...
    'Identical inputs must produce identical outputs.');

assert(isequal(size(baseline.minimalCutSetProbabilities),[1 2]) && ...
    isequal(size(baseline.disjointContributionProbabilities),[1 2]), ...
    'The bounded scalar model must retain two fixed-size cut-set views.');
probabilityOutputs = [baseline.sharedCutSetProbability, ...
    baseline.dualPumpCutSetProbability, ...
    baseline.sharedExclusiveContribution, ...
    baseline.dualPumpExclusiveContribution, ...
    baseline.topEventProbability,baseline.coolingAvailableProbability, ...
    baseline.pumpOrFailureProbability, ...
    baseline.wrongGateTopEventProbability];
assert(all(isfinite(probabilityOutputs)) && ...
    all(probabilityOutputs >= 0 & probabilityOutputs <= 1), ...
    'Every event probability must remain finite and in [0,1].');
assert(abs(baseline.topEventProbability + ...
    baseline.coolingAvailableProbability - 1) < 1e-15, ...
    'Top-event and cooling-available probabilities must be complementary.');
assert(abs(baseline.topEventProbability - ...
    (baseline.sharedExclusiveContribution + ...
    baseline.dualPumpExclusiveContribution)) < 1e-15, ...
    'The two mutually exclusive contributions must add to the top event.');
assert(abs(baseline.topEventProbability - ...
    (baseline.cutSetProbabilitySum - ...
    baseline.cutSetOverlapProbability)) < 1e-15, ...
    'Inclusion-exclusion must agree with the exact disjoint calculation.');

expectedDualPumpCutSet = 0.10*0.10;
expectedDualPumpContribution = (1-0.005)*expectedDualPumpCutSet;
expectedTopEvent = 0.005+expectedDualPumpContribution;
expectedCoolingAvailable = (1-0.005)*(1-expectedDualPumpCutSet);
expectedWrongPumpOr = 0.10+(1-0.10)*0.10;
expectedWrongTopEvent = 0.005+(1-0.005)*expectedWrongPumpOr;
assert(abs(baseline.dualPumpCutSetProbability- ...
    expectedDualPumpCutSet) < 1e-15, ...
    'The {A,B} cut-set probability must independently equal qA*qB.');
assert(abs(baseline.dualPumpExclusiveContribution- ...
    expectedDualPumpContribution) < 1e-15, ...
    'The dual-pump contribution must include no shared-supply event.');
assert(abs(baseline.topEventProbability-expectedTopEvent) < 1e-15 && ...
    abs(baseline.topEventProbability-0.01495) < 1e-15, ...
    'The baseline top-event probability must match an independent equation.');
assert(abs(baseline.coolingAvailableProbability- ...
    expectedCoolingAvailable) < 1e-15 && ...
    abs(baseline.coolingAvailableProbability-0.98505) < 1e-15, ...
    'The baseline success complement must match an independent equation.');
assert(abs(baseline.wrongGateTopEventProbability- ...
    expectedWrongTopEvent) < 1e-15 && ...
    abs(baseline.wrongGateTopEventProbability-0.19405) < 1e-15, ...
    'The deliberately wrong OR-gate reference must remain recognizable.');
assert(abs(baseline.wrongGateOverstatementProbability-0.17910) < 1e-15, ...
    'The broken gate must retain its independently known overstatement.');
assert(abs(baseline.topEventSensitivityToSharedSupply-0.99) < 1e-15, ...
    'The baseline qS sensitivity must independently equal 1-qA*qB.');
assert(abs(baseline.topEventSensitivityToPumpA-0.0995) < 1e-15 && ...
    abs(baseline.topEventSensitivityToPumpB-0.0995) < 1e-15, ...
    'Each baseline pump sensitivity must equal (1-qS) times the other pump probability.');

% Enumerate every Boolean state independently of the probability formula.
% Columns are S, A, and B; rows are binary states 000 through 111.
states = logical([0 0 0; 0 0 1; 0 1 0; 0 1 1; ...
    1 0 0; 1 0 1; 1 1 0; 1 1 1]);
correctTopState = states(:,1) | (states(:,2) & states(:,3));
expectedTopState = logical([0;0;0;1;1;1;1;1]);
assert(isequal(correctTopState,expectedTopState), ...
    'Truth-state enumeration must implement S OR (A AND B).');
brokenTopState = states(:,1) | states(:,2) | states(:,3);
assert(~correctTopState(2) && brokenTopState(2) && ...
    ~correctTopState(3) && brokenTopState(3), ...
    'The broken OR gate must falsely trigger for either single-pump failure.');
onePumpOnly = model(0,1,0);
assert(onePumpOnly.topEventProbability == 0 && ...
    onePumpOnly.wrongGateTopEventProbability == 1, ...
    'With S=0, A=1, B=0, only the broken OR gate may activate the top event.');

eventProbabilities = repmat([0.005 0.10 0.10],8,1);
numericStates = double(states);
stateProbabilities = prod(numericStates.*eventProbabilities + ...
    (1-numericStates).*(1-eventProbabilities),2);
assert(abs(sum(stateProbabilities)-1) < 1e-15, ...
    'Independent Boolean-state probabilities must form a complete partition.');
enumeratedTopEvent = sum(stateProbabilities(correctTopState));
assert(abs(enumeratedTopEvent-baseline.topEventProbability) < 1e-15, ...
    'Independent truth-state summation must reproduce the top-event probability.');

sharedSweep = [0 0.005 0.02 0.05];
expectedSharedSweep = [0.01 0.01495 0.0298 0.0595];
actualSharedSweep = zeros(size(sharedSweep));
rawDualCutSetSweep = zeros(size(sharedSweep));
sharedPathSweep = zeros(size(sharedSweep));
dualPumpDisjointSweep = zeros(size(sharedSweep));
for k = 1:numel(sharedSweep)
    changed = model(sharedSweep(k),0.10,0.10);
    actualSharedSweep(k) = changed.topEventProbability;
    rawDualCutSetSweep(k) = changed.dualPumpCutSetProbability;
    sharedPathSweep(k) = changed.sharedExclusiveContribution;
    dualPumpDisjointSweep(k) = ...
        changed.dualPumpExclusiveContribution;
end
assert(max(abs(actualSharedSweep-expectedSharedSweep)) < 1e-15, ...
    'The shared-supply sweep must match independent reference values.');
assert(all(diff(actualSharedSweep) > 0), ...
    'Increasing shared-supply probability must increase the top event.');
assert(max(abs(rawDualCutSetSweep-0.01)) < 1e-15, ...
    'Changing qS must not change the raw {A,B} cut-set probability.');
assert(max(abs(sharedPathSweep-sharedSweep)) < 1e-15, ...
    'The shared path must equal qS throughout the shared-supply sweep.');
assert(all(diff(sharedPathSweep) > 0) && ...
    all(diff(dualPumpDisjointSweep) < 0), ...
    ['Increasing qS must raise the shared path while reducing the ' ...
    'disjoint no-shared/dual-pump path.']);
assert(max(abs(actualSharedSweep-(sharedPathSweep+ ...
    dualPumpDisjointSweep))) < 1e-15, ...
    'The swept disjoint paths must add to the exact top event.');

pumpASweep = [0 0.05 0.10 0.20 0.40];
expectedPumpASweep = [0.005 0.009975 0.01495 0.0249 0.0448];
actualPumpASweep = zeros(size(pumpASweep));
sharedContributionSweep = zeros(size(pumpASweep));
for k = 1:numel(pumpASweep)
    changed = model(0.005,pumpASweep(k),0.10);
    actualPumpASweep(k) = changed.topEventProbability;
    sharedContributionSweep(k) = changed.sharedExclusiveContribution;
end
assert(max(abs(actualPumpASweep-expectedPumpASweep)) < 1e-15, ...
    'The pump-A sweep must match independent reference values.');
assert(all(diff(actualPumpASweep) > 0), ...
    'Increasing qA at fixed qB must increase the top event.');
assert(all(sharedContributionSweep == 0.005), ...
    'Changing qA must leave the shared-event contribution unchanged.');

swapped = model(0.005,0.10,0.25);
reverseSwapped = model(0.005,0.25,0.10);
assert(swapped.topEventProbability == reverseSwapped.topEventProbability, ...
    'Swapping pump A and pump B must preserve the top-event probability.');
assert(swapped.topEventSensitivityToPumpA == ...
    reverseSwapped.topEventSensitivityToPumpB && ...
    swapped.topEventSensitivityToPumpB == ...
    reverseSwapped.topEventSensitivityToPumpA, ...
    'Pump-label symmetry must also swap the two sensitivities.');

noShared = model(0,0.20,0.30);
assert(abs(noShared.topEventProbability-0.20*0.30) < 1e-15, ...
    'With qS=0, the top event must reduce to qA*qB.');
noPumpA = model(0.30,0,0.80);
noPumpB = model(0.30,0.80,0);
assert(noPumpA.topEventProbability == 0.30 && ...
    noPumpB.topEventProbability == 0.30, ...
    'Either zero pump probability must leave only the shared cut set.');
allShared = model(1,0.20,0.30);
assert(allShared.topEventProbability == 1 && ...
    allShared.dualPumpExclusiveContribution == 0, ...
    'A certain shared-supply loss must make the top event certain.');
bothPumpsCertain = model(0.25,1,1);
assert(bothPumpsCertain.topEventProbability == 1 && ...
    bothPumpsCertain.coolingAvailableProbability == 0, ...
    'Two certain pump-specific failures must make loss of cooling certain.');
allZero = model(0,0,0);
assert(allZero.topEventProbability == 0 && ...
    allZero.coolingAvailableProbability == 1 && ...
    allZero.sharedFractionOfTopEvent == 0, ...
    'All-zero basic-event probabilities must give certain cooling availability.');

tinyAnd = model(0,1e-150,1e-150);
assert(tinyAnd.topEventProbability > 0 && ...
    abs(tinyAnd.topEventProbability/1e-300-1) < 1e-14, ...
    'A representable tiny AND probability must not be lost to cancellation.');

overlappingCutSets = model(0.8,0.8,0.8);
assert(abs(overlappingCutSets.cutSetProbabilitySum-1.44) < 1e-15 && ...
    abs(overlappingCutSets.topEventProbability-0.928) < 1e-15, ...
    'A raw cut-set sum may exceed one while the exact union stays bounded.');
assert(overlappingCutSets.cutSetProbabilitySum > 1 && ...
    overlappingCutSets.topEventProbability <= 1, ...
    'Overlapping minimal cut sets must not be treated as disjoint diagnoses.');

overstatementFactor = baseline.wrongGateTopEventProbability/ ...
    baseline.topEventProbability;
assert(overstatementFactor > 10, ...
    'The broken pump-OR gate must produce a recognizable overstatement.');
assert(baseline.wrongGateTopEventProbability > ...
    baseline.topEventProbability, ...
    'Changing AND to OR must add false single-pump top-event states.');

assertRejects(@() model(-0.01,0.10,0.10), ...
    'A negative shared-supply probability must be rejected.');
assertRejects(@() model(1.01,0.10,0.10), ...
    'A shared-supply probability above one must be rejected.');
assertRejects(@() model(NaN,0.10,0.10), ...
    'A nonfinite shared-supply probability must be rejected.');
assertRejects(@() model(Inf,0.10,0.10), ...
    'An infinite shared-supply probability must be rejected.');
assertRejects(@() model(0.1i,0.10,0.10), ...
    'A complex shared-supply probability must be rejected.');
assertRejects(@() model([0.01 0.02],0.10,0.10), ...
    'A nonscalar shared-supply probability must be rejected.');
assertRejects(@() model(0.005,-0.01,0.10), ...
    'A negative pump-A probability must be rejected.');
assertRejects(@() model(0.005,1.01,0.10), ...
    'A pump-A probability above one must be rejected.');
assertRejects(@() model(0.005,NaN,0.10), ...
    'A nonfinite pump-A probability must be rejected.');
assertRejects(@() model(0.005,Inf,0.10), ...
    'An infinite pump-A probability must be rejected.');
assertRejects(@() model(0.005,0.1i,0.10), ...
    'A complex pump-A probability must be rejected.');
assertRejects(@() model(0.005,[0.10 0.20],0.10), ...
    'A nonscalar pump-A probability must be rejected.');
assertRejects(@() model(0.005,0.10,-0.01), ...
    'A negative pump-B probability must be rejected.');
assertRejects(@() model(0.005,0.10,1.01), ...
    'A pump-B probability above one must be rejected.');
assertRejects(@() model(0.005,0.10,NaN), ...
    'A nonfinite pump-B probability must be rejected.');
assertRejects(@() model(0.005,0.10,Inf), ...
    'An infinite pump-B probability must be rejected.');
assertRejects(@() model(0.005,0.10,0.1i), ...
    'A complex pump-B probability must be rejected.');
assertRejects(@() model(0.005,0.10,[0.10 0.20]), ...
    'A nonscalar pump-B probability must be rejected.');

recovered = model(0.005,0.10,0.10);
assert(isequal(recovered,baseline), ...
    'Rejected malformed calls must not contaminate a later valid calculation.');

disp(['P05 checks passed. Explain why {S} is sufficient alone while ' ...
    '{A,B} requires both pump-specific failures.']);
end

function assertRejects(operation,message)
didReject = false;
try
    operation();
catch
    didReject = true;
end
assert(didReject,message);
end
