function out = model(baseHazardPerHour,postChangeMultiplier,changeTimeHours,missionHours,sampleCount)
%MODEL Convert a piecewise-constant hazard history into survival probability.
%   Hazard is the conditional failure rate among items still surviving.
%   Cumulative hazard H(t) is its time integral, and S(t) = exp(-H(t)).
arguments
    baseHazardPerHour (1,1) double = 2e-4
    postChangeMultiplier (1,1) double = 1
    changeTimeHours (1,1) double = 1000
    missionHours (1,1) double = 3000
    sampleCount (1,1) double = 601
end

validateattributes(baseHazardPerHour,{'double'}, ...
    {'real','finite','nonnegative','<=',1e6},mfilename,'baseHazardPerHour');
validateattributes(postChangeMultiplier,{'double'}, ...
    {'real','finite','nonnegative','<=',1e6},mfilename,'postChangeMultiplier');
validateattributes(changeTimeHours,{'double'}, ...
    {'real','finite','nonnegative','<=',1e9},mfilename,'changeTimeHours');
validateattributes(missionHours,{'double'}, ...
    {'real','finite','positive','<=',1e9},mfilename,'missionHours');
validateattributes(sampleCount,{'double'}, ...
    {'real','finite','integer','>=',2,'<=',10000},mfilename,'sampleCount');

if changeTimeHours > missionHours
    error('P02:model:ChangeAfterMission', ...
        'changeTimeHours must not exceed missionHours.');
end

timeHours = linspace(0,missionHours,sampleCount);
if sampleCount > 2 && changeTimeHours > 0 && changeTimeHours < missionHours
    [~,nearestInterior] = min(abs(timeHours(2:end-1)-changeTimeHours));
    timeHours(nearestInterior+1) = changeTimeHours;
end
hoursAtBaseHazard = min(timeHours,changeTimeHours);
hoursAfterChange = max(timeHours-changeTimeHours,0);

hazardPerHour = baseHazardPerHour*ones(size(timeHours));
hazardPerHour(timeHours >= changeTimeHours) = ...
    baseHazardPerHour*postChangeMultiplier;
cumulativeHazard = baseHazardPerHour*hoursAtBaseHazard + ...
    baseHazardPerHour*postChangeMultiplier*hoursAfterChange;
survivalProbability = exp(-cumulativeHazard);
failureProbability = -expm1(-cumulativeHazard);

out = struct( ...
    'timeHours',timeHours, ...
    'hazardPerHour',hazardPerHour, ...
    'cumulativeHazard',cumulativeHazard, ...
    'survivalProbability',survivalProbability, ...
    'failureProbability',failureProbability, ...
    'missionHazardPerHour',hazardPerHour(end), ...
    'missionCumulativeHazard',cumulativeHazard(end), ...
    'missionSurvival',survivalProbability(end), ...
    'missionFailureProbability',failureProbability(end), ...
    'expectedSurvivorsPerThousand',1000*survivalProbability(end), ...
    'baseHazardPerHour',baseHazardPerHour, ...
    'postChangeMultiplier',postChangeMultiplier, ...
    'changeTimeHours',changeTimeHours, ...
    'missionHours',missionHours, ...
    'sampleCount',sampleCount);
end
