function run_checks
%RUN_CHECKS Check P02 equations, limits, malformed inputs, and bounds.
baseline = model(2e-4,1,1000,3000,601);
repeat = model(2e-4,1,1000,3000,601);
assert(isequal(baseline,repeat),'Identical inputs must produce identical outputs.');

assert(baseline.survivalProbability(1) == 1,'Survival must start at one.');
assert(baseline.cumulativeHazard(1) == 0,'Cumulative hazard must start at zero.');
assert(baseline.timeHours(1) == 0 && baseline.timeHours(end) == 3000, ...
    'The time grid must include both mission endpoints.');
assert(all(size(baseline.timeHours) == size(baseline.hazardPerHour)) && ...
    all(size(baseline.timeHours) == size(baseline.survivalProbability)), ...
    'All model histories must share one bounded time grid.');
assert(all(baseline.hazardPerHour >= 0 & baseline.cumulativeHazard >= 0), ...
    'Hazard and cumulative hazard must be nonnegative.');
assert(all(diff(baseline.cumulativeHazard) >= 0), ...
    'Nonnegative hazard must not reduce cumulative hazard.');
assert(all(diff(baseline.survivalProbability) <= 10*eps), ...
    'Nonnegative hazard must not increase survival.');
assert(all(baseline.survivalProbability >= 0 & baseline.survivalProbability <= 1), ...
    'Survival must remain in [0,1].');
assert(max(abs(baseline.survivalProbability + baseline.failureProbability - 1)) < 1e-14, ...
    'Survival and failure probability must be complementary.');
assert(max(abs(-log(baseline.survivalProbability)-baseline.cumulativeHazard)) < 1e-12, ...
    'The independent relationship -log(S)=H must hold.');

constantHazard = model(2e-4,1,700,3000,601);
constantExpected = exp(-2e-4*constantHazard.timeHours);
assert(max(abs(constantHazard.survivalProbability-constantExpected)) < 1e-14, ...
    'Constant hazard must recover the P01 exponential reliability law.');

changedHazard = model(2e-4,4,1000,3000,601);
expectedMissionHazard = 2e-4*1000 + (2e-4*4)*(3000-1000);
assert(abs(changedHazard.missionCumulativeHazard-expectedMissionHazard) < 1e-14, ...
    'Pre-change and post-change exposure must accumulate independently.');
assert(abs(changedHazard.missionSurvival-exp(-expectedMissionHazard)) < 1e-14, ...
    'Mission survival must be exp(-total cumulative hazard).');
assert(changedHazard.missionSurvival < baseline.missionSurvival, ...
    'A larger post-change hazard must reduce later survival.');

lowMultiplier = model(2e-4,0.25,1000,3000,601);
highMultiplier = model(2e-4,4,1000,3000,601);
throughChange = lowMultiplier.timeHours <= 1000;
afterChange = lowMultiplier.timeHours > 1000;
assert(isequal(lowMultiplier.survivalProbability(throughChange), ...
    highMultiplier.survivalProbability(throughChange)), ...
    'Multiplier changes must leave survival identical through the change time.');
assert(all(highMultiplier.survivalProbability(afterChange) <= ...
    lowMultiplier.survivalProbability(afterChange)) && ...
    any(highMultiplier.survivalProbability(afterChange) < ...
    lowMultiplier.survivalProbability(afterChange)), ...
    'A larger multiplier must lower survival only after the change time.');

changeAtStart = model(2e-4,4,0,3000,601);
assert(max(abs(changeAtStart.survivalProbability- ...
    exp(-(2e-4*4)*changeAtStart.timeHours))) < 1e-14, ...
    'A change at time zero must apply the multiplied hazard for the full mission.');
changeAtEndLow = model(2e-4,0.25,3000,3000,601);
changeAtEndHigh = model(2e-4,4,3000,3000,601);
assert(isequal(changeAtEndLow.survivalProbability,changeAtEndHigh.survivalProbability), ...
    'A change at mission end must not alter accumulated survival.');

zeroHazard = model(0,8,1000,3000,601);
assert(all(zeroHazard.survivalProbability == 1), ...
    'Zero hazard is the limiting case of certain survival.');
stoppedHazard = model(2e-4,0,1000,3000,601);
expectedPlateau = exp(-2e-4*1000);
assert(abs(stoppedHazard.missionSurvival-expectedPlateau) < 1e-14, ...
    'Survival must plateau when post-change hazard is zero.');
offGridChange = model(2e-4,3,1234,3000,601);
assert(any(offGridChange.timeHours == 1234), ...
    'An interior hazard change must appear exactly on the sampled time grid.');

tinyExposure = model(1e-20,1,0,1,3);
assert(tinyExposure.missionFailureProbability > 0 && ...
    abs(tinyExposure.missionFailureProbability/1e-20-1) < 1e-12, ...
    'Tiny cumulative hazard must retain failure probability without cancellation.');

brokenCase = model(1e-3,3,500,2000,601);
linearSurvival = 1-brokenCase.cumulativeHazard;
assert(any(linearSurvival < 0), ...
    'The broken linear approximation must expose a negative-probability symptom.');
assert(all(brokenCase.survivalProbability >= 0), ...
    'The exponential survival law must remain nonnegative in the broken scenario.');

assertRejects(@() model(-1e-4,1,1000,3000,601), ...
    'Negative hazard must be rejected.');
assertRejects(@() model(2e-4,-1,1000,3000,601), ...
    'Negative multiplier must be rejected.');
assertRejects(@() model(2e-4,1,3001,3000,601), ...
    'A condition change after mission end must be rejected.');
assertRejects(@() model(2e-4,1,1000,0,601), ...
    'A zero-duration mission must be rejected.');
assertRejects(@() model(NaN,1,1000,3000,601), ...
    'A nonfinite hazard must be rejected.');
assertRejects(@() model(Inf,1,1000,3000,601), ...
    'An infinite hazard must be rejected.');
assertRejects(@() model(1i,1,1000,3000,601), ...
    'A complex hazard must be rejected.');
assertRejects(@() model([1e-4 2e-4],1,1000,3000,601), ...
    'A nonscalar hazard must be rejected.');
assertRejects(@() model(1e6+1,1,1000,3000,601), ...
    'Hazard beyond the finite calculation domain must be rejected.');
assertRejects(@() model(2e-4,1e6+1,1000,3000,601), ...
    'Multiplier beyond the finite calculation domain must be rejected.');
assertRejects(@() model(2e-4,1,1000,1e9+1,601), ...
    'Mission duration beyond the finite calculation domain must be rejected.');
assertRejects(@() model(2e-4,1,1000,3000,1), ...
    'Too few samples must be rejected.');
assertRejects(@() model(2e-4,1,1000,3000,2.5), ...
    'A fractional sample count must be rejected.');
assertRejects(@() model(2e-4,1,1000,3000,10001), ...
    'The declared sample resource bound must be enforced.');

bounded = model(2e-4,1,1000,3000,10000);
assert(numel(bounded.timeHours) == 10000, ...
    'The maximum supported sample count must remain usable and exact.');
disp('P02 checks passed. Explain why S=1-H failed before claiming completion.');
end

function assertRejects(operation,message)
didReject = false;
try
    operation();
catch
    didReject = true;
end
assert(didReject,message);
end
