%% P04 - Expose Common-Cause Failure
% Guiding question:
% What inputs, observable effects, and failure modes matter when you expose
% Common-Cause Failure?

%% Read the mechanism before touching a control
disp(['P03 asked whether a repairable item is up now. P04 deliberately ' ...
    'returns to no-repair mission reliability to isolate dependence between ' ...
    'redundant channels.']);
disp(['Each channel keeps marginal hazard lambda. Beta allocates beta*lambda ' ...
    'to one shared all-channel event and leaves (1-beta)*lambda as an ' ...
    'independent failure mode on each channel.']);

%% Make one prediction before the baseline
disp(['Prediction: if six channels replace two while beta stays at 0.05, ' ...
    'will mission failure probability approach zero or a shared-event term?']);
disp(['Run experiment.m one %% section at a time: reliability baseline, ' ...
    'failure-mode mechanism, beta lever, channel-count lever, then broken case.']);

%% Open the live controls after observing the baseline
disp(['In interactive.m, move beta first while every other control stays ' ...
    'fixed. Reset, then move only channel count. Switch from reliability ' ...
    'comparison to failure-mode decomposition only after explaining the first view.']);
interactive;

%% Explain and teach back
disp(['Mechanism first: added channels reduce the probability that all ' ...
    'independent modes fail, but no channel count reduces the probability ' ...
    'that one shared event has occurred.']);
disp(['Teach back in two sentences: name lambda, beta, channel count, and ' ...
    'mission time, then explain why equal marginal reliability does not ' ...
    'prove independent channel outcomes.']);
