function out = model(channelFailureRatePerHour,commonCauseFraction,channelCount,missionHours,sampleCount)
%MODEL Reliability of a one-out-of-n group with one shared failure mode.
%   The beta-factor teaching model preserves each channel's marginal
%   constant hazard lambda while splitting it into shared and independent
%   parts: lambda_c=beta*lambda and lambda_i=(1-beta)*lambda.
arguments
    channelFailureRatePerHour (1,1) double = 1e-4
    commonCauseFraction (1,1) double = 0.05
    channelCount (1,1) double = 2
    missionHours (1,1) double = 1000
    sampleCount (1,1) double = 601
end

validateattributes(channelFailureRatePerHour,{'double'}, ...
    {'real','finite','nonnegative','<=',1e6},mfilename,'channelFailureRatePerHour');
validateattributes(commonCauseFraction,{'double'}, ...
    {'real','finite','>=',0,'<=',1},mfilename,'commonCauseFraction');
validateattributes(channelCount,{'double'}, ...
    {'real','finite','integer','>=',1,'<=',128},mfilename,'channelCount');
validateattributes(missionHours,{'double'}, ...
    {'real','finite','>=',1e-6,'<=',1e9},mfilename,'missionHours');
validateattributes(sampleCount,{'double'}, ...
    {'real','finite','integer','>=',2,'<=',10000},mfilename,'sampleCount');

commonCauseRatePerHour = commonCauseFraction*channelFailureRatePerHour;
independentFailureRatePerHour = ...
    (1-commonCauseFraction)*channelFailureRatePerHour;
timeHours = linspace(0,missionHours,sampleCount);
commonCauseExposure = commonCauseRatePerHour*timeHours;
independentExposure = independentFailureRatePerHour*timeHours;
marginalChannelExposure = channelFailureRatePerHour*timeHours;

noCommonCauseProbability = exp(-commonCauseExposure);
commonCauseEventProbability = -expm1(-commonCauseExposure);
independentChannelSurvivalProbability = ...
    exp(-independentExposure);
independentChannelFailureProbability = ...
    -expm1(-independentExposure);
[independentExhaustionConditionalProbability, ...
    logParallelSurvivalConditional] = ...
    parallelFailureAndLogSurvival(independentExposure,channelCount);

% These two failure terms are mutually exclusive: either the shared event
% has occurred, or it has not and every independent channel mode has failed.
independentExhaustionProbability = noCommonCauseProbability.* ...
    independentExhaustionConditionalProbability;
systemFailureProbability = commonCauseEventProbability + ...
    independentExhaustionProbability;
systemReliability = exp(-commonCauseExposure+ ...
    logParallelSurvivalConditional);

% The broken independence comparison uses the same marginal channel hazard.
marginalChannelSurvivalProbability = ...
    exp(-marginalChannelExposure);
marginalChannelFailureProbability = ...
    -expm1(-marginalChannelExposure);
[assumedIndependentSystemFailureProbability, ...
    logAssumedIndependentSystemReliability] = ...
    parallelFailureAndLogSurvival(marginalChannelExposure,channelCount);
assumedIndependentSystemReliability = ...
    exp(logAssumedIndependentSystemReliability);
independenceOptimismProbability = systemFailureProbability- ...
    assumedIndependentSystemFailureProbability;

commonCauseFractionOfSystemFailure = zeros(size(timeHours));
hasSystemFailureProbability = systemFailureProbability > 0;
commonCauseFractionOfSystemFailure(hasSystemFailureProbability) = ...
    commonCauseEventProbability(hasSystemFailureProbability)./ ...
    systemFailureProbability(hasSystemFailureProbability);

out = struct( ...
    'timeHours',timeHours, ...
    'systemReliability',systemReliability, ...
    'systemFailureProbability',systemFailureProbability, ...
    'commonCauseEventProbability',commonCauseEventProbability, ...
    'independentExhaustionProbability',independentExhaustionProbability, ...
    'noCommonCauseProbability',noCommonCauseProbability, ...
    'independentChannelSurvivalProbability',independentChannelSurvivalProbability, ...
    'independentChannelFailureProbability',independentChannelFailureProbability, ...
    'marginalChannelSurvivalProbability',marginalChannelSurvivalProbability, ...
    'marginalChannelFailureProbability',marginalChannelFailureProbability, ...
    'assumedIndependentSystemReliability',assumedIndependentSystemReliability, ...
    'assumedIndependentSystemFailureProbability',assumedIndependentSystemFailureProbability, ...
    'independenceOptimismProbability',independenceOptimismProbability, ...
    'commonCauseFractionOfSystemFailure',commonCauseFractionOfSystemFailure, ...
    'channelFailureRatePerHour',channelFailureRatePerHour, ...
    'commonCauseFraction',commonCauseFraction, ...
    'commonCauseRatePerHour',commonCauseRatePerHour, ...
    'independentFailureRatePerHour',independentFailureRatePerHour, ...
    'channelCount',channelCount, ...
    'missionHours',missionHours, ...
    'sampleCount',sampleCount, ...
    'endpointSystemReliability',systemReliability(end), ...
    'endpointSystemFailureProbability',systemFailureProbability(end), ...
    'endpointCommonCauseEventProbability',commonCauseEventProbability(end), ...
    'endpointIndependentExhaustionProbability',independentExhaustionProbability(end), ...
    'endpointAssumedIndependentFailureProbability', ...
        assumedIndependentSystemFailureProbability(end), ...
    'endpointIndependenceOptimismProbability',independenceOptimismProbability(end));
end

function [allFailedProbability,logAtLeastOneSurvival] = ...
    parallelFailureAndLogSurvival(exposure,channelCount)
% Preserve both Q=(1-exp(-x))^n and its tiny complement 1-Q.
logAllFailed = zeros(size(exposure));
useFailureForm = exposure <= log(2);
logAllFailed(useFailureForm) = channelCount* ...
    log(-expm1(-exposure(useFailureForm)));
useSurvivalForm = ~useFailureForm;
logAllFailed(useSurvivalForm) = channelCount* ...
    log1p(-exp(-exposure(useSurvivalForm)));
allFailedProbability = exp(logAllFailed);

atLeastOneSurvivalProbability = -expm1(logAllFailed);
logAtLeastOneSurvival = log(atLeastOneSurvivalProbability);
% Once a channel survival enters the subnormal range, form n*exp(-x) in
% the log domain. Higher inclusion-exclusion terms are below double range.
largeExposure = exposure > -log(realmin);
logAtLeastOneSurvival(largeExposure) = ...
    log(channelCount)-exposure(largeExposure);
end
