function run_checks
%RUN_CHECKS Check P04 equations, limits, malformed inputs, and bounds.
baseline = model(1e-4,0.05,2,1000,601);
repeat = model(1e-4,0.05,2,1000,601);
assert(isequal(baseline,repeat), ...
    'Identical inputs must produce identical outputs.');

assert(baseline.timeHours(1) == 0 && baseline.timeHours(end) == 1000, ...
    'The bounded time grid must include both mission endpoints.');
assert(all(size(baseline.timeHours) == size(baseline.systemReliability)) && ...
    all(size(baseline.timeHours) == ...
    size(baseline.commonCauseEventProbability)), ...
    'Every probability history must share one bounded time grid.');
assert(baseline.systemReliability(1) == 1 && ...
    baseline.systemFailureProbability(1) == 0, ...
    'A new mission must start reliable with zero accumulated failure probability.');
assert(all(baseline.systemReliability >= 0 & ...
    baseline.systemReliability <= 1), ...
    'System reliability must remain in [0,1].');
assert(all(baseline.systemFailureProbability >= 0 & ...
    baseline.systemFailureProbability <= 1), ...
    'System failure probability must remain in [0,1].');
assert(max(abs(baseline.systemReliability + ...
    baseline.systemFailureProbability - 1)) < 1e-14, ...
    'Reliability and failure probability must be complementary.');
assert(max(abs(baseline.systemFailureProbability - ...
    (baseline.commonCauseEventProbability + ...
    baseline.independentExhaustionProbability))) < 1e-15, ...
    'Shared-event and independent-exhaustion terms must decompose system failure.');
assert(all(diff(baseline.systemReliability) <= 10*eps), ...
    'Nonrepairable mission reliability must not increase with exposure.');
assert(all(diff(baseline.systemFailureProbability) >= -10*eps), ...
    'Accumulated system failure probability must not decrease with exposure.');

expectedCommonRate = 0.05e-4;
expectedIndependentRate = 0.95e-4;
expectedNoCommonCause = exp(-expectedCommonRate*1000);
expectedCommonFailure = -expm1(-expectedCommonRate*1000);
expectedIndependentChannelFailure = ...
    -expm1(-expectedIndependentRate*1000);
expectedIndependentExhaustion = expectedNoCommonCause* ...
    expectedIndependentChannelFailure^2;
expectedSystemFailure = expectedCommonFailure+expectedIndependentExhaustion;
expectedSystemReliability = expectedNoCommonCause* ...
    (1-expectedIndependentChannelFailure^2);
expectedAssumedIndependentFailure = (-expm1(-1e-4*1000))^2;
assert(abs(baseline.commonCauseRatePerHour-expectedCommonRate) < 1e-18, ...
    'The shared hazard must independently equal beta times lambda.');
assert(abs(baseline.independentFailureRatePerHour- ...
    expectedIndependentRate) < 1e-18, ...
    'The independent hazard must independently equal (1-beta) times lambda.');
assert(abs(baseline.endpointCommonCauseEventProbability- ...
    expectedCommonFailure) < 1e-15, ...
    'The endpoint shared-event term must follow its exponential hazard.');
assert(abs(baseline.endpointIndependentExhaustionProbability- ...
    expectedIndependentExhaustion) < 1e-15, ...
    'The independent-exhaustion term must include no shared event and both channel failures.');
assert(abs(baseline.endpointSystemFailureProbability- ...
    expectedSystemFailure) < 1e-15, ...
    'The beta-factor system failure equation must match an independent calculation.');
assert(abs(baseline.endpointSystemReliability- ...
    expectedSystemReliability) < 1e-15, ...
    'The one-out-of-two reliability equation must match an independent calculation.');
assert(abs(baseline.endpointAssumedIndependentFailureProbability- ...
    expectedAssumedIndependentFailure) < 1e-15, ...
    'The comparison must use the same marginal channel hazard.');

independent = model(1e-4,0,2,1000,601);
moreShared = model(1e-4,0.2,2,1000,601);
assert(max(abs(independent.systemReliability- ...
    independent.assumedIndependentSystemReliability)) < 1e-15, ...
    'Beta zero must recover ordinary independent redundancy.');
assert(moreShared.endpointSystemReliability < ...
    baseline.endpointSystemReliability && ...
    baseline.endpointSystemReliability < independent.endpointSystemReliability, ...
    'A larger common-cause fraction must lower redundant-system reliability.');
assert(isequal(independent.marginalChannelSurvivalProbability, ...
    moreShared.marginalChannelSurvivalProbability), ...
    'Changing beta must preserve the stated marginal channel reliability.');
assert(moreShared.endpointIndependenceOptimismProbability > ...
    baseline.endpointIndependenceOptimismProbability, ...
    'A larger shared fraction must increase the independence-assumption error.');

oneChannel = model(1e-4,0.05,1,1000,601);
twoChannels = model(1e-4,0.05,2,1000,601);
sixChannels = model(1e-4,0.05,6,1000,601);
assert(abs(oneChannel.endpointSystemReliability-exp(-0.1)) < 1e-15, ...
    'One channel must retain exp(-lambda*T) regardless of the hazard split.');
assert(isequal(oneChannel.commonCauseEventProbability, ...
    twoChannels.commonCauseEventProbability) && ...
    isequal(twoChannels.commonCauseEventProbability, ...
    sixChannels.commonCauseEventProbability), ...
    'Changing channel count must not change the shared-event contribution.');
assert(sixChannels.endpointIndependentExhaustionProbability < ...
    twoChannels.endpointIndependentExhaustionProbability && ...
    twoChannels.endpointIndependentExhaustionProbability < ...
    oneChannel.endpointIndependentExhaustionProbability, ...
    'Adding channels must reduce the independent-exhaustion term.');
assert(sixChannels.endpointSystemFailureProbability < ...
    twoChannels.endpointSystemFailureProbability && ...
    twoChannels.endpointSystemFailureProbability < ...
    oneChannel.endpointSystemFailureProbability, ...
    'Adding channels must reduce one-out-of-n failure probability at fixed beta.');
assert(sixChannels.endpointSystemFailureProbability >= ...
    sixChannels.endpointCommonCauseEventProbability, ...
    'Redundancy cannot reduce failure probability below the shared-event contribution.');

allSharedTwo = model(1e-4,1,2,1000,601);
allSharedSix = model(1e-4,1,6,1000,601);
assert(max(abs(allSharedTwo.systemReliability-exp(-1e-4* ...
    allSharedTwo.timeHours))) < 1e-15, ...
    'Beta one must make the shared shock equal the full marginal hazard.');
assert(isequal(allSharedTwo.systemReliability,allSharedSix.systemReliability), ...
    'When all hazard is shared, extra channels must provide no benefit.');
assert(all(allSharedSix.independentExhaustionProbability == 0), ...
    'Beta one must leave no independent channel-failure contribution.');

zeroHazard = model(0,0.75,128,1000,601);
assert(all(zeroHazard.systemReliability == 1) && ...
    all(zeroHazard.systemFailureProbability == 0), ...
    'Zero hazard must give certain mission success for every beta and channel count.');
assert(all(zeroHazard.independenceOptimismProbability == 0), ...
    'Zero hazard must leave no independence-assumption error.');

tinyExposure = model(1e-12,0.2,8,1e-6,3);
assert(tinyExposure.endpointCommonCauseEventProbability > 0 && ...
    abs(tinyExposure.endpointCommonCauseEventProbability/2e-19-1) < 1e-14, ...
    'Tiny shared-event probability must survive numerical cancellation.');
assert(tinyExposure.endpointSystemFailureProbability > 0, ...
    'A positive tiny common-cause exposure must not round system failure to zero.');

equalExposureSlow = model(1e-4,0.05,2,1000,601);
equalExposureFast = model(2e-4,0.05,2,500,601);
assert(abs(equalExposureSlow.endpointSystemFailureProbability- ...
    equalExposureFast.endpointSystemFailureProbability) < 1e-15, ...
    'Equal lambda*T exposure must give equal endpoint system failure probability.');

highExposureOne = model(1,0,1,40,2);
expectedHighExposureOne = exp(-40);
assert(highExposureOne.endpointSystemReliability > 0 && ...
    abs(highExposureOne.endpointSystemReliability/expectedHighExposureOne-1) < 1e-14, ...
    'Large-but-representable one-channel survival must not be lost to subtraction.');
highExposureParallel = model(1,0,128,40,2);
expectedHighExposureParallel = -expm1(128*log1p(-exp(-40)));
expectedHighExposureFailure = exp(128*log1p(-exp(-40)));
assert(highExposureParallel.endpointSystemReliability > 0 && ...
    abs(highExposureParallel.endpointSystemReliability/ ...
    expectedHighExposureParallel-1) < 1e-14, ...
    'Large-but-representable parallel survival must not be lost to subtraction.');
assert(highExposureParallel.endpointSystemFailureProbability < 1 && ...
    abs(highExposureParallel.endpointSystemFailureProbability- ...
    expectedHighExposureFailure) < eps(expectedHighExposureFailure), ...
    'Large-exposure parallel failure must retain its representable complement.');
assert(highExposureParallel.endpointSystemFailureProbability + ...
    highExposureParallel.endpointSystemReliability == 1, ...
    'Large-exposure failure and reliability must remain a consistent probability pair.');
assert(highExposureParallel.endpointSystemReliability == ...
    highExposureParallel.assumedIndependentSystemReliability(end), ...
    'Correct and assumed reliability must agree exactly when beta is zero.');

subnormalAggregation = model(1,0,128,746,2);
expectedSubnormalAggregation = exp(log(128)-746);
assert(subnormalAggregation.marginalChannelSurvivalProbability(end) == 0 && ...
    subnormalAggregation.endpointSystemReliability > 0, ...
    'Log-domain aggregation must retain group survival after channel survival underflows.');
assert(subnormalAggregation.endpointSystemReliability == ...
    expectedSubnormalAggregation, ...
    'Subnormal group survival must match the independent log-domain limit.');

extremeExposure = model(1e6,0.25,128,1e9,2);
assert(extremeExposure.endpointSystemReliability == 0 && ...
    extremeExposure.endpointSystemFailureProbability == 1, ...
    'A fully decayed finite-domain mission must retain the exact probability limits.');
assert(all(isfinite([extremeExposure.endpointSystemReliability, ...
    extremeExposure.endpointSystemFailureProbability, ...
    extremeExposure.endpointIndependenceOptimismProbability])), ...
    'Extreme bounded inputs must not produce NaN or infinite outputs.');

brokenCase = model(1e-4,0.05,6,1000,601);
optimismFactor = brokenCase.endpointSystemFailureProbability/ ...
    brokenCase.endpointAssumedIndependentFailureProbability;
assert(brokenCase.endpointAssumedIndependentFailureProbability > 0, ...
    'The broken comparison must retain its small positive independent estimate.');
assert(optimismFactor > 1000, ...
    'The broken independence assumption must produce a recognizable optimism factor.');
assert(brokenCase.endpointSystemFailureProbability > 0.004 && ...
    brokenCase.endpointAssumedIndependentFailureProbability < 1e-6, ...
    'The broken case must expose shared risk hidden by nominal six-channel redundancy.');

assertRejects(@() model(-1e-4,0.05,2,1000,601), ...
    'Negative channel failure rate must be rejected.');
assertRejects(@() model(NaN,0.05,2,1000,601), ...
    'A nonfinite channel failure rate must be rejected.');
assertRejects(@() model(Inf,0.05,2,1000,601), ...
    'An infinite channel failure rate must be rejected.');
assertRejects(@() model(1i,0.05,2,1000,601), ...
    'A complex channel failure rate must be rejected.');
assertRejects(@() model([1e-4 2e-4],0.05,2,1000,601), ...
    'A nonscalar channel failure rate must be rejected.');
assertRejects(@() model(1e6+1,0.05,2,1000,601), ...
    'Channel failure rate beyond the finite domain must be rejected.');
assertRejects(@() model(1e-4,-0.01,2,1000,601), ...
    'A negative common-cause fraction must be rejected.');
assertRejects(@() model(1e-4,1.01,2,1000,601), ...
    'A common-cause fraction above one must be rejected.');
assertRejects(@() model(1e-4,NaN,2,1000,601), ...
    'A nonfinite common-cause fraction must be rejected.');
assertRejects(@() model(1e-4,1i,2,1000,601), ...
    'A complex common-cause fraction must be rejected.');
assertRejects(@() model(1e-4,[0.05 0.1],2,1000,601), ...
    'A nonscalar common-cause fraction must be rejected.');
assertRejects(@() model(1e-4,0.05,0,1000,601), ...
    'Zero channels must be rejected.');
assertRejects(@() model(1e-4,0.05,2.5,1000,601), ...
    'A fractional channel count must be rejected.');
assertRejects(@() model(1e-4,0.05,129,1000,601), ...
    'The channel-count resource bound must be enforced.');
assertRejects(@() model(1e-4,0.05,2,0,601), ...
    'A zero mission duration must be rejected.');
assertRejects(@() model(1e-4,0.05,2,NaN,601), ...
    'A nonfinite mission duration must be rejected.');
assertRejects(@() model(1e-4,0.05,2,1i,601), ...
    'A complex mission duration must be rejected.');
assertRejects(@() model(1e-4,0.05,2,1e9+1,601), ...
    'Mission duration beyond the finite domain must be rejected.');
assertRejects(@() model(1e-4,0.05,2,1000,1), ...
    'Too few samples must be rejected.');
assertRejects(@() model(1e-4,0.05,2,1000,2.5), ...
    'A fractional sample count must be rejected.');
assertRejects(@() model(1e-4,0.05,2,1000,10001), ...
    'The sample resource bound must be enforced.');

bounded = model(1e-4,0.05,128,1000,10000);
assert(numel(bounded.timeHours) == 10000 && bounded.channelCount == 128, ...
    'Maximum supported channel and sample counts must remain usable and exact.');
recovered = model(1e-4,0.05,2,1000,601);
assert(isequal(recovered,baseline), ...
    'Rejected malformed calls must not contaminate a later valid calculation.');

disp(['P04 checks passed. Explain why unchanged marginal channel reliability ' ...
    'does not justify multiplying channel failures as independent.']);
end

function assertRejects(operation,message)
didReject = false;
try
    operation();
catch
    didReject = true;
end
assert(didReject,message);
end
